/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABContactsHelper : NSObject
{
}

+ (id)groupsMatchingName:(id)arg1;
+ (id)contactsMatchingPhone:(id)arg1;
+ (id)contactsMatchingName:(id)arg1 andName:(id)arg2;
+ (id)contactsMatchingName:(id)arg1;
+ (BOOL)addGroup:(id)arg1 withError:(id *)arg2;
+ (BOOL)addContact:(id)arg1 withError:(id *)arg2;
+ (BOOL)firstNameSorting;
+ (id)groups;
+ (int)numberOfGroups;
+ (int)contactsWithoutImageCount;
+ (int)contactsWithImageCount;
+ (int)contactsCount;
+ (id)contacts;
+ (void *)addressBook;

@end

