/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewController.h"

@class NSMutableArray, UIBarButtonItem;

@interface AccountsListViewController : WBTableViewController
{
    NSMutableArray *_users;
    UIBarButtonItem *btnAdd;
    UIBarButtonItem *btnReturn;
    UIBarButtonItem *btnEdit;
    UIBarButtonItem *btnLeaveEdit;
    int _switchToRow;
    BOOL isEdit;
    int selectRow;
}

- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)doSwitchAccount;
- (void)accountSwitch;
- (void)doAddAccount;
- (void)doDelAccount;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)clearUnread;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)accountDelete;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)editAccounts:(id)arg1;
- (void)returnAccount:(id)arg1;
- (void)registerAccount;
- (void)addAccount;
- (void)leaveEditMode;
- (void)enterEditMode;
- (void)updateBarButtonItems;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

