/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "AFHTTPRequestOperation.h"

@class UIImage;

@interface AFImageRequestOperation : AFHTTPRequestOperation
{
    UIImage *_responseImage;
    float _imageScale;
}

+ (BOOL)canProcessRequest:(id)arg1;
+ (id)acceptableContentTypes;
+ (id)imageRequestOperationWithRequest:(id)arg1 imageProcessingBlock:(id)arg2 cacheName:(void)arg3 success:(id)arg4 failure:(id)arg5;
+ (id)imageRequestOperationWithRequest:(id)arg1 success:(id)arg2;
@property(nonatomic) float imageScale; // @synthesize imageScale=_imageScale;
@property(retain, nonatomic) UIImage *responseImage; // @synthesize responseImage=_responseImage;
- (void)setCompletionBlockWithSuccess:(id)arg1 failure:(void)arg2;
- (void)dealloc;
- (id)initWithRequest:(id)arg1;

@end

