/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "AFHTTPRequestOperation.h"

@class NSError;

@interface AFPropertyListRequestOperation : AFHTTPRequestOperation
{
    id _responsePropertyList;
    unsigned int _propertyListReadOptions;
    unsigned int _propertyListFormat;
    NSError *_propertyListError;
}

+ (BOOL)canProcessRequest:(id)arg1;
+ (id)acceptableContentTypes;
+ (id)propertyListRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(void)arg3;
@property(retain, nonatomic) NSError *propertyListError; // @synthesize propertyListError=_propertyListError;
@property(nonatomic) unsigned int propertyListFormat; // @synthesize propertyListFormat=_propertyListFormat;
@property(nonatomic) unsigned int propertyListReadOptions; // @synthesize propertyListReadOptions=_propertyListReadOptions;
@property(retain, nonatomic) id responsePropertyList; // @synthesize responsePropertyList=_responsePropertyList;
- (void)setCompletionBlockWithSuccess:(id)arg1 failure:(void)arg2;
- (id)error;
- (void)dealloc;
- (id)initWithRequest:(id)arg1;

@end

