/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ASICacheDelegate <NSObject>
- (void)clearCachedResponsesForStoragePolicy:(int)arg1;
- (id)pathToStoreCachedResponseDataForRequest:(id)arg1;
- (id)pathToStoreCachedResponseHeadersForRequest:(id)arg1;
- (id)pathToCachedResponseHeadersForURL:(id)arg1;
- (id)pathToCachedResponseDataForURL:(id)arg1;
- (id)cachedResponseDataForURL:(id)arg1;
- (id)cachedResponseHeadersForURL:(id)arg1;
- (void)removeCachedDataForURL:(id)arg1;
- (void)storeResponseForRequest:(id)arg1 maxAge:(double)arg2;
- (BOOL)isCachedDataCurrentForRequest:(id)arg1;
- (void)removeCachedDataForRequest:(id)arg1;
- (BOOL)canUseCachedDataForRequest:(id)arg1;
- (void)updateExpiryForRequest:(id)arg1 maxAge:(double)arg2;
- (id)expiryDateForRequest:(id)arg1 maxAge:(double)arg2;
- (int)defaultCachePolicy;
@end

