/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "CKImagePickerControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class UIImage, UIImageView, UIScrollView;

@interface BackgroundSettings : WBViewController <UIActionSheetDelegate, CKImagePickerControllerDelegate, UINavigationControllerDelegate, UIScrollViewDelegate>
{
    int _activeButtonIndex;
    UIImageView *imgSign;
    UIScrollView *_imgScrollView;
    UIImage *previewImage;
}

- (void)dealloc;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2 metadata:(id)arg3;
- (void)photoLibraryButtonPressed:(id)arg1;
- (void)cameraButtonPressed:(id)arg1;
- (void)thumbnailImageButtonPressed:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)initBackgroundsView;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

