/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CLLocation, NSMutableDictionary;

@interface CKImageMetadata : NSObject
{
    NSMutableDictionary *metadata;
}

- (id)EXIFRepresentation;
- (void)setImageOrientation:(unsigned int)arg1;
- (id)metadataByReplacingImageOrientation:(unsigned int)arg1;
@property(retain, nonatomic) CLLocation *location;
- (void)dealloc;
- (id)initWithMetadata:(id)arg1;

@end

