/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIImageView.h"

@class UIButton;

@interface CommentBarView : UIImageView
{
    UIButton *topicButton;
    UIButton *atButton;
    UIButton *faceButton;
    BOOL isOrientation;
}

@property(retain, nonatomic) UIButton *faceButton; // @synthesize faceButton;
@property(retain, nonatomic) UIButton *atButton; // @synthesize atButton;
@property(retain, nonatomic) UIButton *topicButton; // @synthesize topicButton;
- (void)dealloc;
- (void)changeFramePortrait:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

