/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@interface CXMLNode : NSObject <NSCopying>
{
    struct _xmlNode *_node;
}

- (id)nodesForXPath:(id)arg1 error:(id *)arg2;
- (id)XMLStringWithOptions:(unsigned int)arg1;
- (id)_XMLStringWithOptions:(unsigned int)arg1 appendingToString:(id)arg2;
- (id)XMLString;
- (id)description;
- (id)URI;
- (id)prefix;
- (id)localName;
- (id)nextSibling;
- (id)previousSibling;
- (id)childAtIndex:(unsigned int)arg1;
- (id)children;
- (unsigned int)childCount;
- (id)parent;
- (id)rootDocument;
- (unsigned int)level;
- (unsigned int)index;
- (id)stringValue;
- (id)name;
- (int)kind;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;

@end

