/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CXMLNode.h"

@interface CXMLNode (CXMLNode_CreationExtensions)
+ (id)processingInstructionWithName:(id)arg1 stringValue:(id)arg2;
+ (id)namespaceWithName:(id)arg1 stringValue:(id)arg2;
+ (id)elementWithName:(id)arg1 stringValue:(id)arg2;
+ (id)elementWithName:(id)arg1 URI:(id)arg2;
+ (id)elementWithName:(id)arg1;
+ (id)documentWithRootElement:(id)arg1;
+ (id)document;
- (void)setStringValue:(id)arg1;
@end

