/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBStatusTableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class MGTwitterEngine;

@interface DirectMessagesController : WBStatusTableViewController <UIActionSheetDelegate>
{
    MGTwitterEngine *_twitter;
    int _pagenum;
    BOOL _firstLoad;
    int _recordsCount;
    int listType;
    BOOL isLogin;
    BOOL isWelcome;
    int selectCellIndex;
}

@property(nonatomic) BOOL isWelcome; // @synthesize isWelcome;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)didPressAvatarOfUser:(id)arg1 inCell:(id)arg2;
- (void)didPressPhotoOfStatus:(id)arg1 inCell:(id)arg2;
- (void)loadMoreWeibos;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)finishLoadingNewData;
- (void)startViewController;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)reloadAll;
- (void)loadMessagesStaringAtPage:(int)arg1 count:(int)arg2;
- (void)accountChanged:(id)arg1;
- (void)dealloc;
- (void)RegisterSuccessAfter:(id)arg1;
- (void)viewDidUnload;
- (void)backToHomeAction:(id)arg1;
- (void)viewDidLoad;
- (void)updateTitle;
- (id)initWithRequestType:(int)arg1;
- (void)register;

@end

