/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CATransition, DXAd, DXAdHLoader, DXAdHStatisticsData, DXAdHWebViewClient, DXAdInfo, DXAdRequest, DXAdSize, NSCondition, NSOperationQueue, NSString;

@interface DXAdAbstractControl : NSObject
{
    int enforceShowCloseButton;
    DXAd *ad;
    DXAdRequest *adRequest;
    int orientation;
    DXAdSize *adSize;
    NSString *posId;
    DXAdInfo *adInfo;
    BOOL isReceiveAdSuccess;
    DXAdHLoader *loader;
    DXAdHWebViewClient *adShowWebView;
    float refreshInterval;
    DXAdHStatisticsData *statisticsData;
    NSOperationQueue *threadQueue;
    NSCondition *threadLock;
    CATransition *adAni;
    BOOL isCanClosed;
}

@property BOOL isCanClosed; // @synthesize isCanClosed;
@property(retain) CATransition *adAni; // @synthesize adAni;
@property(retain) NSCondition *threadLock; // @synthesize threadLock;
@property(retain) NSOperationQueue *threadQueue; // @synthesize threadQueue;
@property(retain) DXAdHStatisticsData *statisticsData; // @synthesize statisticsData;
@property float refreshInterval; // @synthesize refreshInterval;
@property BOOL isReceiveAdSuccess; // @synthesize isReceiveAdSuccess;
@property(retain) DXAdHWebViewClient *adShowWebView; // @synthesize adShowWebView;
@property(retain) DXAdHLoader *loader; // @synthesize loader;
@property(retain) DXAdInfo *adInfo; // @synthesize adInfo;
@property(retain) NSString *posId; // @synthesize posId;
@property(retain) DXAdSize *adSize; // @synthesize adSize;
@property int orientation; // @synthesize orientation;
@property(retain) DXAdRequest *adRequest; // @synthesize adRequest;
@property DXAd *ad; // @synthesize ad;
@property int enforceShowCloseButton; // @synthesize enforceShowCloseButton;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)animationDidStart:(id)arg1;
- (id)adTransition:(float)arg1 type:(int)arg2 subType:(int)arg3;
- (void)setAdFromDefaultCenter:(id)arg1;
- (id)buildRequestUrl:(id)arg1;
- (id)buildRequestParms;
- (void)enableCloseButton:(id)arg1 state:(int)arg2;
- (void)switchAdWithoutAnimation;
- (void)switchAd;
- (void)cancelLoadAd;
- (void)onLeaveApplication;
- (void)onPresentScreen;
- (void)onDismissScreen;
- (void)onAdFinished;
- (void)onReceiveAd;
- (void)onFailedToReceiveAd:(id)arg1;
- (void)refreshAd;
- (void)executeAdRequest:(id)arg1;
- (void)createAdWebView;
- (void)clickCloseButton;
- (void)close;
- (void)dealloc;
- (id)init;

@end

