/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface DXAdHStatisticsData : NSObject
{
    NSMutableArray *adClickTime;
    NSString *adRequestLoadContentTime;
    NSString *adRequestStartTime;
    NSMutableArray *viewAdTime;
    long long adRequestCount;
    NSString *adId;
    BOOL networkError;
    BOOL noFill;
    NSString *a;
}

@property(retain) NSString *a; // @synthesize a;
@property BOOL noFill; // @synthesize noFill;
@property BOOL networkError; // @synthesize networkError;
@property(retain) NSString *adId; // @synthesize adId;
@property(readonly) long long adRequestCount; // @synthesize adRequestCount;
@property(retain) NSMutableArray *viewAdTime; // @synthesize viewAdTime;
@property(retain) NSString *adRequestStartTime; // @synthesize adRequestStartTime;
@property(retain) NSString *adRequestLoadContentTime; // @synthesize adRequestLoadContentTime;
@property(retain) NSMutableArray *adClickTime; // @synthesize adClickTime;
- (void)viewAdEnd;
- (long long)adRequestLoadTime;
- (id)adClickTimes;
- (id)viewAdTimes;
- (long long)adClickCount;
- (void)adRequestLoad;
- (void)adRequestStart;
- (void)adClick;
- (void)initParm;
- (void)dealloc;
- (id)init;

@end

