/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DXAdAbstractControl.h"

@class NSMutableArray;

@interface DXAdControlWithNoCache : DXAdAbstractControl
{
    long long interstitialTimeout;
    BOOL isEnableRefresh;
    NSMutableArray *trackUrls;
    NSMutableArray *clickTrackingUrls;
}

@property(retain) NSMutableArray *clickTrackingUrls; // @synthesize clickTrackingUrls;
@property(retain) NSMutableArray *trackUrls; // @synthesize trackUrls;
@property BOOL isEnableRefresh; // @synthesize isEnableRefresh;
@property long long interstitialTimeout; // @synthesize interstitialTimeout;
- (void)onReceiveAd;
- (void)onFailedToReceiveAd:(id)arg1;
- (void)refreshAd;
- (BOOL)pingClickTrackingURLs;
- (void)pingTrackingURLs;
- (void)disableRefresh;
- (void)enableRefresh;
- (void)addClickTrackingUrl:(id)arg1;
- (void)addTrackUrl:(id)arg1;
- (void)initDefaultParm;
- (id)initWithCustom:(id)arg1 adSize:(id)arg2 posId:(id)arg3;
- (void)dealloc;

@end

