/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DXAdUtil : NSObject
{
}

+ (BOOL)checkHtml5File:(id)arg1;
+ (BOOL)isRetinaModel;
+ (id)macAddress;
+ (void)sendNilMsgFromNotificationCenter:(id)arg1;
+ (BOOL)isObjsNotNil:(int)arg1;
+ (BOOL)isFileCreateTimeMoreThen7Day:(id)arg1;
+ (int)getPartOfDay:(id)arg1;
+ (id)objectToJson:(id)arg1;
+ (id)jsonToObject:(id)arg1;
+ (BOOL)isAdSourceExist:(id)arg1;
+ (id)ErrorCode:(int)arg1;
+ (id)parentViewController:(id)arg1;
+ (void)closeChildViewController:(id)arg1;
+ (BOOL)isLocalFileUrl:(id)arg1;
+ (BOOL)isStandFormat:(id)arg1;
+ (BOOL)isHttp:(id)arg1;
+ (id)DateAddInterval:(id)arg1 intervalTime:(float)arg2;
+ (float)DateTimeInterval:(id)arg1 beforeDate:(id)arg2;
+ (id)urlParms:(id)arg1;
+ (id)urlDecode:(id)arg1;
+ (id)urlEncode:(id)arg1;
+ (void)createDirectory:(id)arg1;
+ (void)delCacheFile:(id)arg1;
+ (BOOL)isDirectoryExist:(id)arg1;
+ (BOOL)isFileExist:(id)arg1;
+ (void)initDownLoadDirectory;
+ (id)dxAdCacheDirectory;
+ (id)allFilesInDirectory:(id)arg1;
+ (void)delDirectory:(id)arg1;
+ (BOOL)unzipAdFile:(id)arg1 to:(id)arg2;
+ (void)delFile:(id)arg1;
+ (void)initDocumentPath:(id)arg1;
+ (id)jsonToAdInfo:(id)arg1;
+ (void)requestHeaderSetting:(id)arg1 requestInfo:(id)arg2;
+ (id)clientUserAgent;
+ (long long)currentTimeOfDayEnd;
+ (long long)currentTimeOfDayStart;
+ (long long)currentTimeMillis;
+ (id)stringToDate:(id)arg1;
+ (id)dateToString:(id)arg1;
+ (void)initAdSdkDB;
+ (void)adLogOut:(id)arg1 marked:(id)arg2 isDebugModel:(BOOL)arg3;
+ (id)md5WithUpperCase:(id)arg1;
+ (id)md5:(id)arg1;
+ (int)currMobileAccessInternetType;

@end

