/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DXAdTime : NSObject
{
    int start;
    int end;
    int allowDisplayCount;
    int allowClickCount;
    int currentDisplaycount;
    int currentClickCount;
    int visible;
}

@property int visible; // @synthesize visible;
@property int currentDisplaycount; // @synthesize currentDisplaycount;
@property int currentClickCount; // @synthesize currentClickCount;
@property int allowDisplayCount; // @synthesize allowDisplayCount;
@property int allowClickCount; // @synthesize allowClickCount;
@property int end; // @synthesize end;
@property int start; // @synthesize start;
- (id)init;

@end

