/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDate, NSString;

@interface DXAdInfo : NSObject
{
    NSString *posId;
    NSString *adid;
    int type;
    NSString *adword;
    NSString *adwordid;
    NSDate *begintime;
    NSDate *endtime;
    NSString *url;
    NSString *adurl;
    long long allowdisplaytime;
    long long allowdisplaynum;
    NSString *imageUrl;
    int adurltype;
    int sortnum;
    int allowdayclicknum;
    int showclosebuttontype;
    NSString *tokenId;
    int currentdisplaycount;
    int currentclickcount;
    int currentclosecount;
    int currenttimeoutcount;
    int visible;
    int tempinvisible;
    long long cacheTime;
    NSString *fileName;
    NSString *jsondate;
    NSString *imgextname;
    NSString *desc;
    int cid;
    NSArray *adtimes;
    int allownetwork;
    BOOL isFirstLoadSucc;
    NSString *weiboUserid;
    NSString *weiboId;
    int showAttention;
    int showForward;
    NSString *gsId;
    NSString *weiboContent;
    NSString *weiboTopic;
    int reactivate;
    int weiboType;
    NSString *downloadPackageName;
    NSString *downLoadSchems;
}

@property(retain) NSString *downloadPackageName; // @synthesize downloadPackageName;
@property(retain) NSString *downLoadSchems; // @synthesize downLoadSchems;
@property int weiboType; // @synthesize weiboType;
@property(retain) NSString *weiboTopic; // @synthesize weiboTopic;
@property(retain) NSString *weiboContent; // @synthesize weiboContent;
@property int reactivate; // @synthesize reactivate;
@property(retain) NSString *gsId; // @synthesize gsId;
@property int showAttention; // @synthesize showAttention;
@property int showForward; // @synthesize showForward;
@property(retain) NSString *weiboUserid; // @synthesize weiboUserid;
@property(retain) NSString *weiboId; // @synthesize weiboId;
@property BOOL isFirstLoadSucc; // @synthesize isFirstLoadSucc;
@property int allownetwork; // @synthesize allownetwork;
@property(retain) NSArray *adtimes; // @synthesize adtimes;
@property int tempinvisible; // @synthesize tempinvisible;
@property(retain) NSString *imgextname; // @synthesize imgextname;
@property(retain) NSString *fileName; // @synthesize fileName;
@property long long cacheTime; // @synthesize cacheTime;
@property int visible; // @synthesize visible;
@property int currenttimeoutcount; // @synthesize currenttimeoutcount;
@property int currentdisplaycount; // @synthesize currentdisplaycount;
@property int currentclosecount; // @synthesize currentclosecount;
@property int currentclickcount; // @synthesize currentclickcount;
@property(retain) NSString *tokenId; // @synthesize tokenId;
@property int allowdayclicknum; // @synthesize allowdayclicknum;
@property long long allowdisplaynum; // @synthesize allowdisplaynum;
@property int sortnum; // @synthesize sortnum;
@property(retain) NSString *jsondate; // @synthesize jsondate;
@property(retain) NSDate *begintime; // @synthesize begintime;
@property(retain) NSString *posId; // @synthesize posId;
@property int cid; // @synthesize cid;
@property int showclosebuttontype; // @synthesize showclosebuttontype;
@property(retain) NSString *imageUrl; // @synthesize imageUrl;
@property(retain) NSString *desc; // @synthesize desc;
@property int type; // @synthesize type;
@property long long allowdisplaytime; // @synthesize allowdisplaytime;
@property(retain) NSDate *endtime; // @synthesize endtime;
@property(retain) NSString *adword; // @synthesize adword;
@property(retain) NSString *adwordid; // @synthesize adwordid;
@property(retain) NSString *adurl; // @synthesize adurl;
@property int adurltype; // @synthesize adurltype;
@property(retain) NSString *url; // @synthesize url;
@property(retain) NSString *adid; // @synthesize adid;
- (id)toString;
- (void)dealloc;
- (id)getCurrentAdTime;
- (id)createAdTime;
- (id)init;

@end

