/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "ASIHTTPRequestDelegate-Protocol.h"

@interface DXAdHPingUrl : NSObject <ASIHTTPRequestDelegate>
{
}

- (void)postData:(id)arg1 data:(id)arg2;
- (void)ping:(id)arg1;

@end

