/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DXAdHAbstractBannerAd.h"

@class DXAdAbstractControl, DXAdSize, NSString, UIViewController;

@interface DXAdHWBBannerAd : DXAdHAbstractBannerAd
{
    DXAdAbstractControl *adControl;
    DXAdSize *adSize;
    NSString *posId;
    int refreshCacheInterval;
    UIViewController *viewControl;
}

+ (id)html5BannerAd:(id)arg1 adRequest:(id)arg2 adSize:(id)arg3 posId:(id)arg4 refreshCacheInterval:(int)arg5;
+ (id)html5BannerAd:(id)arg1 adSize:(id)arg2 posId:(id)arg3 refreshCacheInterval:(int)arg4;
@property UIViewController *viewControl; // @synthesize viewControl;
@property int refreshCacheInterval; // @synthesize refreshCacheInterval;
@property(retain) NSString *posId; // @synthesize posId;
@property(retain) DXAdSize *adSize; // @synthesize adSize;
@property(retain) DXAdAbstractControl *adControl; // @synthesize adControl;
- (void)resetAdTempVisible:(id)arg1;
- (void)refreshCache;
- (void)close;
- (void)removeFromSuper;
- (void)hideCloseButton;
- (void)showCloseButton;
- (void)stopLoading;
- (void)loadAd:(id)arg1;
- (BOOL)isReady;
- (void)dealloc;
- (id)initWithCustom:(id)arg1 adRequest:(id)arg2 adSize:(id)arg3 posId:(id)arg4 refreshCacheInterval:(int)arg5;
- (id)initWithCustom:(id)arg1 adSize:(id)arg2 posId:(id)arg3 refreshCacheInterval:(int)arg4;

@end

