/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DXAdAbstractControl, DXAdHActionAndParms, DXAdHViewController;

@interface DXAdHView : NSObject
{
    DXAdAbstractControl *adControl;
    DXAdHActionAndParms *actionParms;
    DXAdHViewController *viewControl;
}

+ (void)launchAdView:(id)arg1 actionParms:(id)arg2;
+ (id)getAdViewInstance;
+ (id)adViewInstanceWithCustom:(id)arg1 actionParms:(id)arg2;
@property(retain) DXAdHViewController *viewControl; // @synthesize viewControl;
@property(retain) DXAdHActionAndParms *actionParms; // @synthesize actionParms;
@property DXAdAbstractControl *adControl; // @synthesize adControl;
- (void)setAdControlFromDefaultCenter:(id)arg1;
- (void)onAdClosed:(id)arg1;
- (void)operatingWebApp:(id)arg1;
- (void)operatingIntent:(id)arg1;
- (void)onDistribution;
- (id)initWithCustom:(id)arg1 actionParms:(id)arg2;
- (void)dealloc;

@end

