/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIWebViewDelegate-Protocol.h"

@class UIWebView;

@interface DXAdGetUA : NSObject <UIWebViewDelegate>
{
    UIWebView *web;
}

@property UIWebView *web; // @synthesize web;
- (void)dealloc;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (id)init;

@end

