/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DXAdLog : NSObject
{
}

+ (void)enableLog:(BOOL)arg1;
+ (void)log:(id)arg1;
+ (void)error:(id)arg1;
+ (void)warning:(id)arg1;

@end

