/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DXAdHIAction-Protocol.h"

@interface DXAdHLogAction : NSObject <DXAdHIAction>
{
}

- (void)execute:(id)arg1 actionParms:(id)arg2 webview:(id)arg3;

@end

