/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DXAdAbstractControlWithCache.h"

#import "WBDXAdManagerDelegate-Protocol.h"

@class DXAdHWeiBoBrower, DXAdRefreshCache, NSString, NSTimer, SinaAdDB, WBDXAdManager;

@interface DXAdWBControlWithCache : DXAdAbstractControlWithCache <WBDXAdManagerDelegate>
{
    DXAdRefreshCache *adRefresh;
    SinaAdDB *mAdDB;
    BOOL isFirstRequest;
    BOOL lastVisibleAd;
    BOOL isClosedAd;
    BOOL isRefreshing;
    NSTimer *failRefreshTimer;
    WBDXAdManager *weibo;
    NSString *currAdid;
    NSString *currAdwordid;
    NSString *weiboUserId;
    DXAdHWeiBoBrower *wbBrower;
}

@property(retain, nonatomic) DXAdHWeiBoBrower *wbBrower; // @synthesize wbBrower;
@property(retain) NSString *weiboUserId; // @synthesize weiboUserId;
@property(retain) NSString *currAdwordid; // @synthesize currAdwordid;
@property(retain) NSString *currAdid; // @synthesize currAdid;
@property(retain) WBDXAdManager *weibo; // @synthesize weibo;
@property(retain) NSTimer *failRefreshTimer; // @synthesize failRefreshTimer;
@property BOOL isClosedAd; // @synthesize isClosedAd;
@property BOOL lastVisibleAd; // @synthesize lastVisibleAd;
@property BOOL isFirstRequest; // @synthesize isFirstRequest;
@property SinaAdDB *mAdDB; // @synthesize mAdDB;
@property(retain) DXAdRefreshCache *adRefresh; // @synthesize adRefresh;
- (void)adManager:(id)arg1 didFailToRepostStatusWithOriginalStatusID:(id)arg2 userID:(id)arg3 content:(id)arg4 error:(id)arg5;
- (void)adManager:(id)arg1 didRepostStatusWithOriginalStatusID:(id)arg2 userID:(id)arg3 content:(id)arg4;
- (void)adManager:(id)arg1 didFailToFollowUserID:(id)arg2 error:(id)arg3;
- (void)adManager:(id)arg1 didFollowUserID:(id)arg2;
- (void)setAdFromDefaultCenter:(id)arg1;
- (void)releaseWBBrower;
- (void)executeWeiboAction:(id)arg1 actionParms:(id)arg2;
- (void)resetAdTempVisible:(id)arg1;
- (void)notify;
- (void)wait;
- (void)refreshAd;
- (void)closeAdRefresh;
- (void)clickCloseButton;
- (void)switchAd;
- (void)onReceiveAd;
- (void)refreshAdCacheByFailReceiveOnMain;
- (void)onFailedToReceiveAd:(id)arg1;
- (void)refreshAdCacheOnMain:(id)arg1;
- (void)refreshAdCache;
- (void)saveDB:(id)arg1 add:(id)arg2;
- (void)setAdtempInvisible:(id)arg1 isVisiable:(int)arg2;
- (void)changeAdTempVisiable:(id)arg1 isVisible:(int)arg2;
- (void)recordTimeoutAd;
- (void)recordCloseAd;
- (void)recordClickAd;
- (void)clearCache;
- (void)closeByOperate;
- (void)closeAd;
- (void)clickAd;
- (void)recordPV;
- (id)buildAdUriForClickAd:(id)arg1 selectAd:(id)arg2;
- (id)buildPostParms:(id)arg1;
- (id)buildPostCacheData;
- (void)showMessageInStatusBarOnMain:(id)arg1;
- (void)showMessageInStatusBar:(id)arg1;
- (id)buildRequestParms;
- (void)close;
- (void)adControlSetRunning;
- (void)dealloc;
- (id)initWithCustom:(id)arg1 adRequest:(id)arg2 adSize:(id)arg3 posId:(id)arg4 refreshCacheInterval:(int)arg5;
- (id)initWithCustom:(id)arg1 adSize:(id)arg2 posId:(id)arg3 refreshCacheInterval:(int)arg4;

@end

