/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DXSQLHelp : NSObject
{
    struct sqlite3 *database;
}

- (id)Query:(id)arg1 parms:(id)arg2;
- (id)Query:(id)arg1;
- (BOOL)RunBatchSQL:(id)arg1;
- (BOOL)RunSQL:(id)arg1 parms:(id)arg2;
- (BOOL)RunSQL:(id)arg1;
- (void)Close;
- (BOOL)Open:(id)arg1;

@end

