/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewCell.h"

@class UIImageView, UILabel;

@interface GroupCell : WBTableViewCell
{
    UIImageView *img;
    UILabel *grouptext;
}

@property(retain, nonatomic) UIImageView *img; // @synthesize img;
- (void)dealloc;
- (void)updateCellContent:(id)arg1;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

