/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "WBSkinning-Protocol.h"

@class UIImageView, UILabel;

@interface GuidePopView : UIView <WBSkinning>
{
    UILabel *hintLabel;
    UIImageView *bgImage;
}

@property(retain, nonatomic) UIImageView *bgImage; // @synthesize bgImage;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)onHideHintEnd;
- (void)hideHint;
- (void)showHint:(id)arg1;
- (void)restartAnimate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)reloadUIElements;

@end

