/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WBSkinning-Protocol.h"

@class NSArray, UIActivityIndicatorView, UIButton, UIImageView, UITableView, WBFeedGroup;

@interface HomeGroupView : UIView <UITableViewDelegate, UITableViewDataSource, WBSkinning>
{
    UITableView *mTableView;
    UIImageView *imgCell;
    UIImageView *imgBack;
    UIActivityIndicatorView *_loadingAttIndic;
    WBFeedGroup *selectedGroup;
    UIImageView *separatorImageView;
    UIButton *editGroupsButton;
    NSArray *groupsSectionHeaders;
    NSArray *feedGroups;
    id <HomeGroupViewDelegate> delegate;
    int indexSel;
}

@property(readonly, nonatomic) WBFeedGroup *selectedGroup; // @synthesize selectedGroup;
@property(nonatomic) int indexSel; // @synthesize indexSel;
@property(nonatomic) id <HomeGroupViewDelegate> delegate; // @synthesize delegate;
@property(copy, nonatomic) NSArray *groupsSectionHeaders; // @synthesize groupsSectionHeaders;
@property(copy, nonatomic) NSArray *feedGroups; // @synthesize feedGroups;
- (void)editGroupsButtonPressed:(id)arg1;
- (void)reloadUIElements;
- (void)dealloc;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)reloadLoadView:(BOOL)arg1;
- (void)reSetTabFrame:(struct CGRect)arg1;
- (void)reloadTableView;
- (void)resetGroupsSectionHeaders:(id)arg1;
- (void)resetWithFeedGroups:(id)arg1 selectedGroup:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

