/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBStatusTableViewController.h"

#import "DXAdDelegate-Protocol.h"
#import "HomeGroupViewDelegate-Protocol.h"
#import "MyPhotoFadeViewDelegate-Protocol.h"
#import "SNPopoverWindowDismissDelegate-Protocol.h"
#import "StartWeiboDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "WBSkinning-Protocol.h"
#import "WBStatusTableViewCellDelegate-Protocol.h"
#import "WBTabBarControllerDelegate-Protocol.h"

@class DXAdHWBBannerAd, HomeGroupView, MGTwitterEngine, NSString, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIImageView, UILabel, WBHomeNewStatusHintBoard, WBStatusPostAdHintBoard, WBTimelineManager;

@interface HomeViewController : WBStatusTableViewController <WBSkinning, UIActionSheetDelegate, HomeGroupViewDelegate, StartWeiboDelegate, MyPhotoFadeViewDelegate, WBStatusTableViewCellDelegate, WBTabBarControllerDelegate, SNPopoverWindowDismissDelegate, DXAdDelegate>
{
    MGTwitterEngine *_twitter;
    BOOL isChangedAccount;
    BOOL isUnLoad;
    struct CGPoint offPoint;
    int languIndex;
    WBHomeNewStatusHintBoard *topHintBoard;
    HomeGroupView *groupView;
    UIButton *btnHead;
    UILabel *lblAtt;
    UIImageView *imgAtt;
    UIBarButtonItem *_reloadButton;
    UIBarButtonItem *_loadingButton;
    UIActivityIndicatorView *_loadingIndic;
    BOOL isViewVisiable;
    UIButton *refreshButton;
    UIButton *newMsgButton;
    UIButton *checkInButton;
    DXAdHWBBannerAd *adBanner;
    id viewDidAppearBlock;
    WBTimelineManager *timelineManager;
    NSString *refreshType;
    WBStatusPostAdHintBoard *bottomStatusPostAdHintBoard;
}

- (void)loadMore;
- (void)reload:(id)arg1;
- (void)refreshButtonDidPressed;
- (void)loadAllStatusFromLocal;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)handleLoadStatusResultWithError:(id)arg1 block:(id)arg2;
- (void)resetNavigationBarButtonItems;
- (void)reloadDataWithCurrentResultSet;
- (BOOL)remindFollowOfficalAccountIfNeeded;
- (void)getOfficialAccountInfomation;
- (void)followOfficialAccount;
- (void)didRemindedFollowOfficailAccount;
- (BOOL)hasRemindedFollowOfficailAccount;
- (void)getMyAccountInfomation;
- (void)onHideBanner:(id)arg1;
- (void)onLeaveApplication:(id)arg1;
- (void)onDismissScreen:(id)arg1;
- (void)onPresentScreen:(id)arg1;
- (void)onFailedToReceiveAd:(id)arg1 AdRequest:(id)arg2 ErrorCode:(int)arg3;
- (void)onReceiveAd:(id)arg1;
- (void)handleStatusSentOutNotification:(id)arg1;
- (void)bottomHintBoardPressed:(id)arg1;
- (void)shareApplication;
- (void)startLoadWeibo;
- (void)loginReceived:(id)arg1 forRequest:(id)arg2;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestFailed:(id)arg1;
- (void)requestSucceeded:(id)arg1;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)reviewInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)welcomeStart;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)checkIn;
- (void)newMessage;
- (void)refreshProfile;
- (void)accountChanged:(id)arg1;
- (void)accountChangedReturn:(id)arg1;
- (void)accountChangedFromWelcome:(id)arg1;
- (void)reloadTabBarItem;
- (void)tabBarControllerDidSelect:(id)arg1;
- (void)appLanguageDidChangeNotification:(id)arg1;
- (void)bubbleSkinBackgroundImageDidChangeNotification:(id)arg1;
- (void)currentSkinDidChangeNotification:(id)arg1;
- (void)setViewBackground;
- (void)reloadUIElements;
- (void)configPRLMWrapper;
- (void)viewDidLoad;
- (void)showAd;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)createRightItemView;
- (void)createLeftItemView;
- (void)createTitleView;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;
- (void)handleGroupsDidChangeNotification;
- (void)loadFeedGroups;
- (void)groupsViewDidPressEditGroupsButton:(id)arg1;
- (void)groupViewSeleted:(id)arg1;
- (void)btnHeadDown:(id)arg1;
- (void)resetGroupPickerTitle;
- (void)popoverDidDismiss:(id)arg1;
- (void)openGroupPicker;
- (void)resetGroupPickerWithFeedGroups:(id)arg1 selectedGroup:(id)arg2;
- (void)resetGroupPickerFrame;
- (void)updateStatusCount:(id)arg1;

@end

