/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewController.h"

@class MGTwitterEngine, NSMutableArray, UIActivityIndicatorView;

@interface HotTopicsListViewController : WBTableViewController
{
    MGTwitterEngine *_twitter;
    NSMutableArray *items;
    unsigned char _loading;
    BOOL isLogin;
    int pageNo;
    int _recordsCount;
    BOOL _lastMessage;
    UIActivityIndicatorView *indicator;
    BOOL isWelcome;
    int viewfrom;
    id <HotwordDelegate> delegate;
}

@property(nonatomic) int viewfrom; // @synthesize viewfrom;
@property(nonatomic) id <HotwordDelegate> delegate; // @synthesize delegate;
@property(nonatomic) BOOL isWelcome; // @synthesize isWelcome;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)hotWordsReceived:(id)arg1;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)loadMoreHotPeople;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)backToHomeAction:(id)arg1;
- (void)viewDidLoad;
- (id)init;

@end

