/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IPRGBCurveAdjustFilter.h"

@interface IPColorBalanceFilter : IPRGBCurveAdjustFilter
{
    int type;
    int cyanRed;
    int magentaGreen;
    int yellowBlue;
}

- (BOOL)shouldProcess;
- (void)generateRGBTable;
- (void)setType:(int)arg1 cyanRed:(int)arg2 magentaGreen:(int)arg3 yellowBlue:(int)arg4;
- (id)initWithImage:(id)arg1;

@end

