/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IPProcessor.h"

@interface IPMaxMinFilter : IPProcessor
{
    BOOL maximum;
    int radius;
}

@property(nonatomic) int radius; // @synthesize radius;
@property(nonatomic) BOOL maximum; // @synthesize maximum;
- (void)processImage:(id)arg1;
- (BOOL)shouldProcess;
- (id)initWithImages:(id)arg1;
- (id)initWithImage:(id)arg1;

@end

