/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString, UIImage;

@interface IPProcessor : NSObject
{
    NSString *name;
    id <IPProcessorDelegate> delegate;
    UIImage *inputImage;
    BOOL useMultipleInputs;
    NSMutableArray *inputImages;
    UIImage *outputImage;
}

@property(retain, nonatomic) UIImage *outputImage; // @synthesize outputImage;
@property(retain, nonatomic) NSMutableArray *inputImages; // @synthesize inputImages;
@property(retain, nonatomic) UIImage *inputImage; // @synthesize inputImage;
@property(nonatomic) id <IPProcessorDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void)processImages:(id)arg1;
- (void)processImage:(id)arg1;
- (BOOL)shouldProcess;
- (void)applyProcessorInBackground;
- (id)imageWithProcessorApplied;
- (void)dealloc;
- (id)initWithImages:(id)arg1;
- (id)initWithImage:(id)arg1;

@end

