/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "IPProcessor.h"

@interface IPSpatialFilter : IPProcessor
{
    int *kernel;
    int kernelWidth;
    int kernelHeight;
    int kernelFactor;
    BOOL separable;
}

@property(nonatomic) BOOL separable; // @synthesize separable;
- (void)processImage:(id)arg1;
- (BOOL)shouldProcess;
- (void)setKernel:(int *)arg1 width:(int)arg2 height:(int)arg3;
- (id)initWithImages:(id)arg1;
- (id)initWithImage:(id)arg1;

@end

