/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "TwitterConnectionProtocol-Protocol.h"

@class MGTwitterEngine, NSString;

@interface MGConnectionWrap : NSObject <TwitterConnectionProtocol>
{
    MGTwitterEngine *_twitter;
    NSString *mgTwitterConnectionID;
    id <MGConnectionDelegate> _delegate;
    BOOL canceled;
}

@property(retain, nonatomic) NSString *mgTwitterConnectionID; // @synthesize mgTwitterConnectionID;
- (void)cancelImage;
- (BOOL)canceled;
- (void)cancel;
- (void)dealloc;
- (id)initWithTwitter:(id)arg1 connection:(id)arg2 delegate:(id)arg3;

@end

