/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSURLConnection.h"

@class NSMutableData, NSString, NSURL, NSURLRequest;

@interface MGTwitterHTTPURLConnection : NSURLConnection
{
    NSMutableData *_data;
    int _requestType;
    int _responseType;
    NSString *_identifier;
    NSURL *_URL;
    NSURLRequest *__wb_request;
    id __wb_delegate;
    BOOL _retryHTTP;
}

- (id)retryHTTPConnection;
- (BOOL)isHTTPS;
- (BOOL)isRetryHTTP;
- (id)description;
- (int)responseType;
- (int)requestType;
- (id)URL;
- (id)data;
- (id)identifier;
- (void)setRetryHTTP;
- (void)resetIdentifier:(id)arg1;
- (void)appendData:(id)arg1;
- (void)resetDataLength;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 delegate:(id)arg2 requestType:(int)arg3 responseType:(int)arg4;

@end

