/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIWindow.h"

@class NSMutableArray, UIActivityIndicatorView, UIImage, UIImageView, UILabel, UIView;

@interface MTStatusBarOverlay : UIWindow
{
    UIView *backgroundView_;
    UIImageView *statusBarBackgroundImageView_;
    UILabel *statusLabel1_;
    UILabel *statusLabel2_;
    UILabel *hiddenStatusLabel_;
    UIImageView *progressView_;
    double progress_;
    UIActivityIndicatorView *activityIndicator_;
    UILabel *finishedLabel_;
    BOOL hidesActivity_;
    UIImage *defaultStatusBarImage_;
    UIImage *defaultStatusBarImageShrinked_;
    int animation_;
    struct CGRect smallFrame_;
    struct CGRect oldBackgroundViewFrame_;
    BOOL hideInProgress_;
    BOOL active_;
    NSMutableArray *messageQueue_;
    BOOL canRemoveImmediateMessagesFromQueue_;
    id <MTStatusBarOverlayDelegate> delegate_;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)threadSafeSharedOverlay;
+ (id)threadSafeSharedInstance;
+ (id)sharedOverlay;
+ (id)sharedInstance;
@property(nonatomic) id <MTStatusBarOverlayDelegate> delegate; // @synthesize delegate=delegate_;
@property(nonatomic) BOOL canRemoveImmediateMessagesFromQueue; // @synthesize canRemoveImmediateMessagesFromQueue=canRemoveImmediateMessagesFromQueue_;
@property(retain, nonatomic) NSMutableArray *messageQueue; // @synthesize messageQueue=messageQueue_;
@property(getter=isActive) BOOL active; // @synthesize active=active_;
@property(getter=isHideInProgress) BOOL hideInProgress; // @synthesize hideInProgress=hideInProgress_;
@property(nonatomic) int animation; // @synthesize animation=animation_;
@property(nonatomic) struct CGRect oldBackgroundViewFrame; // @synthesize oldBackgroundViewFrame=oldBackgroundViewFrame_;
@property(nonatomic) struct CGRect smallFrame; // @synthesize smallFrame=smallFrame_;
@property(retain, nonatomic) UIImage *defaultStatusBarImageShrinked; // @synthesize defaultStatusBarImageShrinked=defaultStatusBarImageShrinked_;
@property(retain, nonatomic) UIImage *defaultStatusBarImage; // @synthesize defaultStatusBarImage=defaultStatusBarImage_;
@property(nonatomic) BOOL hidesActivity; // @synthesize hidesActivity=hidesActivity_;
@property(retain, nonatomic) UILabel *finishedLabel; // @synthesize finishedLabel=finishedLabel_;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=activityIndicator_;
@property(retain, nonatomic) UIImageView *progressView; // @synthesize progressView=progressView_;
@property(nonatomic) double progress; // @synthesize progress=progress_;
@property(nonatomic) UILabel *hiddenStatusLabel; // @synthesize hiddenStatusLabel=hiddenStatusLabel_;
@property(retain, nonatomic) UILabel *statusLabel2; // @synthesize statusLabel2=statusLabel2_;
@property(retain, nonatomic) UILabel *statusLabel1; // @synthesize statusLabel1=statusLabel1_;
@property(retain, nonatomic) UIImageView *statusBarBackgroundImageView; // @synthesize statusBarBackgroundImageView=statusBarBackgroundImageView_;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=backgroundView_;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)animation3DidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)animation2DidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
@property(readonly, nonatomic, getter=isNotVisible) BOOL notVisible;
- (void)setHidden:(BOOL)arg1 useAlpha:(BOOL)arg2;
- (void)setHiddenUsingAlpha:(BOOL)arg1;
- (void)updateProgressViewSizeForLabel:(id)arg1;
- (void)callDelegateWithNewMessage:(id)arg1;
- (void)updateUIForMessageType:(int)arg1 duration:(double)arg2;
- (void)setColorSchemeForStatusBarStyle:(int)arg1 messageType:(int)arg2;
- (void)setStatusBarBackgroundForStyle:(int)arg1;
@property(readonly, nonatomic) UILabel *visibleStatusLabel;
- (void)setShrinked:(BOOL)arg1 animated:(BOOL)arg2;
@property(readonly, nonatomic, getter=isShrinked) BOOL shrinked;
- (void)rotateToStatusBarFrame:(id)arg1;
- (void)didChangeStatusBarFrame:(id)arg1;
- (void)show;
- (void)hide;
- (void)showNextMessage;
- (void)postImmediateMessage:(id)arg1 type:(int)arg2 duration:(double)arg3 animated:(BOOL)arg4;
- (void)postMessage:(id)arg1 type:(int)arg2 duration:(double)arg3 animated:(BOOL)arg4 immediate:(BOOL)arg5;
- (void)postImmediateErrorMessage:(id)arg1 duration:(double)arg2 animated:(BOOL)arg3;
- (void)postErrorMessage:(id)arg1 duration:(double)arg2 animated:(BOOL)arg3;
- (void)postErrorMessage:(id)arg1 duration:(double)arg2;
- (void)postErrorMessage:(id)arg1;
- (void)postImmediateFinishMessage:(id)arg1 duration:(double)arg2 animated:(BOOL)arg3;
- (void)postFinishMessage:(id)arg1 duration:(double)arg2 animated:(BOOL)arg3;
- (void)postFinishMessage:(id)arg1 duration:(double)arg2;
- (void)postImmediateMessage:(id)arg1 duration:(double)arg2 animated:(BOOL)arg3;
- (void)postImmediateMessage:(id)arg1 animated:(BOOL)arg2;
- (void)postMessage:(id)arg1 duration:(double)arg2 animated:(BOOL)arg3;
- (void)postMessage:(id)arg1 duration:(double)arg2;
- (void)postMessage:(id)arg1 animated:(BOOL)arg2;
- (void)postMessage:(id)arg1;
- (void)restoreState;
- (void)saveStateSynchronized:(BOOL)arg1;
- (void)saveState;
- (void)addSubviewToBackgroundView:(id)arg1 atIndex:(int)arg2;
- (void)addSubviewToBackgroundView:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)supportBlock;

@end

