/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewController.h"

#import "MyBlackUserCellDelegate-Protocol.h"
#import "PRLMTableViewWrapperDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class MGTwitterEngine, NSMutableArray, NSString, UIActionSheet, UIActivityIndicatorView, UIBarButtonItem, WBPRLMTableViewWrapper;

@interface MyBlackUserViewController : WBTableViewController <UIActionSheetDelegate, PRLMTableViewWrapperDelegate, MyBlackUserCellDelegate>
{
    MGTwitterEngine *_twitter;
    NSMutableArray *blockedUsers;
    int _pageNo;
    int _count;
    UIActivityIndicatorView *_loadingIndic;
    UIBarButtonItem *_loadingButton;
    UIBarButtonItem *_reloadButton;
    int rowNum;
    UIActionSheet *progressSheet;
    WBPRLMTableViewWrapper *prlmWrapper;
    NSString *_errorDesc;
}

@property(retain, nonatomic) UIActionSheet *progressSheet; // @synthesize progressSheet;
- (void)unblockButtonDidPressInCell:(id)arg1;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)dealloc;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)fansReceived:(id)arg1 forRequest:(id)arg2;
- (void)finishLoadingNewData;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)closeAfterHaveResult;
- (void)ActionSheetHintCancel;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)init;

@end

