/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewController.h"

#import "ProfileEditViewControllerDelegate-Protocol.h"

@class NSDictionary, WBUserProfileHeaderView;

@interface MyProfileViewController : WBTableViewController <ProfileEditViewControllerDelegate>
{
    WBUserProfileHeaderView *_profileHeaderView;
    NSDictionary *_userInfo;
    int userInfoSectionIndex;
    int userDataSectionIndex;
    int userMiscellaneousSectionIndex;
    int enterpriseSectionIndex;
    int haoAndMedalsSectionIndex;
    int sectionsCount;
}

- (void)profileEditModifyAfter:(BOOL)arg1;
- (void)showUserInfo;
- (void)downloadUserInfo;
- (void)loadUserInfoFromLocal;
- (BOOL)isUserInfoAvailable;
- (void)trendsButtonPressed:(id)arg1;
- (void)followersButtonPressed:(id)arg1;
- (void)statusesButtonPressed:(id)arg1;
- (void)followingsButtonPressed:(id)arg1;
- (void)membershipButtonPressed:(id)arg1;
- (void)editProfileButtonPressed:(id)arg1;
- (void)refreshButtonPressed:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)unloadSubviews;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)changeProfileTabBarBadge:(id)arg1;
- (void)statusesCountChanged:(id)arg1;
- (void)accountChanged:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithoutToolbar;
- (id)initWithStyle:(int)arg1;
- (void)reloadUserData;

@end

