/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (TTCategory)
- (id)objectWithClass:(Class)arg1;
- (id)objectWithValue:(id)arg1 forKey:(id)arg2;
- (void)perform:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3 withObject:(id)arg4;
- (void)perform:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (void)perform:(SEL)arg1 withObject:(id)arg2;
- (void)perform:(SEL)arg1;
@end

