/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (KeyValue)
- (id)UIColorForKey:(id)arg1;
- (id)UIColorForKey:(id)arg1 defaultValue:(id)arg2;
- (id)imageForKey:(id)arg1;
- (id)imageForKey:(id)arg1 defaultValue:(id)arg2;
- (unsigned int)unsignedIntegerForKey:(id)arg1;
- (unsigned int)unsignedIntegerForKey:(id)arg1 defaultValue:(unsigned int)arg2;
- (int)integerForKey:(id)arg1;
- (int)integerForKey:(id)arg1 defaultValue:(int)arg2;
- (unsigned long long)unsignedLongLongForKey:(id)arg1;
- (unsigned long long)unsignedLongLongForKey:(id)arg1 defaultValue:(unsigned long long)arg2;
- (unsigned int)unsignedIntForKey:(id)arg1;
- (unsigned int)unsignedIntForKey:(id)arg1 defaultValue:(unsigned int)arg2;
- (int)intForKey:(id)arg1;
- (int)intForKey:(id)arg1 defaultValue:(int)arg2;
- (BOOL)boolForKey:(id)arg1;
- (BOOL)boolForKey:(id)arg1 defaultValue:(BOOL)arg2;
- (struct CGRect)rectForKey:(id)arg1;
- (struct CGRect)rectForKey:(id)arg1 defaultValue:(struct CGRect)arg2;
- (struct CGSize)sizeForKey:(id)arg1;
- (struct CGSize)sizeForKey:(id)arg1 defaultValue:(struct CGSize)arg2;
- (struct CGPoint)pointForKey:(id)arg1;
- (struct CGPoint)pointForKey:(id)arg1 defaultValue:(struct CGPoint)arg2;
- (double)doubleForKey:(id)arg1;
- (double)doubleForKey:(id)arg1 defaultValue:(double)arg2;
- (float)floatForKey:(id)arg1;
- (float)floatForKey:(id)arg1 defaultValue:(float)arg2;
- (id)stringArrayForKey:(id)arg1;
- (id)stringArrayForKey:(id)arg1 defaultValue:(id)arg2;
- (id)stringForKey:(id)arg1;
- (id)stringForKey:(id)arg1 defaultValue:(id)arg2;
- (id)numberForKey:(id)arg1;
- (id)numberForKey:(id)arg1 defaultValue:(id)arg2;
@end

