/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSFileManager.h"

@interface NSFileManager (Utilities)
+ (id)pathsForBundleDocumentsMatchingExtension:(id)arg1;
+ (id)pathsForDocumentsMatchingExtension:(id)arg1;
+ (id)pathsForItemsMatchingExtension:(id)arg1 inFolder:(id)arg2;
+ (id)filesInFolder:(id)arg1;
+ (id)pathForBundleDocumentNamed:(id)arg1;
+ (id)pathForDocumentNamed:(id)arg1;
+ (id)pathForItemNamed:(id)arg1 inFolder:(id)arg2;
@end

