/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (TTCategory)
- (void)openURLFromButton:(id)arg1;
- (void)openURL;
- (id)objectValue;
- (id)stringByAddingQueryDictionary:(id)arg1;
- (id)queryDictionaryUsingEncoding:(unsigned int)arg1;
- (id)stringByRemovingHTMLTags;
- (BOOL)isEmptyOrWhitespace;
- (BOOL)isWhitespace;
@end

