/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (SimpleMatching)
+ (BOOL)isEmptyString:(id)arg1;
- (BOOL)hasLeadingWhitespace;
- (BOOL)containsString:(id)arg1;
- (BOOL)containsString:(id)arg1 options:(unsigned int)arg2;
- (BOOL)containsCharacterInSet:(id)arg1;
@end

