/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (JSONKitDeserializing)
- (id)mutableObjectFromJSONStringWithParseOptions:(unsigned int)arg1 error:(id *)arg2;
- (id)mutableObjectFromJSONStringWithParseOptions:(unsigned int)arg1;
- (id)mutableObjectFromJSONString;
- (id)objectFromJSONStringWithParseOptions:(unsigned int)arg1 error:(id *)arg2;
- (id)objectFromJSONStringWithParseOptions:(unsigned int)arg1;
- (id)objectFromJSONString;
@end

