/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@protocol PRLMTableViewWrapperDelegate <UITableViewDelegate, UITableViewDataSource>

@optional
- (BOOL)hasNoDataInWrapper:(id)arg1;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
@end

