/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PRLMHeaderFooterView.h"

@class CALayer, UIImageView, UILabel;

@interface PRLMHeaderView : PRLMHeaderFooterView
{
    UILabel *lastUpdateTimeLabel;
    CALayer *arrowImageLayer;
    UIImageView *backgroundImageView;
}

- (void)setPrlmState:(int)arg1;
- (void)didFinishPullRefreshAnimation;
- (void)layoutSubviews;
- (id)localizedPromptText;
- (id)localizedLastUpdateTimeText:(id)arg1;
- (id)arrowImage;
- (float)headerHeight;
- (void)setBackgroundImage:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

