/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSString, PRLMFooterView, PRLMHeaderView, PRLMTableView;

@interface PRLMTableViewWrapper : NSObject
{
    NSString *wrapperID;
    PRLMTableView *_tableView;
    PRLMHeaderView *pullRefreshHeaderView;
    PRLMFooterView *loadMoreFooterView;
    BOOL initialized;
    BOOL supportPullRefresh;
    BOOL supportLoadMore;
    BOOL enablePullRefresh;
    BOOL enableLoadMore;
    BOOL loading;
    BOOL _animatingToHideHeader;
    BOOL usingTableFooterView;
    float baseVerticalContentInset;
    NSDate *lastPullRefreshTime;
    NSDate *lastLoadMoreTime;
    id <UITableViewDelegate><UITableViewDataSource><UIScrollViewDelegate><PRLMTableViewWrapperDelegate> delegate;
}

@property(nonatomic) id <UITableViewDelegate><UITableViewDataSource><UIScrollViewDelegate><PRLMTableViewWrapperDelegate> delegate; // @synthesize delegate;
@property(readonly, nonatomic) NSDate *lastLoadMoreTime; // @synthesize lastLoadMoreTime;
@property(readonly, nonatomic) NSDate *lastPullRefreshTime; // @synthesize lastPullRefreshTime;
@property(nonatomic) float baseVerticalContentInset; // @synthesize baseVerticalContentInset;
@property(readonly, nonatomic) BOOL usingTableFooterView; // @synthesize usingTableFooterView;
@property(nonatomic) BOOL loading; // @synthesize loading;
@property(nonatomic) BOOL enableLoadMore; // @synthesize enableLoadMore;
@property(nonatomic) BOOL enablePullRefresh; // @synthesize enablePullRefresh;
@property(nonatomic) BOOL supportLoadMore; // @synthesize supportLoadMore;
@property(nonatomic) BOOL supportPullRefresh; // @synthesize supportPullRefresh;
@property(retain, nonatomic) PRLMFooterView *loadMoreFooterView; // @synthesize loadMoreFooterView;
@property(retain, nonatomic) PRLMHeaderView *pullRefreshHeaderView; // @synthesize pullRefreshHeaderView;
@property(retain, nonatomic) PRLMTableView *tableView; // @synthesize tableView=_tableView;
- (void)playSoundForAction:(int)arg1;
- (id)soundFileOfAction:(int)arg1;
- (void)didFinishPullRefreshingOrLoadingMore;
- (void)loadingMoreDidFinished;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)pullRefreshingDidFinished;
- (void)scrollViewDidEndDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)loadMoreFooterViewPressed:(id)arg1;
- (void)triggerLoadMore;
- (void)triggerPullRefresh;
- (void)triggerPullRefresh:(BOOL)arg1;
- (void)initialize;
- (id)footerView;
- (id)headerView;
- (void)dealloc;
- (id)initWithTableView:(id)arg1;
- (id)initWithTableView:(id)arg1 wrapperID:(id)arg2;
- (id)init;
- (void)restoreLastPullRefreshTime;
- (void)refreshLastPullRefreshTime;
- (void)setWrapperID:(id)arg1;
- (BOOL)isLoadingMore;
- (BOOL)isPullRefreshing;
- (void)_setEnablePullRefresh:(BOOL)arg1;
- (void)_setEnableLoadMore:(BOOL)arg1;

@end

