/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIControl.h"

@class PRLMTableViewWrapper, UIActivityIndicatorView, UILabel;

@interface PRLMHeaderFooterView : UIControl
{
    PRLMTableViewWrapper *owner;
    int _prlmState;
    UIActivityIndicatorView *activityIndicatorView;
    UILabel *promptLabel;
}

@property(nonatomic) int prlmState; // @synthesize prlmState=_prlmState;
@property(nonatomic) PRLMTableViewWrapper *owner; // @synthesize owner;
- (void)dealloc;
- (id)localizedPromptText;
- (id)initWithFrame:(struct CGRect)arg1;

@end

