/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "FriendsFansVCDelegate-Protocol.h"
#import "FriendsFollowsVCDelegate-Protocol.h"
#import "MyPhotoFadeViewDelegate-Protocol.h"
#import "ProfileTabViewControllerDelegate-Protocol.h"
#import "UITabBarDelegate-Protocol.h"
#import "UserTopicListViewControllerDelegate-Protocol.h"

@class FriendsFansVC, FriendsFollowsVC, MGTwitterEngine, MyFavMblogListVC, NSArray, NSString, UIAccelerometer, UIActivityIndicatorView, UITabBar, UIViewController, UIViewController<SubTabDelegate>, UserInfoMBlogViewController, UserTopicListViewController, WBTabBar, WBTabBarItem;

@interface ProfileTabViewController : WBViewController <UITabBarDelegate, FriendsFollowsVCDelegate, FriendsFansVCDelegate, UserTopicListViewControllerDelegate, ProfileTabViewControllerDelegate, MyPhotoFadeViewDelegate>
{
    int viewType;
    FriendsFollowsVC *vcFollows;
    FriendsFansVC *vcFans;
    UserInfoMBlogViewController *vcMblogs;
    UserTopicListViewController *vcTopic;
    MyFavMblogListVC *vcFav;
    WBTabBar *tabBar;
    WBTabBarItem *tabItemFavs;
    WBTabBarItem *tabItemProfile;
    WBTabBarItem *tabItemMblogs;
    WBTabBarItem *tabItemFollows;
    WBTabBarItem *tabItemFans;
    WBTabBarItem *tabItemTopics;
    NSArray *myTabItems;
    NSString *uid;
    int itemsCount;
    BOOL _loading;
    BOOL _relogined;
    int newFansAmount;
    BOOL showNeedRefresh;
    unsigned char _isMyself;
    BOOL isNotIdle;
    UIAccelerometer *shakeAccelerometer;
    NSString *nickname;
    UIViewController<SubTabDelegate> *_activeTabVC;
    UIViewController *parentVC;
    MGTwitterEngine *_twitter;
    UIActivityIndicatorView *_loadingIndic;
}

@property(retain, nonatomic) NSArray *myTabItems; // @synthesize myTabItems;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname;
@property(retain, nonatomic) UIViewController *parentVC; // @synthesize parentVC;
@property(retain, nonatomic) MyFavMblogListVC *vcFav; // @synthesize vcFav;
@property(retain, nonatomic) UserTopicListViewController *vcTopic; // @synthesize vcTopic;
@property(retain, nonatomic) UserInfoMBlogViewController *vcMblogs; // @synthesize vcMblogs;
@property(retain, nonatomic) FriendsFansVC *vcFans; // @synthesize vcFans;
@property(retain, nonatomic) FriendsFollowsVC *vcFollows; // @synthesize vcFollows;
@property(retain, nonatomic) UITabBar *tabBar; // @synthesize tabBar;
@property(retain, nonatomic) NSString *uid; // @synthesize uid;
@property(nonatomic) int viewType; // @synthesize viewType;
- (void)showStatusContent:(id)arg1 isFavor:(BOOL)arg2;
- (void)showPhotoWithUrl:(id)arg1;
- (void)showUserProfile:(id)arg1;
- (void)viewOriginalImageButtonPressedWithImageURL:(id)arg1;
- (void)fromUserTopicListViewController:(id)arg1 topId:(id)arg2;
- (void)fromFriendsFanVC:(id)arg1;
- (void)fromFriendsFollowsVC:(id)arg1;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)statusesReceived:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)onUserReLogin:(id)arg1;
- (void)resetNewCount:(id)arg1;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (id)initWithViewType:(int)arg1 withUid:(id)arg2 withNickname:(id)arg3;
- (id)initWithViewType:(int)arg1 withUid:(id)arg2;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)updateStatusCount:(id)arg1;
- (void)onReloadButtonTouched;
- (void)tabBar:(id)arg1 didSelectItem:(id)arg2;
- (void)initTabBar:(unsigned char)arg1 withViewType:(int)arg2;
- (void)viewDidLoad;
- (void)initLoadingIndicator;
- (void)initGoHomeButton;
- (void)onGoHomeClick:(id)arg1;
- (void)claimUidAvailable:(id)arg1;
- (void)initSubTabControllers:(id)arg1;
- (void)activeTabOfViewType:(int)arg1;
- (void)forceReload;

@end

