/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewCell.h"

@class UIImageView, UILabel;

@interface ProfileEditViewCell : WBTableViewCell
{
    UILabel *lblName;
    UIImageView *imgIcon;
    UILabel *lblContent;
}

@property(retain, nonatomic) UILabel *lblContent; // @synthesize lblContent;
@property(retain, nonatomic) UIImageView *imgIcon; // @synthesize imgIcon;
@property(retain, nonatomic) UILabel *lblName; // @synthesize lblName;
- (void)dealloc;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setProfileText:(id)arg1 path:(int)arg2;
- (void)setProfileImage:(id)arg1;
- (void)setIconImage:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

