/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewController.h"

#import "ActionSheetHintDelegate-Protocol.h"
#import "IPImageEditorViewControllerDelegate-Protocol.h"
#import "ProfileEditParticularDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ActionSheetHint, MGTwitterEngine, NSArray, NSMutableDictionary, NSString, UIButton, UIImage, UIPickerView, UIToolbar, UIView;

@interface ProfileEditViewController : WBTableViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, ProfileEditParticularDelegate, UIPickerViewDelegate, UIPickerViewDataSource, ActionSheetHintDelegate, IPImageEditorViewControllerDelegate>
{
    NSMutableDictionary *userInfo;
    UIImage *pickImage;
    int modifyRow;
    BOOL isEdit;
    NSString *strNick;
    NSString *strIntro;
    id <ProfileEditViewControllerDelegate> delegate;
    ActionSheetHint *progressSheet;
    BOOL isCamera;
    UIPickerView *m_picker;
    UIToolbar *toolBar;
    int groupRow;
    int cityRow;
    MGTwitterEngine *_twitter;
    NSArray *arrProvince;
    UIButton *btnMale;
    UIButton *btnFemale;
    UIView *viewHead;
    BOOL isFemale;
    NSString *strProvince;
    NSString *strCity;
}

@property(retain, nonatomic) ActionSheetHint *progressSheet; // @synthesize progressSheet;
@property(retain, nonatomic) NSString *strCity; // @synthesize strCity;
@property(retain, nonatomic) NSString *strProvince; // @synthesize strProvince;
@property(retain, nonatomic) NSArray *arrProvince; // @synthesize arrProvince;
@property(retain, nonatomic) UIImage *pickImage; // @synthesize pickImage;
@property(nonatomic) id <ProfileEditViewControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSMutableDictionary *userInfo; // @synthesize userInfo;
- (void)setUserArray;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)closeAfterHaveResult;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)ActionSheetHintCancel;
- (void)saveButtonprofile:(id)arg1;
- (void)cannelButtonprofile:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (float)heightOfMessage:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)imageEditorDidDeleteImage:(id)arg1;
- (void)imageEditorDidCancelReEditing:(id)arg1;
- (void)imageEditorDidCancelEditing:(id)arg1;
- (void)imageEditor:(id)arg1 didFinishEditingImage:(id)arg2 effectName:(id)arg3;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (id)scaleToSize:(struct CGSize)arg1 img:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)profileModifyAfter:(id)arg1;
- (void)getDataPlace;
- (void)getDataM_pickerDown:(id)arg1;
- (void)getDataM_pickerCancelDown:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (id)pickerView:(id)arg1 titleForRow:(int)arg2 forComponent:(int)arg3;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (void)btnFemaleSetGender:(id)arg1;
- (void)btnMaleSetGender:(id)arg1;
- (void)createTabHeadView;
- (void)viewDidLoad;

@end

