/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WBSkinning-Protocol.h"
#import "WeiboItemBoardViewDelegate-Protocol.h"

@class MGTwitterEngine, NSArray, NSMutableArray, NSTimer, PageControl, UISearchDisplayController, UITableView, WBSearchBar, WeiboItemBoardView;

@interface SearchCatalogViewController : WBViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate, UIScrollViewDelegate, WeiboItemBoardViewDelegate, WBSkinning>
{
    MGTwitterEngine *_twitter;
    WBSearchBar *_searchBar;
    UITableView *_tableView;
    NSMutableArray *_arrHisSearchPerson;
    NSMutableArray *_arrHisSearchWeibo;
    NSArray *filteredArray;
    BOOL isSearch;
    BOOL _isSearchWeibo;
    UISearchDisplayController *searchDisplayController;
    WeiboItemBoardView *weiboBoard;
    PageControl *mPage_Num;
    NSMutableArray *searchResult;
    BOOL isSucc;
    int languIndex;
    NSTimer *loaderQueueTimer;
    NSMutableArray *unReadResult;
    int UnreadCount;
    int touchNum;
}

@property(retain, nonatomic) NSTimer *loaderQueueTimer; // @synthesize loaderQueueTimer;
@property(retain) NSArray *filteredArray; // @synthesize filteredArray;
- (void)dealloc;
- (void)viewDidUnload;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewSetNoHidden;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (BOOL)searchBarShouldBeginEditing:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)hotWordsReceived:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 selectedScopeButtonIndexDidChange:(int)arg2;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)itemDidTouchDown:(int)arg1;
- (void)GetSearchUnreadReceived:(id)arg1;
- (void)unreadMessageCountDidUpdateNotification:(id)arg1;
- (void)searchGridReceived:(id)arg1;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)searchDisplayController:(id)arg1 willShowSearchResultsTableView:(id)arg2;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchScope:(int)arg2;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)filterHistoryWordsWithKeyword:(id)arg1;
- (void)accountChanged:(id)arg1;
- (void)viewDidLoad;
- (void)currentSkinDidChangeNotification:(id)arg1;
- (void)searchHistoryDidRemoveNotification:(id)arg1;
- (void)reloadUIElements;
- (void)reloadTabBarItem;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

