/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "ActionSheetHintDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class ActionSheetHint, MGTwitterEngine, NSString, UIBarButtonItem, UITextView;

@interface SendReportWeibo : WBViewController <UITextViewDelegate, UIActionSheetDelegate, ActionSheetHintDelegate>
{
    UITextView *textEdit;
    UIBarButtonItem *cancelButton;
    UIBarButtonItem *sendButton;
    NSString *weiboId;
    BOOL isEdit;
    MGTwitterEngine *_twitter;
    ActionSheetHint *progressSheet;
    NSString *srcuid;
    int keyboardHeight;
}

@property(retain, nonatomic) NSString *srcuid; // @synthesize srcuid;
@property(retain, nonatomic) ActionSheetHint *progressSheet; // @synthesize progressSheet;
@property(retain, nonatomic) NSString *weiboId; // @synthesize weiboId;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)setViewsLocationBasedOnInterfaceOrientation:(int)arg1;
- (void)keyboardChangedNotification:(id)arg1;
- (void)keyboardWillHideNotification:(id)arg1;
- (void)keyboardDidShowNotification:(id)arg1;
- (void)keyboardWillShowNotification:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)dismissProgressSheetIfExist;
- (void)closeAfterHaveResult;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)ActionSheetHintCancel;
- (void)sendButtonPress:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)cannelButtonPress:(id)arg1;
- (void)viewDidLoad;

@end

