/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class AFHTTPRequestOperation, NSDictionary, NSMutableURLRequest, SNNetworkBaseClient, SNNetworkClient;

@interface SNHTTPRequestOperationWrapper : NSObject
{
    id successBlock;
    id failureBlock;
    id uploadProgressBlock;
    id downloadProgressBlock;
    SNNetworkClient *client;
    AFHTTPRequestOperation *operation;
    NSMutableURLRequest *request;
    NSDictionary *settings;
}

@property(copy, nonatomic) id downloadProgressBlock; // @synthesize downloadProgressBlock;
@property(copy, nonatomic) id uploadProgressBlock; // @synthesize uploadProgressBlock;
@property(retain, nonatomic) NSDictionary *settings; // @synthesize settings;
@property(readonly, nonatomic) NSMutableURLRequest *request; // @synthesize request;
@property(retain, nonatomic) AFHTTPRequestOperation *operation; // @synthesize operation;
@property(nonatomic) SNNetworkBaseClient *client; // @synthesize client;
- (void)callbackFailureBlockInFailureQueueWithError:(id)arg1;
- (void)callbackSuccessBlockInSuccessQueueWithResponseObject:(id)arg1;
- (void)callbackFailureBlockWithError:(id)arg1;
- (void)callbackSuccessBlockWithResponseObject:(id)arg1;
- (id)responseString;
- (id)responseData;
- (id)response;
- (void)loadImageFileWithPath:(id)arg1 encodeAsImage:(BOOL)arg2;
- (void)loadImageWithPath:(id)arg1 encodeAsImage:(BOOL)arg2;
- (void)resetRequest:(id)arg1;
- (id)requestWithResendProperties:(id)arg1;
- (void)resendWithProperties:(id)arg1;
- (void)cancel;
- (void)dealloc;
- (id)initWithWithRequest:(id)arg1 successBlock:(id)arg2 failureBlock:(void)arg3;

@end

