/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SNNetworkClient.h"

@interface SNNetworkClient (XML)
- (id)uploadPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 constructingBodyWithBlock:(id)arg4 successBlock:(void)arg5 failureBlock:(id)arg6;
- (id)deletePath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 successBlock:(id)arg4 failureBlock:(void)arg5;
- (id)putPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 successBlock:(id)arg4 failureBlock:(void)arg5;
- (id)postPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 successBlock:(id)arg4 failureBlock:(void)arg5;
- (id)getPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 successBlock:(id)arg4 failureBlock:(void)arg5;
- (id)enqueueOperationWithRequest:(id)arg1 arrayQueryPaths:(id)arg2 successBlock:(id)arg3 failureBlock:(void)arg4;
@end

