/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SNNetworkClient.h"

@interface SNNetworkClient (CompletionBlock)
- (id)uploadPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 constructingBodyWithBlock:(id)arg4 completionBlock:(void)arg5;
- (id)deletePath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 completionBlock:(id)arg4;
- (id)putPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 completionBlock:(id)arg4;
- (id)postPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 completionBlock:(id)arg4;
- (id)getPath:(id)arg1 parameters:(id)arg2 arrayQueryPaths:(id)arg3 completionBlock:(id)arg4;
- (id)loadImageWithPath:(id)arg1 encodeAsImage:(BOOL)arg2 completionBlock:(id)arg3;
- (id)uploadPath:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(id)arg3 completionBlock:(void)arg4;
- (id)deletePath:(id)arg1 parameters:(id)arg2 completionBlock:(id)arg3;
- (id)putPath:(id)arg1 parameters:(id)arg2 completionBlock:(id)arg3;
- (id)postPath:(id)arg1 parameters:(id)arg2 completionBlock:(id)arg3;
- (id)getPath:(id)arg1 parameters:(id)arg2 completionBlock:(id)arg3;
@end

