/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SNNetworkBaseClient.h"

@interface SNNetworkClient : SNNetworkBaseClient
{
}

- (void)resendOperationWithWrapper:(id)arg1 properties:(id)arg2;
- (id)uploadPath:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(id)arg3 successBlock:(void)arg4 failureBlock:(id)arg5;
- (id)deletePath:(id)arg1 parameters:(id)arg2 successBlock:(id)arg3 failureBlock:(void)arg4;
- (id)putPath:(id)arg1 parameters:(id)arg2 successBlock:(id)arg3 failureBlock:(void)arg4;
- (id)postPath:(id)arg1 parameters:(id)arg2 successBlock:(id)arg3 failureBlock:(void)arg4;
- (id)getPath:(id)arg1 parameters:(id)arg2 successBlock:(id)arg3 failureBlock:(void)arg4;

@end

