/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIWindow.h"

@class UIControl, UIView;

@interface SNPopoverWindow : UIWindow
{
    UIView *_contentView;
    UIControl *_backgrounView;
    id <SNPopoverWindowDelegate> delegate;
    id userInfo;
    id <SNPopoverWindowDismissDelegate> dismissDelegate;
}

+ (id)sharedWindow;
+ (void)initialize;
@property(nonatomic) id <SNPopoverWindowDelegate> delegate; // @synthesize delegate;
- (void)backgroundViewPressed:(id)arg1;
- (void)didDismiss;
- (void)dismiss;
- (void)presentContentView:(id)arg1 fromRect:(struct CGRect)arg2 inView:(id)arg3;
- (void)presentContentView:(id)arg1 fromRect:(struct CGRect)arg2 inView:(id)arg3 userInfo:(id)arg4 dismissDelegate:(id)arg5;
- (void)presentContentView:(id)arg1 inRect:(struct CGRect)arg2;
- (void)presentContentView:(id)arg1 inRect:(struct CGRect)arg2 userInfo:(id)arg3 dismissDelegate:(id)arg4;
- (void)presentContentView:(id)arg1 fromView:(id)arg2;
- (void)presentContentView:(id)arg1 fromView:(id)arg2 userInfo:(id)arg3 dismissDelegate:(id)arg4;
- (void)_presentContentViewInRect:(struct CGRect)arg1;
- (struct CGRect)popoverRectOfSize:(struct CGSize)arg1 baseRect:(struct CGRect)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

