/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "AFHTTPRequestOperation.h"

#import "SNConfiguableRequestOperation-Protocol.h"

@class NSArray, NSError;

@interface SNXMLRequestOperation : AFHTTPRequestOperation <SNConfiguableRequestOperation>
{
    NSError *_XMLError;
    NSArray *_arrayQueryPaths;
    id _responseXML;
}

+ (BOOL)canProcessRequest:(id)arg1;
+ (id)defaultAcceptablePathExtensions;
+ (id)defaultAcceptableContentTypes;
@property(retain, nonatomic) NSError *XMLError; // @synthesize XMLError=_XMLError;
@property(retain, nonatomic) id responseXML; // @synthesize responseXML=_responseXML;
- (void)setCompletionBlockWithSuccess:(id)arg1 failure:(void)arg2;
- (id)error;
- (BOOL)validateXMLStructureAfterParse:(id)arg1;
- (BOOL)validateXMLStructureBeforeParse:(id)arg1;
- (id)parseXMLWithElement:(struct _TBXMLElement *)arg1 path:(id)arg2;
- (void)dealloc;
- (void)configWithSettings:(id)arg1;

@end

