/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewController.h"

#import "AppSettingViewControllerDelegate-Protocol.h"
#import "WBAppUpgradeManagerDelegate-Protocol.h"
#import "WBSkinning-Protocol.h"
#import "WBTaskQueueDelegate-Protocol.h"

@class MGTwitterEngine, NSArray, WBAppUpgradeManager;

@interface TabBarMoreItem : WBTableViewController <AppSettingViewControllerDelegate, WBTaskQueueDelegate, WBSkinning, WBAppUpgradeManagerDelegate>
{
    MGTwitterEngine *_twitter;
    WBAppUpgradeManager *upgradeManager;
    NSArray *sections;
    int draftCount;
}

@property(retain, nonatomic) NSArray *sections; // @synthesize sections;
- (void)setDateOfOfficalAccountLatestStatus:(id)arg1;
- (id)dateOfOfficalAccountLatestStatus;
- (void)setOfficalAccountHasNewStatus:(BOOL)arg1;
- (BOOL)officalAccountHasNewStatus;
- (void)checkVersion;
- (void)handleAppVersionAvailabelNotification;
- (void)appUpgradeManager:(id)arg1 didFailToCheckVersionWithError:(id)arg2;
- (void)appUpgradeManager:(id)arg1 didFinishCheckVersionWithResult:(id)arg2 hasNewVersion:(BOOL)arg3;
- (void)taskQueueDidUpdateTasks:(id)arg1;
- (void)taskQueueDidReload:(id)arg1;
- (void)taskQueueDidRemoveTask:(id)arg1;
- (void)taskQueueDidAddTask:(id)arg1;
- (void)updateDraftCount;
- (void)dealloc;
- (void)dismissWithClickedButtonIndex:(int)arg1 animated:(BOOL)arg2;
- (void)clearUnread;
- (void)accountDelete;
- (void)doAccountDelete;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)reSetMuLanguageSet;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)settingsButtonPressed:(id)arg1;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)viewDidLoad;
- (void)currentSkinDidChangeNotification:(id)arg1;
- (void)reloadUIElements;
- (void)reloadTabBarItem;
- (void)resetBadgeValue;
- (void)loadLatestStatusOfIphoneOfficial;
- (void)reloadSections;
- (id)initWithStyle:(int)arg1;

@end

