/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "TBXML.h"

@interface TBXML (StaticFunctions)
+ (void)iterateAttributesOfElement:(struct _TBXMLElement *)arg1 withBlock:(id)arg2;
+ (void)iterateElementsForQuery:(id)arg1 fromElement:(struct _TBXMLElement *)arg2 withBlock:(id)arg3;
+ (struct _TBXMLElement *)nextSiblingNamed:(id)arg1 searchFromElement:(struct _TBXMLElement *)arg2 error:(id *)arg3;
+ (struct _TBXMLElement *)nextSiblingNamed:(id)arg1 searchFromElement:(struct _TBXMLElement *)arg2;
+ (struct _TBXMLElement *)childElementNamed:(id)arg1 parentElement:(struct _TBXMLElement *)arg2 error:(id *)arg3;
+ (struct _TBXMLElement *)childElementNamed:(id)arg1 parentElement:(struct _TBXMLElement *)arg2;
+ (id)valueOfAttributeNamed:(id)arg1 forElement:(struct _TBXMLElement *)arg2 error:(id *)arg3;
+ (id)valueOfAttributeNamed:(id)arg1 forElement:(struct _TBXMLElement *)arg2;
+ (id)textForElement:(struct _TBXMLElement *)arg1 error:(id *)arg2;
+ (id)textForElement:(struct _TBXMLElement *)arg1;
+ (id)attributeValue:(struct _TBXMLAttribute *)arg1 error:(id *)arg2;
+ (id)attributeValue:(struct _TBXMLAttribute *)arg1;
+ (id)attributeName:(struct _TBXMLAttribute *)arg1 error:(id *)arg2;
+ (id)attributeName:(struct _TBXMLAttribute *)arg1;
+ (id)elementName:(struct _TBXMLElement *)arg1 error:(id *)arg2;
+ (id)elementName:(struct _TBXMLElement *)arg1;
@end

