/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSXMLParserDelegate-Protocol.h"

@class NSMutableArray;

@interface TTMarkupStripper : NSObject <NSXMLParserDelegate>
{
    NSMutableArray *_strings;
}

- (id)parse:(id)arg1;
- (id)parser:(id)arg1 resolveExternalEntityName:(id)arg2 systemID:(id)arg3;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)dealloc;
- (id)init;

@end

