/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString, NSTimer;

@interface TTURLRequestQueue : NSObject
{
    NSMutableDictionary *_loaders;
    NSMutableArray *_loaderQueue;
    NSTimer *_loaderQueueTimer;
    int _totalLoading;
    unsigned int _maxContentLength;
    NSString *_userAgent;
    float _imageCompressionQuality;
    BOOL _suspended;
}

+ (void)setMainQueue:(id)arg1;
+ (id)mainQueue;
@property(nonatomic) float imageCompressionQuality; // @synthesize imageCompressionQuality=_imageCompressionQuality;
@property(nonatomic) BOOL suspended; // @synthesize suspended=_suspended;
@property(copy, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(nonatomic) unsigned int maxContentLength; // @synthesize maxContentLength=_maxContentLength;
- (id)createNSURLRequest:(id)arg1 URL:(id)arg2;
- (void)cancelAllRequests;
- (void)cancelRequestsWithDelegate:(id)arg1;
- (void)cancelRequest:(id)arg1;
- (BOOL)sendRequest:(id)arg1;
- (void)loaderDidCancel:(id)arg1 wasLoading:(BOOL)arg2;
- (void)loader:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)loader:(id)arg1 didLoadResponse:(id)arg2 data:(id)arg3;
- (void)removeLoader:(id)arg1;
- (void)loadNextInQueue;
- (void)loadNextInQueueDelayed;
- (void)executeLoader:(id)arg1;
- (BOOL)loadRequestFromCache:(id)arg1;
- (BOOL)loadFromCache:(id)arg1 cacheKey:(id)arg2 expires:(double)arg3 fromDisk:(BOOL)arg4 data:(id *)arg5 error:(id *)arg6 timestamp:(id *)arg7;
- (id)loadFromDocuments:(id)arg1 error:(id *)arg2;
- (id)loadFromBundle:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)init;

@end

