/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "TTURLPattern.h"

@class NSString;

@interface TTURLNavigatorPattern : TTURLPattern
{
    Class _targetClass;
    id _targetObject;
    int _navigationMode;
    NSString *_parentURL;
    int _transition;
    int _argumentCount;
}

@property(nonatomic) int argumentCount; // @synthesize argumentCount=_argumentCount;
@property(nonatomic) int transition; // @synthesize transition=_transition;
@property(copy, nonatomic) NSString *parentURL; // @synthesize parentURL=_parentURL;
@property(readonly, nonatomic) int navigationMode; // @synthesize navigationMode=_navigationMode;
@property(nonatomic) id targetObject; // @synthesize targetObject=_targetObject;
@property(nonatomic) Class targetClass; // @synthesize targetClass=_targetClass;
- (id)createObjectFromURL:(id)arg1 query:(id)arg2;
- (id)invoke:(id)arg1 withURL:(id)arg2 query:(id)arg3;
- (BOOL)matchURL:(id)arg1;
- (void)compile;
@property(readonly, nonatomic) BOOL isFragment;
@property(readonly, nonatomic) BOOL isUniversal;
- (Class)classForInvocation;
- (void)dealloc;
- (id)init;
- (id)initWithTarget:(id)arg1 mode:(int)arg2;
- (id)initWithTarget:(id)arg1;
- (void)setArgumentsFromURL:(id)arg1 forInvocation:(id)arg2 query:(id)arg3;
- (BOOL)setArgument:(id)arg1 pattern:(id)arg2 forInvocation:(id)arg3;
- (void)analyzeProperties;
- (void)analyzeMethod;
- (void)analyzeArgument:(id)arg1 method:(struct objc_method *)arg2 argNames:(id)arg3;
- (void)deduceSelector;
- (int)compareSpecificity:(id)arg1;
- (BOOL)callsInstanceMethod;
- (BOOL)instantiatesClass;

@end

