/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIImage.h"

@interface UIImage (Draw)
- (void)drawInRect:(struct CGRect)arg1 contentMode:(int)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 withContentMode:(int)arg2;
@end

