/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIImage.h"

@interface UIImage (RoundedCorner)
- (void)addRoundedRectToPath:(struct CGRect)arg1 context:(struct CGContext *)arg2 ovalWidth:(float)arg3 ovalHeight:(float)arg4;
- (id)roundedCornerImage:(int)arg1 borderSize:(int)arg2;
@end

