/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

@interface UIViewController (Helper)
- (BOOL)replaceButtonItem:(id)arg1 toButtonItem:(id)arg2 animated:(BOOL)arg3;
- (BOOL)replaceButtonItem:(id)arg1 toButtonItem:(id)arg2;
@end

