/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@interface UIView (UIView_cubicAnimation)
- (void)cubeTransitionSubViewIn:(id)arg1 SubViewOut:(id)arg2 direction:(BOOL)arg3 withDelegate:(id)arg4 withDelegate:(id)arg5;
- (void)cubeTransitionSubViewIn:(id)arg1 SubViewOut:(id)arg2 direction:(BOOL)arg3 animationDuration:(double)arg4 withDelegate:(id)arg5 withDelegate:(id)arg6;
- (id)cubicAnimationTopToCenterwithDelegate:(id)arg1 withDuration:(double)arg2 radius:(float)arg3;
- (id)cubicAnimationCenterToBottomwithDelegate:(id)arg1 withDuration:(double)arg2 radius:(float)arg3;
@end

