/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "ABUnknownPersonViewControllerDelegate-Protocol.h"
#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WBContactEngineDelegate-Protocol.h"
#import "WBImageBarDelegate-Protocol.h"

@class MGTwitterEngine, NSArray, NSString, UIActionSheet, UITableView, WBContactEngine, WBImageBar, WBToolbarButtonItem, WBUser, WBUserProfileHeaderView;

@interface UserInformationTabViewController : WBViewController <UIActionSheetDelegate, UITableViewDelegate, UITableViewDataSource, ABUnknownPersonViewControllerDelegate, WBContactEngineDelegate, WBImageBarDelegate, MFMessageComposeViewControllerDelegate>
{
    WBUser *user;
    WBUserProfileHeaderView *profileHeaderView;
    MGTwitterEngine *_twitter;
    NSString *uid;
    NSArray *myTabItems;
    NSString *nickName;
    UITableView *myTableView;
    UIActionSheet *progressSheet;
    BOOL isReady;
    int function_id;
    WBToolbarButtonItem *messageButtonItem;
    WBToolbarButtonItem *editGroupsButtonItem;
    BOOL isBlackAdd;
    id <UserInformationTabViewControllerDelegate> delegate;
    WBContactEngine *contactEngine;
    WBImageBar *phoneAccessoryImageBar;
    int remarkSectionIndex;
    int userInfoSectionIndex;
    int userDataSectionIndex;
    int phoneSectionIndex;
    int enterpriseSectionIndex;
    int haoAndMedalsSectionIndex;
    int sectionsCount;
}

@property(nonatomic) id <UserInformationTabViewControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName;
@property(retain, nonatomic) UIActionSheet *progressSheet; // @synthesize progressSheet;
@property(retain, nonatomic) NSString *uid; // @synthesize uid;
- (void)updateUI;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)trendsButtonPressed:(id)arg1;
- (void)statusesButtonPressed:(id)arg1;
- (void)followingsButtonPressed:(id)arg1;
- (void)followersButtonPressed:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)imageBar:(id)arg1 didClickItem:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)heightOfMessage:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)contactEngine:(id)arg1 didFailToRemoveFollower:(id)arg2 error:(id)arg3;
- (void)contactEngine:(id)arg1 didRemoveFollower:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)closeAfterHaveResult;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)statusesReceived:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (id)initColorBarItemWithAction:(SEL)arg1 title:(id)arg2 image:(id)arg3 highLightImage:(id)arg4;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)contactInfoAction:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)blackUserAddAction:(id)arg1;
- (void)sendPrivateMailAction:(id)arg1;
- (void)refresh:(id)arg1;
- (void)initTabToolbar:(BOOL)arg1;
- (void)ActionSheetHintCancel;
- (void)AtHimAction:(id)arg1;
- (void)disPlayBigIcon;
- (void)membershipButtonPressed:(id)arg1;
- (void)relationshipButtonPressed:(id)arg1;
- (void)initHeaderView;
- (void)onGoHomeClick:(id)arg1;
- (void)initTabGoHomeButton;
- (void)forceGetReloadData;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)reloadUserData;

@end

