/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBUser.h"

@class NSString;

@interface WBAccount : WBUser
{
    NSString *username;
    NSString *password;
    NSString *gsid;
    NSString *s;
    NSString *sid;
    NSString *oauthToken;
    NSString *oauthTokenSecret;
    NSString *oauth2Token;
    double oauth2TokenRemindIn;
    double oauth2TokenExpiresIn;
    unsigned int pushStartHour;
    unsigned int pushStopHour;
    unsigned int pushType;
    double unreadRemindInterval;
    unsigned int unreadRemindType;
}

@property(nonatomic) unsigned int unreadRemindType; // @synthesize unreadRemindType;
@property(nonatomic) double unreadRemindInterval; // @synthesize unreadRemindInterval;
@property(nonatomic) unsigned int pushType; // @synthesize pushType;
@property(nonatomic) unsigned int pushStopHour; // @synthesize pushStopHour;
@property(nonatomic) unsigned int pushStartHour; // @synthesize pushStartHour;
@property(nonatomic) double oauth2TokenExpiresIn; // @synthesize oauth2TokenExpiresIn;
@property(nonatomic) double oauth2TokenRemindIn; // @synthesize oauth2TokenRemindIn;
@property(retain, nonatomic) NSString *oauth2Token; // @synthesize oauth2Token;
@property(retain, nonatomic) NSString *oauthTokenSecret; // @synthesize oauthTokenSecret;
@property(retain, nonatomic) NSString *oauthToken; // @synthesize oauthToken;
@property(retain, nonatomic) NSString *sid; // @synthesize sid;
@property(retain, nonatomic) NSString *s; // @synthesize s;
@property(retain, nonatomic) NSString *gsid; // @synthesize gsid;
@property(retain, nonatomic) NSString *password; // @synthesize password;
@property(retain, nonatomic) NSString *username; // @synthesize username;
- (void)loadExtraInfo;
- (void)loadAuthInfo;
- (void)storeAuthInfo:(id)arg1;
- (void)loadPushAndUnreadRemindSettings;
- (BOOL)updateWithJSONDictionary:(id)arg1;
- (void)dealloc;

@end

