/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MGTwitterEngine, NSArray, NSMutableSet, NSTimer, WBNetworkV3Client;

@interface WBAdManager : NSObject
{
    NSArray *_cachedAds;
    MGTwitterEngine *engine;
    NSMutableSet *delegates;
    NSTimer *presentAdTimer;
    NSTimer *loadServerAdTimer;
    WBNetworkV3Client *loadAdClient;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
+ (id)sharedManager;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
- (void)willEnterForeground;
- (void)didEnterBackground;
- (void)currentSkinDidChangeNotification:(id)arg1;
- (void)accountSignedOut;
- (void)accountChangedReturn:(id)arg1;
- (void)accountChanged:(id)arg1;
- (void)clickAdModelViewAndSendRequestWithParams:(id)arg1;
- (void)clearHomeViewPullRefreshAdModel;
- (id)getAdModelFromCache;
- (void)loadHomePullRefreshHeaderViewAdPhoto:(id)arg1;
- (id)getAdCommonParamsDictionary;
- (void)loadHomeViewPullRefreshAdModel;
- (void)loadAdModelImmediately:(id)arg1 completionHandler:(id)arg2;
- (void)loadServerAd;
- (void)didGetServerAds:(id)arg1;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)presentAdInDelegate:(id)arg1;
- (void)scheduleLoadingServerAd;
- (void)closeAd:(id)arg1;
- (void)closeAd:(id)arg1 inDelegate:(id)arg2;
- (void)presentAds;
- (void)presentAds:(id)arg1 inDelegates:(id)arg2;
- (id)cachedAds;

@end

