/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBModelObject.h"

@class NSDate, NSString, UIColor;

@interface WBAdModel : WBModelObject
{
    NSString *adID;
    NSString *title;
    NSString *content;
    NSString *link;
    NSString *linkParams;
    NSString *iconURL;
    NSString *photoURL;
    int displayTime;
    NSDate *startDate;
    NSDate *endDate;
    BOOL showsCloseButton;
    BOOL shouldHideWhenClick;
    unsigned int category;
    NSString *downloadURL;
    NSString *backgroundURL;
    NSString *clickURL;
    NSString *pulldownTitle;
    NSString *pulloffTitle;
    NSString *loadingTitle;
    UIColor *textColor;
}

+ (id)objectsWithHomeviewPullRefreshAdJSONArray:(id)arg1;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor;
@property(retain, nonatomic) NSString *loadingTitle; // @synthesize loadingTitle;
@property(retain, nonatomic) NSString *pulloffTitle; // @synthesize pulloffTitle;
@property(retain, nonatomic) NSString *pulldownTitle; // @synthesize pulldownTitle;
@property(retain, nonatomic) NSString *clickURL; // @synthesize clickURL;
@property(retain, nonatomic) NSString *backgroundURL; // @synthesize backgroundURL;
@property(retain, nonatomic) NSString *downloadURL; // @synthesize downloadURL;
@property(nonatomic) unsigned int category; // @synthesize category;
@property(nonatomic) BOOL shouldHideWhenClick; // @synthesize shouldHideWhenClick;
@property(nonatomic) BOOL showsCloseButton; // @synthesize showsCloseButton;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate;
@property(nonatomic) int displayTime; // @synthesize displayTime;
@property(retain, nonatomic) NSString *photoURL; // @synthesize photoURL;
@property(retain, nonatomic) NSString *iconURL; // @synthesize iconURL;
@property(retain, nonatomic) NSString *linkParams; // @synthesize linkParams;
@property(retain, nonatomic) NSString *link; // @synthesize link;
@property(retain, nonatomic) NSString *content; // @synthesize content;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSString *adID; // @synthesize adID;
- (id)fullLink;
- (void)addParam:(id)arg1 withValue:(id)arg2 toLink:(id)arg3 hasParams:(char *)arg4;
- (id)user;
- (void)dealloc;
- (void)updateWithHomeviewPullRefreshAdJSONDictionary:(id)arg1;
- (id)initWithHomeviewPullRefreshAdJSONDictionary:(id)arg1;
- (BOOL)updateWithJSONDictionary:(id)arg1;
- (id)dateFromString:(id)arg1;

@end

