/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIControl.h"

#import "WBSkinning-Protocol.h"

@class UIButton, UIImageView, WBAdModel;

@interface WBAdView : UIControl <WBSkinning>
{
    WBAdModel *advertisement;
    UIImageView *imageView;
    UIButton *closeButton;
}

@property(readonly, nonatomic) UIButton *closeButton; // @synthesize closeButton;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(readonly, nonatomic) WBAdModel *advertisement; // @synthesize advertisement;
- (void)dealloc;
- (void)reloadUIElements;
- (id)initWithAdvertisement:(id)arg1 photo:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

