/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTask.h"

#import "WBTaskInSqlite-Protocol.h"

@class NSMutableDictionary, NSString;

@interface WBAPITaskBase : WBTask <WBTaskInSqlite>
{
    NSString *_uid;
    int _errCode;
    NSString *_errMsg;
    float _longitude;
    float _latitude;
    BOOL _locationHasOffset;
    NSString *_gsid;
    NSString *_act;
    NSString *_content;
    NSString *_tonick;
    NSMutableDictionary *_properties;
}

@property(readonly, nonatomic) NSMutableDictionary *properties; // @synthesize properties=_properties;
@property(nonatomic) BOOL locationHasOffset; // @synthesize locationHasOffset=_locationHasOffset;
@property(retain, nonatomic) NSString *tonick; // @synthesize tonick=_tonick;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *act; // @synthesize act=_act;
@property(retain, nonatomic) NSString *gsid; // @synthesize gsid=_gsid;
@property(nonatomic) float latitude; // @synthesize latitude=_latitude;
@property(nonatomic) float longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *errMsg; // @synthesize errMsg=_errMsg;
@property(nonatomic) int errCode; // @synthesize errCode=_errCode;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (BOOL)hasCoordinateLocation;
- (void)dealloc;
- (void)loadFromRS:(id)arg1;
- (BOOL)deleteFromDB:(id)arg1;
- (BOOL)updateDB:(id)arg1;
- (BOOL)insertIntoDB:(id)arg1;
- (id)init;
- (void)removeProperty:(id)arg1;
- (void)addProperty:(id)arg1 withValue:(id)arg2;

@end

