/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBAppUpgradeManagerDelegate <NSObject>
- (void)appUpgradeManager:(id)arg1 didFailToCheckVersionWithError:(id)arg2;
- (void)appUpgradeManager:(id)arg1 didFinishCheckVersionWithResult:(id)arg2 hasNewVersion:(BOOL)arg3;
@end

