/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MTStatusBarOverlayDelegate-Protocol.h"
#import "WBTaskDelegate-Protocol.h"
#import "WBTaskQueueDelegate-Protocol.h"
#import "WBTouchEventTracker-Protocol.h"

@class NSMutableSet, NSString, WBAppWindow, WBStatusBar, WBTaskQueue;

@interface WBAPIAccessorHelper : NSObject <WBTaskQueueDelegate, MTStatusBarOverlayDelegate, WBTouchEventTracker, WBTaskDelegate>
{
    WBTaskQueue *_globalTaskQueue;
    NSString *_uid;
    WBStatusBar *_statusBar;
    int _statusBarState;
    BOOL _reloadingTaskQueue;
    BOOL _showingNewTaskAddedStatus;
    BOOL _queueFaildAndWaitingUserEvent;
    BOOL _onlyShowProgressBar;
    WBAppWindow *_appWindow;
    NSMutableSet *_tasksInCurrentProcess;
}

+ (id)sharedHelper;
+ (void)initialize;
@property(readonly, nonatomic) WBTaskQueue *queue; // @synthesize queue=_globalTaskQueue;
- (void)fullScreen:(BOOL)arg1;
- (id)postLater:(id)arg1;
- (id)post:(id)arg1;
- (void)_postTask:(id)arg1;
- (BOOL)hasUnfinishedTasks;
- (id)allTasks;
- (void)touchEventDidReceive;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)taskQueueDidReload:(id)arg1;
- (void)taskQueueDidUpdateTasks:(id)arg1;
- (void)taskQueueDidRemoveTask:(id)arg1;
- (void)taskQueueDidAddTask:(id)arg1;
- (void)willEnterForeground;
- (void)willWakeup;
- (void)didSuspend;
- (void)statusBarOverlayDidHide;
- (void)allTasksInCurrentProcessFinished:(char *)arg1 hasFail:(char *)arg2;
- (void)allTasksInQueueFinished:(char *)arg1 hasFail:(char *)arg2;
- (void)allTasksFinished:(char *)arg1 hasFail:(char *)arg2 inContainer:(id)arg3;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (void)accountSignedOut;
- (void)accountDBCreated;
- (void)dealloc;
- (id)init;
- (void)updateStatusBarWithEvent:(int)arg1 targetTasks:(id)arg2;
- (void)showStatusIsFinished:(BOOL)arg1 hasFail:(BOOL)arg2;
- (BOOL)isPMTask:(id)arg1;

@end

