/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBModelObject.h"

@class NSDictionary, NSString;

@interface WBAttitude : WBModelObject
{
    BOOL isLocal;
    NSString *attitudeID;
    NSString *name;
    NSString *timelineListIcon;
    NSString *attitudeButtonIcon;
    NSString *attitudeButtonSelectedIcon;
    NSString *attitudeListButtonIcon;
    NSString *userAttitudeIcon;
    NSDictionary *localIconInfos;
}

@property(retain, nonatomic) NSDictionary *localIconInfos; // @synthesize localIconInfos;
@property(retain, nonatomic) NSString *userAttitudeIcon; // @synthesize userAttitudeIcon;
@property(retain, nonatomic) NSString *attitudeListButtonIcon; // @synthesize attitudeListButtonIcon;
@property(retain, nonatomic) NSString *attitudeButtonSelectedIcon; // @synthesize attitudeButtonSelectedIcon;
@property(retain, nonatomic) NSString *attitudeButtonIcon; // @synthesize attitudeButtonIcon;
@property(retain, nonatomic) NSString *timelineListIcon; // @synthesize timelineListIcon;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *attitudeID; // @synthesize attitudeID;
@property(nonatomic) BOOL isLocal; // @synthesize isLocal;
- (void)dealloc;
- (BOOL)updateWithDictionary:(id)arg1;
@property(readonly, nonatomic) NSString *localUserAttitudeIcon;
@property(readonly, nonatomic) NSString *localAttitudeListButtonIcon;
@property(readonly, nonatomic) NSString *localAttitudeButtonSelectedIcon;
@property(readonly, nonatomic) NSString *localAttitudeButtonIcon;
@property(readonly, nonatomic) NSString *localTimelineListIcon;
@property(readonly, nonatomic) BOOL isVisit;
@property(readonly, nonatomic) BOOL isNone;
@property(readonly, nonatomic) BOOL hasIcon;
- (id)timelineListIconImage;

@end

