/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "AVAudioRecorderDelegate-Protocol.h"

@class AVAudioRecorder, NSDate, NSString;

@interface WBAudioRecorder : NSObject <AVAudioRecorderDelegate>
{
    id <WBAudioRecorderDelegate> delegate;
    AVAudioRecorder *audioRecorder;
    unsigned int recorderState;
    NSDate *recordingBeginDate;
    double minimumRecordingDuration;
    double duration;
    NSString *recordingFile;
}

+ (void)clearCache;
@property(retain, nonatomic) NSString *recordingFile; // @synthesize recordingFile;
@property(readonly, nonatomic) double duration; // @synthesize duration;
@property(nonatomic) double minimumRecordingDuration; // @synthesize minimumRecordingDuration;
@property(nonatomic) unsigned int recorderState; // @synthesize recorderState;
@property(nonatomic) id <WBAudioRecorderDelegate> delegate; // @synthesize delegate;
- (void)dealloc;
- (BOOL)deleteRecording;
- (void)markAsErrorOccurredWithError:(id)arg1;
- (void)markAsErrorOccurredWithErrorCode:(int)arg1;
- (void)markAsFinishedWithFile:(id)arg1;
- (void)processAMREncoding;
- (void)audioRecorderEndInterruption:(id)arg1;
- (void)audioRecorderEndInterruption:(id)arg1 withFlags:(unsigned int)arg2;
- (void)audioRecorderBeginInterruption:(id)arg1;
- (void)audioRecorderEncodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(BOOL)arg2;
- (BOOL)cancelRecording;
- (BOOL)stopRecording;
- (BOOL)startRecording;
- (void)prepareToRecord;
- (id)initWithDelegate:(id)arg1;
- (id)init;
- (BOOL)isCancelled;
- (BOOL)isErrorOccurred;
- (BOOL)isFinished;

@end

