/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIControl.h"

@class NSTimer, UIActivityIndicatorView, UIButton, UIImage, UILabel, WBAudioMetadata, WBAudioProgressSlider;

@interface WBAudioPlayerPlugin : UIControl
{
    UIButton *playButton;
    UIButton *stopButton;
    WBAudioProgressSlider *progressSlider;
    UILabel *timeLabel;
    UILabel *promptLabel;
    UIActivityIndicatorView *loadingIndicator;
    BOOL timeLabelDisplaysHours;
    NSTimer *progressTimer;
    WBAudioMetadata *audio;
    int state;
    UIImage *waveformImage;
    id <WBAudioPlayerPluginDelegate> delegate;
}

@property(nonatomic) id <WBAudioPlayerPluginDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) UIImage *waveformImage; // @synthesize waveformImage;
- (void)setAudioMetadata:(id)arg1;
- (void)setTimeLabelText:(id)arg1;
- (void)setPromptLabelText:(id)arg1;
- (void)beginShowProgressSliderAnimation:(BOOL)arg1;
- (void)onProgressTimer:(id)arg1;
- (void)setAudioLength:(unsigned long)arg1;
- (BOOL)setPlayerState:(int)arg1;
- (void)setUIState:(int)arg1;
- (void)setState:(int)arg1;
- (id)formattedAudioTime:(unsigned long)arg1;
- (void)audioPlayerDidStopPlaying:(id)arg1;
- (void)progressSliderValueChanged:(id)arg1;
- (void)stopButtonPressed:(id)arg1;
- (void)playButtonPressed:(id)arg1;
- (void)audioPlayerPluginPressed:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;

@end

