/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface WBAudioMetadata : NSObject
{
    NSString *fileName;
    NSString *url;
    unsigned long length;
    NSArray *waveform;
    int state;
    double currentTime;
}

@property(nonatomic) double currentTime; // @synthesize currentTime;
@property(nonatomic) int state; // @synthesize state;
@property(retain, nonatomic) NSArray *waveform; // @synthesize waveform;
@property(nonatomic) unsigned long length; // @synthesize length;
@property(retain, nonatomic) NSString *url; // @synthesize url;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName;
- (void)dealloc;
- (id)init;

@end

