/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface WBBadgeView : UIView
{
    UIImageView *badgeImageView;
    UILabel *badgeLabel;
    struct CGSize minimumBadgeSize;
    struct CGSize maximumBadgeSize;
    struct UIEdgeInsets badgeLabelEdgeInsets;
    int horizontalAlignment;
    int verticalAlignment;
    BOOL hidesWhenNoBadge;
    NSString *badgeValue;
    int badgeNumber;
}

@property(nonatomic) BOOL hidesWhenNoBadge; // @synthesize hidesWhenNoBadge;
@property(nonatomic) int verticalAlignment; // @synthesize verticalAlignment;
@property(nonatomic) int horizontalAlignment; // @synthesize horizontalAlignment;
@property(nonatomic) struct UIEdgeInsets badgeLabelEdgeInsets; // @synthesize badgeLabelEdgeInsets;
@property(nonatomic) struct CGSize maximumBadgeSize; // @synthesize maximumBadgeSize;
@property(nonatomic) struct CGSize minimumBadgeSize; // @synthesize minimumBadgeSize;
@property(readonly, nonatomic) UILabel *badgeLabel; // @synthesize badgeLabel;
@property(readonly, nonatomic) UIImageView *badgeImageView; // @synthesize badgeImageView;
- (void)dealloc;
- (void)sizeToFit;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) int badgeNumber; // @synthesize badgeNumber;
@property(retain, nonatomic) NSString *badgeValue; // @synthesize badgeValue;
- (void)setup;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

