/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBContactContactsView.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WBContactEngineDelegate-Protocol.h"

@class NSMutableArray, WBContactEngine;

@interface WBContactAtPersonView : WBContactContactsView <UITableViewDelegate, UISearchBarDelegate, WBContactEngineDelegate>
{
    NSMutableArray *combinedContacts;
    NSMutableArray *combinedSearchContacts;
    BOOL hasRecentContacts;
    WBContactEngine *contactEngine;
    int localSearchCount;
    int quickSearchCount;
}

- (void)reloadContacts;
- (void)contactEngine:(id)arg1 didFailQuickSearchByKeyword:(id)arg2 error:(id)arg3;
- (void)contactEngine:(id)arg1 didFinishQuickSearchOfUsers:(id)arg2 keyword:(id)arg3;
- (void)searchBarBecomeFirstResponder;
- (void)setSearchBarPlaceHolder;
- (id)searchBarText;
- (id)localSearchPredicateForKey:(id)arg1;
- (void)showSearchResult:(BOOL)arg1;
- (void)cancelSearching;
- (void)startSearching;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)combineSearchContactsDataSource;
- (void)combineContactsDataSource;
- (void)copySearchDataSource;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)contactsDataSourceOfTableView:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

