/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBRoundedAvatarView.h"

@class WBContact;

@interface WBContactAvatarView : WBRoundedAvatarView
{
    WBContact *contact;
}

+ (float)contentMeasureOfContact:(id)arg1;
+ (float)totalMeasure;
@property(retain, nonatomic) WBContact *contact; // @synthesize contact;
- (void)dealloc;
- (void)setAvatarImage:(id)arg1;
- (float)contentMeasure;
- (void)configMeasures;

@end

