/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "ActionSheetHintDelegate-Protocol.h"
#import "PRLMTableViewWrapperDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ActionSheetHint, NSMutableArray, NSString, WBPRLMTableViewWrapper, WBTableView;

@interface WBContactSearchOnlineContactsViewController : WBViewController <UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate, ActionSheetHintDelegate, PRLMTableViewWrapperDelegate>
{
    WBTableView *contactsTableView;
    WBPRLMTableViewWrapper *prWrapper;
    NSMutableArray *searchResults;
    ActionSheetHint *actionSheetHint;
    NSString *searchKey;
}

@property(retain, nonatomic) NSString *searchKey; // @synthesize searchKey;
@property(readonly, nonatomic) WBPRLMTableViewWrapper *prWrapper; // @synthesize prWrapper;
@property(readonly, nonatomic) WBTableView *contactsTableView; // @synthesize contactsTableView;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)contactForCell:(id)arg1;
- (id)tableView:(id)arg1 contactForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)hideHint;
- (void)showHint:(id)arg1 cancelable:(BOOL)arg2;
- (void)viewProfileOfContact:(id)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

