/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBModelObject.h"

#import "WBDatabaseModel-Protocol.h"

@class NSArray, NSString;

@interface WBContactGroup : WBModelObject <WBDatabaseModel>
{
    unsigned int groupType;
    NSString *groupID;
    NSString *name;
    NSString *userID;
    unsigned int contactsCount;
    unsigned int badgeCount;
    NSArray *subGroups;
    BOOL isOwnedByCurrentUser;
}

+ (void)deleteAllGroupsFromDB:(id)arg1;
+ (id)groupWithGroupID:(id)arg1 type:(unsigned int)arg2;
+ (id)groupWithGroupID:(id)arg1 name:(id)arg2 type:(unsigned int)arg3;
+ (BOOL)isValidForDictionary:(id)arg1;
@property(retain, nonatomic) NSArray *subGroups; // @synthesize subGroups;
@property(nonatomic) unsigned int badgeCount; // @synthesize badgeCount;
@property(nonatomic) unsigned int contactsCount; // @synthesize contactsCount;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID;
@property(nonatomic) unsigned int groupType; // @synthesize groupType;
- (void)dealloc;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)saveToDB:(id)arg1;
- (void)loadFromRS:(id)arg1 andDB:(id)arg2;
- (void)deleteFromDB:(id)arg1;
- (void)updateDB:(id)arg1;
- (void)insertIntoDB:(id)arg1;
- (BOOL)isValidToPersist;
@property(readonly, nonatomic) BOOL hasValidUserID;
@property(readonly, nonatomic) BOOL isOwnedByCurrentUser; // @synthesize isOwnedByCurrentUser;
- (BOOL)updateWithJSONDictionary:(id)arg1;
- (id)init;

@end

