/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBContactContactsTableViewCell.h"

@class UIControl, WBContactDataButton;

@interface WBContactAddressBookContactCell : WBContactContactsTableViewCell
{
    UIControl *meAccessoryView;
    WBContactDataButton *statusesButton;
    WBContactDataButton *favoritesButton;
    WBContactDataButton *followersButton;
}

- (void)appLanguageDidChangeNotification:(id)arg1;
- (void)refreshMyContactCard;
- (void)contactEngineDidClearFollowerUnreadCountNotification:(id)arg1;
- (void)accountDidReceiveUnreadCountNotification:(id)arg1;
- (void)updateFollowerUnreadCount;
- (void)reloadUIElements;
- (void)followersButtonPressed:(id)arg1;
- (void)favoritesButtonPressed:(id)arg1;
- (void)statusesButtonPressed:(id)arg1;
- (void)layoutSubviews;
- (void)setContact:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

