/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBHintBoard.h"

@class UIImageView, WBAdModel;

@interface WBContentAdHintBoard : WBHintBoard
{
    UIImageView *adsView;
    WBAdModel *contentAdModel;
}

@property(retain, nonatomic) WBAdModel *contentAdModel; // @synthesize contentAdModel;
- (void)dealloc;
- (void)contentAdscrollDraggingAnimation:(BOOL)arg1;
- (void)settingContentAdPhoto:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 dismissDirection:(int)arg2;

@end

