/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBContactContactsViewDelegate-Protocol.h"

@protocol WBContactFollowerContactsViewDelegate <WBContactContactsViewDelegate>
- (void)followerContactsView:(id)arg1 searchFollowersOnlineWithKey:(id)arg2;
- (void)followerContactsView:(id)arg1 didFailToDownloadFollowersWithError:(id)arg2;
@end

