/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBAPITaskBase.h"

@class NSString;

@interface WBCommentTask : WBAPITaskBase
{
    NSString *_srcid;
    NSString *_srcuid;
    int _rt;
    NSString *_cmtuid;
    NSString *_cmtid;
}

+ (unsigned int)taskType;
@property(retain, nonatomic) NSString *cmtid; // @synthesize cmtid=_cmtid;
@property(retain, nonatomic) NSString *cmtuid; // @synthesize cmtuid=_cmtuid;
@property(nonatomic) int rt; // @synthesize rt=_rt;
@property(retain, nonatomic) NSString *srcuid; // @synthesize srcuid=_srcuid;
@property(retain, nonatomic) NSString *srcid; // @synthesize srcid=_srcid;
- (void)loadFromRS:(id)arg1;
- (BOOL)updateDB:(id)arg1;
- (BOOL)insertIntoDB:(id)arg1;
- (id)act;
- (BOOL)isCommentToComment;
- (void)dealloc;
- (id)init;

@end

