/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "SNPopoverWindowDismissDelegate-Protocol.h"
#import "WBContactAddressBookGroupsViewDelegate-Protocol.h"
#import "WBContactContactsViewDelegate-Protocol.h"
#import "WBContactFollowerContactsViewDelegate-Protocol.h"
#import "WBContactRefreshOverlayViewControllerDelegate-Protocol.h"
#import "WBHelperViewDelegate-Protocol.h"
#import "WBSkinning-Protocol.h"

@class WBContactAddressBookContactsView, WBContactAddressBookGroupButton, WBContactAddressBookGroupsView, WBContactEngine, WBContactFollowerContactsView, WBContactGroup, WBContactRefreshHUDViewController, WBContactRefreshOverlayViewController, WBFindFriendsEngine;

@interface WBContactViewController : WBViewController <WBContactContactsViewDelegate, WBContactFollowerContactsViewDelegate, WBContactAddressBookGroupsViewDelegate, MFMessageComposeViewControllerDelegate, SNPopoverWindowDismissDelegate, WBContactRefreshOverlayViewControllerDelegate, WBSkinning, WBHelperViewDelegate>
{
    WBContactAddressBookGroupsView *groupsView;
    WBContactAddressBookGroupButton *groupButton;
    WBContactAddressBookContactsView *contactsView;
    WBContactFollowerContactsView *followerContactsView;
    BOOL isFirstTimeLoadView;
    BOOL shouldHideNavigationBarBeforeViewAppear;
    WBContactGroup *selectedGroup;
    BOOL viewOnTop;
    BOOL receivedGroupChangeNotification;
    BOOL receivedContactChangeNotification;
    WBFindFriendsEngine *findFriendsEngine;
    BOOL shouldDownloadAddressBook;
    WBContactRefreshOverlayViewController *refreshOverlayViewController;
    WBContactRefreshHUDViewController *refreshHUDViewController;
    WBContactEngine *contactEngine;
    unsigned int newFollowersCount;
}

@property(retain, nonatomic) WBContactGroup *selectedGroup; // @synthesize selectedGroup;
- (void)helperViewDidHide:(id)arg1;
- (void)tabBarControllerDidSelect:(id)arg1;
- (void)contactEngineDidClearFollowerUnreadCountNotification:(id)arg1;
- (void)accountDidReceiveUnreadCountNotification:(id)arg1;
- (void)updateFollowerUnreadCount:(int)arg1;
- (void)accountDidChangeNotification:(id)arg1;
- (void)followerContactsView:(id)arg1 searchFollowersOnlineWithKey:(id)arg2;
- (void)followerContactsView:(id)arg1 didFailToDownloadFollowersWithError:(id)arg2;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)contactsView:(id)arg1 didPressFavoritesButtonOfContact:(id)arg2;
- (void)contactsView:(id)arg1 didPressStatusesButtonOfContact:(id)arg2;
- (void)contactsView:(id)arg1 didPressFollowersButtonOfContact:(id)arg2;
- (void)contactsView:(id)arg1 didPressSendTextButtonOfContact:(id)arg2;
- (void)contactsView:(id)arg1 didPressMakeCallButtonOfContact:(id)arg2;
- (void)contactsView:(id)arg1 didPressSendPMButtonOfContact:(id)arg2;
- (void)contactsView:(id)arg1 didPressAvatarViewOfContact:(id)arg2;
- (void)didEndSearchInContactsView:(id)arg1;
- (void)didBeginSearchInContactsView:(id)arg1;
- (void)reloadAll;
- (void)reloadContacts;
- (void)reloadGroups;
- (void)groupsViewDidPressEditGroupsButton:(id)arg1;
- (void)groupsViewDidPressRefreshContactsButton:(id)arg1;
- (void)groupsView:(id)arg1 didSelectGroup:(id)arg2;
- (void)showContactsForGroup:(id)arg1;
- (void)contactRefreshOverlayViewController:(id)arg1 didPressRetryButton:(id)arg2;
- (void)refreshContacts;
- (void)refreshContactsFirstTime:(BOOL)arg1;
- (void)setRefreshUserInteractionEnabled:(BOOL)arg1 firstTime:(BOOL)arg2;
- (void)popoverWillDismiss:(id)arg1;
- (void)groupButtonPressed:(id)arg1;
- (void)handleGroupsDidChangeNotification;
- (void)handleContactsDidChangeNotification;
- (void)pushViewController:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)appLanguageDidChangeNotification:(id)arg1;
- (void)currentSkinDidChangeNotification:(id)arg1;
- (void)reloadUIElements;
- (void)reloadTabBarItem;
- (void)resetBadgeValue;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

