/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "WBContactAtPersonSearchViewControllerDelegate-Protocol.h"
#import "WBContactContactsViewDelegate-Protocol.h"

@class WBContactAtPersonView, WBContactEngine;

@interface WBContactAtPersonViewController : WBViewController <WBContactContactsViewDelegate, WBContactAtPersonSearchViewControllerDelegate>
{
    WBContactAtPersonView *atPersonView;
    id <WBContactAtPersonViewControllerDelegate> delegate;
    WBContactEngine *contactEngine;
}

@property(nonatomic) id <WBContactAtPersonViewControllerDelegate> delegate; // @synthesize delegate;
- (void)refreshContacts:(id)arg1;
- (void)atPersonSearchViewController:(id)arg1 didSelectContact:(id)arg2;
- (void)contactsView:(id)arg1 didPressAvatarViewOfContact:(id)arg2;
- (void)didEndSearchInContactsView:(id)arg1;
- (void)didBeginSearchInContactsView:(id)arg1;
- (void)dismissModalViewController;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

