/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBContactContactsView.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@interface WBContactMessageContactsView : WBContactContactsView <UITableViewDelegate, UISearchBarDelegate>
{
}

- (void)reloadContacts;
- (void)showSearchResult:(BOOL)arg1;
- (void)cancelSearching;
- (void)startSearching;
- (void)setSearchBarPlaceHolder;
- (id)searchBarText;
- (id)localSearchPredicateForKey:(id)arg1;
- (void)copySearchDataSource;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

