/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBContact.h"

@class UIImage;

@interface WBContact (RelationshipImage)
+ (id)imageForUserRelationship:(unsigned int)arg1;
@property(readonly, nonatomic) UIImage *relationshipImage;
@end

