/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBContactContactsTableViewCellDelegate <NSObject>
- (void)didPressFavoritesButtonInCell:(id)arg1 contact:(id)arg2;
- (void)didPressStatusesButtonInCell:(id)arg1 contact:(id)arg2;
- (void)didPressFollowersButtonInCell:(id)arg1 contact:(id)arg2;
- (void)didPressSendTextButtonInCell:(id)arg1 contact:(id)arg2;
- (void)didPressMakeCallButtonInCell:(id)arg1 contact:(id)arg2;
- (void)didPressSendPMButtonInCell:(id)arg1 contact:(id)arg2;
@end

