/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface WBDataParser : NSObject
{
}

+ (id)hashtagsFromString:(id)arg1;
+ (id)mentionsFromString:(id)arg1;
+ (id)absolueLinksFromString:(id)arg1;
+ (id)linksFromString:(id)arg1;
+ (id)matchesInString:(id)arg1 byUsingRegularExpression:(id)arg2;

@end

