/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBDatabaseModel <NSObject>

@optional
- (BOOL)isValidToPersist;
- (void)saveToDB:(id)arg1;
- (BOOL)mergeFromDB:(id)arg1;
- (void)loadFromRS:(id)arg1 andDB:(id)arg2;
- (void)deleteFromDB:(id)arg1;
- (void)updateDB:(id)arg1;
- (void)insertIntoDB:(id)arg1;
@end

