/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface WBEmoticonsManager : NSObject
{
    NSArray *emoticons;
    NSDictionary *keyedEmoticons;
    unsigned int count;
    unsigned int emoticonsCount;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSDictionary *keyedEmoticons; // @synthesize keyedEmoticons;
@property(retain, nonatomic) NSArray *emoticons; // @synthesize emoticons;
- (id)escapeEmoticonsForHTMLWithString:(id)arg1;
- (id)emoticonAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int emoticonsCount; // @synthesize emoticonsCount;
- (void)dealloc;
- (id)init;

@end

