/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBContactGroup.h"

@class NSString;

@interface WBFeedGroup : WBContactGroup
{
    NSString *type;
}

+ (BOOL)isValidForDictionary:(id)arg1;
@property(retain, nonatomic) NSString *type; // @synthesize type;
- (void)dealloc;
- (BOOL)updateWithJSONDictionary:(id)arg1;

@end

