/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class SNHTTPRequestOperationWrapper;

@interface WBFindFriendsEngine : NSObject
{
    SNHTTPRequestOperationWrapper *fetchRequestOperationWrapper;
}

- (void)dealloc;
- (void)cancelLoading;
- (void)fetchGuessUsersWithCompletionHandler:(id)arg1;
- (id)parsedContactsFromArray:(id)arg1;
- (void)saveCachedAddressBookForContact:(id)arg1;
- (void)fetchCachedAddressBookWithCompletionHandler:(id)arg1;
- (void)disableAddressBookWithCompletionHanlder:(id)arg1;
- (void)downloadAddressBookWithCompletionHandler:(id)arg1;
- (void)downloadAddressBookAndSaveToDatabase;
- (void)uploadAddressBookWithCompletionHandler:(id)arg1 uploadProgressBlock:(void)arg2;
- (void)checkForMobileBindingWithCompletionHandler:(id)arg1;
- (void)fetchShakeUsersWithLocation:(id)arg1 completionHandler:(id)arg2;

@end

