/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ASIOAuthRequest.h"

@class NSString, NSURL;

@interface WBFileRequest : ASIOAuthRequest
{
    NSString *_key;
    NSURL *_initialURL;
}

@property(retain, nonatomic) NSURL *initialURL; // @synthesize initialURL=_initialURL;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void)dealloc;

@end

