/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewController.h"

#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "PRLMTableViewWrapperDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "WBUserTableViewCellDelegate-Protocol.h"

@class NSArray, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIImageView, UILabel, UIViewController, WBContactEngine, WBFindFriendsEngine, WBPRLMTableViewWrapper, WBProgressView;

@interface WBFindFriendsAddressBookViewController : WBTableViewController <PRLMTableViewWrapperDelegate, WBUserTableViewCellDelegate, MFMessageComposeViewControllerDelegate, UIActionSheetDelegate>
{
    UIViewController *rootViewController;
    UIBarButtonItem *disableAddressBookItem;
    WBPRLMTableViewWrapper *tableViewWrapper;
    WBFindFriendsEngine *findFriendsEngine;
    WBContactEngine *contactEngine;
    NSArray *users;
    BOOL needsReloadData;
    unsigned int addressBookState;
    UIActivityIndicatorView *activityIndicatorView;
    UIImageView *tipImageView;
    UILabel *titleLabel;
    UILabel *tipLabel;
    WBProgressView *progressView;
    UIButton *startButton;
    UIButton *bindButton;
}

@property(nonatomic) unsigned int addressBookState; // @synthesize addressBookState;
@property(retain, nonatomic) NSArray *users; // @synthesize users;
- (void)handleContactsDidChangeNotification:(id)arg1;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)relationshipButton:(id)arg1 didPressInCell:(id)arg2;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)bindButtonPressed:(id)arg1;
- (void)startButtonPressed:(id)arg1;
- (void)loadLocalCache;
- (void)downloadAddressBook;
- (void)disableAddressBookButtonPressed:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)clearRootViewController;
- (id)initWithRootViewController:(id)arg1;

@end

