/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface WBGeneralEngine : NSObject
{
}

+ (void)appInstallStatistics;
+ (void)doAppInstallStatisticsWithType:(id)arg1;
+ (id)removeStatus:(id)arg1 inView:(id)arg2 withCompletionHandler:(id)arg3;
+ (id)favoritOrFavoritUnStatus:(id)arg1 inView:(id)arg2 withCompletionHandler:(id)arg3;
+ (id)getUserInfomationWithUserID:(id)arg1 screenName:(id)arg2 completionHandler:(id)arg3;
+ (id)followOfficialAccount:(id)arg1;

@end

