/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIScrollView.h"

@class NSMutableArray, NSMutableDictionary;

@interface WBGridView : UIScrollView
{
    id <WBGridViewDataSource> _dataSource;
    NSMutableArray *_visibleTiles;
    NSMutableDictionary *_reusableGridTiles;
    struct _NSRange _visibleTilesIndexRange;
    int _tilesPerRow;
    int _preloadRows;
    struct CGSize _gridSize;
    struct CGSize _gridPadding;
    float _gridViewHorizontalMargin;
    struct CGSize _preloadMargin;
}

@property(nonatomic) struct CGSize gridPadding; // @synthesize gridPadding=_gridPadding;
@property(nonatomic) struct CGSize gridSize; // @synthesize gridSize=_gridSize;
@property(nonatomic) int tilesPerRow; // @synthesize tilesPerRow=_tilesPerRow;
@property(nonatomic) id <WBGridViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) id <WBGridViewDelegate> delegate;
- (void)reloadData;
- (id)dequeueReusableTileWithIdentifier:(id)arg1;
- (struct _NSRange)rangeOfVisibleTileIndexes;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

