/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class UIImageView;

@interface WBHelperView : UIView
{
    id <WBHelperViewDelegate> delegate;
    UIImageView *imageView;
}

@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) id <WBHelperViewDelegate> delegate; // @synthesize delegate;
- (void)helperViewDidHide;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

