/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBPullRefreshHeaderView.h"

@class WBAdModel;

@interface WBHomePullRefreshHeaderView : WBPullRefreshHeaderView
{
    WBAdModel *currentAdModel;
    WBAdModel *newsAdModel;
    BOOL isNeedUpdateToNewAdModel;
}

@property(retain, nonatomic) WBAdModel *newsAdModel; // @synthesize newsAdModel;
@property(retain, nonatomic) WBAdModel *currentAdModel; // @synthesize currentAdModel;
- (void)dealloc;
- (id)localizedPromptText;
- (void)didFinishPullRefreshAnimation;
- (void)homeViewPullRefreshAdPhotoDidChangeNotification:(id)arg1;
- (void)setAdModelFromManager;
- (void)reloadUIElements;
- (id)initWithFrame:(struct CGRect)arg1;

@end

