/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIBarButtonItem.h"

@class UIImage;

@interface WBImageBarItem : UIBarButtonItem
{
    UIImage *highlightedImage;
    id userInfo;
    id clickBlock;
}

@property(copy, nonatomic) id clickBlock; // @synthesize clickBlock;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo;
@property(retain, nonatomic) UIImage *highlightedImage; // @synthesize highlightedImage;
- (void)dealloc;

@end

