/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, NSMutableArray;

@interface WBImageBar : UIView
{
    id <WBImageBarDelegate> delegate;
    NSArray *items;
    NSMutableArray *buttons;
    float itemPadding;
    struct UIEdgeInsets edgeInsets;
}

@property(nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets;
@property(nonatomic) float itemPadding; // @synthesize itemPadding;
@property(copy, nonatomic) NSArray *items; // @synthesize items;
@property(nonatomic) id <WBImageBarDelegate> delegate; // @synthesize delegate;
- (void)dealloc;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)buttonPressed:(id)arg1;
- (id)initWithImages:(id)arg1;
- (id)initWithItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

