/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIButton.h"

@class WBImageBarItem;

@interface WBImageBarButton : UIButton
{
    WBImageBarItem *item;
}

@property(retain, nonatomic) WBImageBarItem *item; // @synthesize item;
- (void)sizeToFit;
- (void)dealloc;

@end

