/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBHintBoard.h"

@class UIImageView, UILabel;

@interface WBLBSNearbyPeopleHintBoard : WBHintBoard
{
    UILabel *countLabel;
    UIImageView *locationImageView;
}

- (void)dealloc;
- (void)showHintWithNearbyPeopleCount:(unsigned int)arg1;
- (void)initHintLabel;
- (void)initCloseButton;
- (id)initWithFrame:(struct CGRect)arg1 dismissDirection:(int)arg2;
- (void)reloadUIElements;
- (void)appLanguageDidChange:(id)arg1;

@end

