/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBGridViewTile.h"

@class UIImageView, UILabel, WBContactAvatarView;

@interface WBLikeUserListGridViewTile : WBGridViewTile
{
    WBContactAvatarView *avatarView;
    UIImageView *attitudeView;
    UILabel *screenNameLabel;
}

@property(readonly, nonatomic) WBContactAvatarView *avatarView; // @synthesize avatarView;
- (void)setFrame:(struct CGRect)arg1;
- (void)setOrigin:(struct CGPoint)arg1;
- (void)setLikeUser:(id)arg1;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

@end

