/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBStatusBusinessEngine.h"

@class WBAttitude;

@interface WBLikeEngine : WBStatusBusinessEngine
{
    WBAttitude *attitudeToPost;
}

+ (void)setIsRetweetWhileLiking:(BOOL)arg1;
+ (BOOL)isRetweetWhileLiking;
@property(retain, nonatomic) WBAttitude *attitudeToPost; // @synthesize attitudeToPost;
- (void)fetchDataWithCompletionHandler:(id)arg1;
- (void)postAttitude;
- (void)dealloc;
- (id)initWithStatus:(id)arg1;

@end

