/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewCell.h"

@class NSArray, NSMutableArray;

@interface WBLikeUserListTableViewCell : WBTableViewCell
{
    int tilesPerRow;
    NSMutableArray *tileViews;
    NSArray *contacts;
    id <WBLikeUserListTableViewCellDelegate> delegate;
}

+ (float)rowHeightOfDataObject:(id)arg1;
@property(nonatomic) id <WBLikeUserListTableViewCellDelegate> delegate; // @synthesize delegate;
@property(nonatomic) int tilesPerRow; // @synthesize tilesPerRow;
- (void)setContacts:(id)arg1;
- (void)avatarViewPressed:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

