/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewCell.h"

@class NSArray, UIButton, UIImageView;

@interface WBLikeTableViewCell : WBTableViewCell
{
    NSArray *attitudes;
    BOOL retweet;
    UIButton *retweetButton;
    id likeWithAttitudeBlock;
    UIImageView *separatorImageView;
}

+ (float)rowHeightOfDataObject:(id)arg1;
@property(copy, nonatomic) id likeWithAttitudeBlock; // @synthesize likeWithAttitudeBlock;
@property(readonly, nonatomic) BOOL retweet; // @synthesize retweet;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)setupWithAttitudes:(id)arg1;
- (void)setupUIElements;
- (void)retweetButtonPressed:(id)arg1;
- (void)resetRetweetButtonImage;
- (void)attitudeButtonDidPressed:(id)arg1;

@end

