/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PRLMFooterView.h"

#import "WBAppLanguageObserver-Protocol.h"
#import "WBSkinning-Protocol.h"

@class WBRoundedImageView;

@interface WBLoadMoreFooterView : PRLMFooterView <WBSkinning, WBAppLanguageObserver>
{
    WBRoundedImageView *selectedBackgroundView;
}

- (void)dealloc;
- (void)appLanguageDidChange:(id)arg1;
- (id)localizedPromptText;
- (void)setHighlighted:(BOOL)arg1;
- (void)reloadUIElements;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

