/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocation, CLLocationManager;

@interface WBLocationManager : NSObject <CLLocationManagerDelegate>
{
    unsigned int locationManagerMode;
    CLLocationManager *locationManager;
    BOOL locating;
    double timeoutInterval;
    unsigned int retryTimes;
    CLLocation *bestEffortAtLocation;
    CLLocation *currentLocation;
    BOOL currentLocationOffset;
    CLLocation *previousLocation;
    BOOL previousLocationOffset;
    id <WBLocationManagerDelegate> delegate;
}

+ (void)showError:(id)arg1;
+ (id)sharedManager;
@property(nonatomic) BOOL previousLocationOffset; // @synthesize previousLocationOffset;
@property(retain, nonatomic) CLLocation *previousLocation; // @synthesize previousLocation;
@property(nonatomic) BOOL currentLocationOffset; // @synthesize currentLocationOffset;
@property(retain, nonatomic) CLLocation *currentLocation; // @synthesize currentLocation;
@property(retain, nonatomic) CLLocation *bestEffortAtLocation; // @synthesize bestEffortAtLocation;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval;
@property(nonatomic, getter=isLocating) BOOL locating; // @synthesize locating;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager;
@property(nonatomic) unsigned int locationManagerMode; // @synthesize locationManagerMode;
@property(nonatomic) id <WBLocationManagerDelegate> delegate; // @synthesize delegate;
- (id)localizedDescriptionForErrorCode:(unsigned int)arg1;
- (id)localizedFailureReasonForErrorCode:(unsigned int)arg1;
- (id)errorWithCode:(unsigned int)arg1;
- (void)markAsErrorOccurredWithErrorCode:(unsigned int)arg1;
- (void)markAsErrorOccurredWithError:(id)arg1;
- (void)markAsFinishedWithLocation:(id)arg1;
- (void)timeout;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation;
- (void)dealloc;
- (id)init;

@end

