/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBMapLocationViewControllerDelegate <NSObject>
- (void)mapLocationViewControllerDidCancel:(id)arg1;
- (void)mapLocationViewController:(id)arg1 didLocateWithCoordinate:(CDStruct_2c43369c)arg2;
@end

