/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIButton.h"

@interface WBMessageMapButton : UIButton
{
    CDStruct_2c43369c coordinate;
}

@property(nonatomic) CDStruct_2c43369c coordinate; // @synthesize coordinate;
- (void)setImage:(id)arg1 forState:(unsigned int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

