/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "WBTaskDelegate-Protocol.h"

@class FMDatabase, MGTwitterEngine, NSMutableArray, NSMutableDictionary, NSString, NSTimer, WBConversation;

@interface WBMessagesEngine : NSObject <WBTaskDelegate>
{
    MGTwitterEngine *_twitter;
    FMDatabase *_db;
    id <WBMessagesEngineDelegate> _delegate;
    NSTimer *_heartbeatTimer;
    NSString *_heartbeatConnId;
    WBConversation *_conversation;
    NSString *_targetUserId;
    NSMutableArray *_messageGroups;
    unsigned long long _sendingMessageId;
    int _serverHasMoreMessages;
    BOOL _hasMoreMessages;
    BOOL _alive;
    NSMutableDictionary *_connUserInfos;
    NSString *_deleteMsgConnId;
}

+ (void)updateStateForMessageOfTask:(id)arg1 fromDB:(id)arg2 currentMinServerConfirmedId:(id)arg3;
+ (void)removeMessageOfTask:(id)arg1 fromDB:(id)arg2;
+ (id)engineWithConversation:(id)arg1;
@property(retain, nonatomic) WBConversation *conversation; // @synthesize conversation=_conversation;
@property(readonly, nonatomic) BOOL hasMoreMessages; // @synthesize hasMoreMessages=_hasMoreMessages;
@property(readonly, nonatomic) NSMutableArray *messageGroups; // @synthesize messageGroups=_messageGroups;
@property(readonly, nonatomic) NSString *targetUserId; // @synthesize targetUserId=_targetUserId;
@property(nonatomic) id <WBMessagesEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)resumeTaskOfMessage:(id)arg1;
- (BOOL)pauseTaskOfMessage:(id)arg1;
- (void)taskDidRemove:(id)arg1;
- (void)taskStateDidChange:(id)arg1;
- (void)forwardPMF:(id)arg1 userScreenName:(id)arg2 avatarUrl:(id)arg3;
- (void)sendPMF:(id)arg1;
- (void)forwardPM:(id)arg1 userScreenName:(id)arg2 avatarUrl:(id)arg3;
- (void)sendPM:(id)arg1;
- (void)notifyMessageAdded;
- (void)endConversation;
- (void)beginConversation;
- (void)stopHeartbeat;
- (void)startHeartbeat;
- (void)cancelHeartbeatTimer;
- (void)heartbeat;
- (void)processServerHeartbeatMessages:(id)arg1;
- (void)processServerHeartbeatFaild;
- (void)refreshMessages;
- (void)processServerLatestMessages:(id)arg1 action:(int)arg2;
- (void)cancelDeleteMessage;
- (void)deleteMessage:(id)arg1;
- (void)deleteLocalDataForMessage:(id)arg1;
- (void)loadHistoryMessagesForFirstScreen;
- (void)loadMoreHistoryMessages;
- (void)notifyMessageLoadingDidSucceed;
- (void)processServerHistoryMessages:(id)arg1;
- (id)loadServerMessagesWithMaxId:(id)arg1 orMinId:(id)arg2 action:(int)arg3;
- (id)loadServerMessagesWithMaxId:(id)arg1 orMinId:(id)arg2 count:(unsigned int)arg3 action:(int)arg4;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)initTwitterEngine;
- (void)cancelTwitterEngine;
- (void)deleteAllLocalMessages;
- (id)getLocalHistoryMessagesBefore:(double)arg1 after:(double)arg2 count:(unsigned int)arg3 order:(int)arg4;
- (id)getLocalHistoryMessagesBefore:(double)arg1 after:(double)arg2 count:(unsigned int)arg3 order:(int)arg4 equalBefore:(BOOL)arg5 equalAfter:(BOOL)arg6;
- (BOOL)isAlive;
- (void)dealloc;
- (id)initWithConversation:(id)arg1;

@end

