/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBMessagesEngineDelegate <NSObject>
- (void)messageDidRemove:(id)arg1 success:(BOOL)arg2;
- (void)messageDidAdd:(id)arg1;
- (void)messageLoadingDidFail:(id)arg1 error:(id)arg2 action:(int)arg3;
- (void)messageLoadingDidSucceed:(id)arg1 action:(int)arg2;
@end

