/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WBSkinning-Protocol.h"

@class NSMutableArray, UIButton, UIColor, UIControl, UIImageView, UITableView, WBTableView;

@interface WBMessageCenterFilterComponent : NSObject <UITableViewDelegate, UITableViewDataSource, WBSkinning>
{
    NSMutableArray *droplistItems;
    unsigned int droplistSelectedIndex;
    BOOL droplistAnimating;
    BOOL droplistHidden;
    float droplistHeight;
    float droplistAlpha;
    UIColor *previousSeparatorColor;
    int style;
    UIButton *titleView;
    UIImageView *titleSeparatorImageView;
    UIImageView *titleArrowImageView;
    UITableView *droplistTableView;
    UIImageView *popoverView;
    UIControl *overlayView;
    WBTableView *rootTableView;
    id <WBMessageCenterFilterComponentDelegate> delegate;
}

@property(nonatomic) id <WBMessageCenterFilterComponentDelegate> delegate; // @synthesize delegate;
@property(readonly, nonatomic) float droplistHeight; // @synthesize droplistHeight;
@property(nonatomic) UITableView *rootTableView; // @synthesize rootTableView;
@property(readonly, nonatomic) UITableView *droplistTableView; // @synthesize droplistTableView;
@property(readonly, nonatomic) UIButton *titleView; // @synthesize titleView;
- (void)reloadUIElements;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (BOOL)hideDroplist:(BOOL)arg1;
- (void)updateUIForNewMessageCountChange;
- (void)updateUIForLanguageChange;
- (void)setDroplistSelectedIndex:(unsigned int)arg1;
- (void)setDroplistItems:(id)arg1 selectedIndex:(unsigned int)arg2;
- (float)titleViewHeight;
- (void)overlayViewTouched:(id)arg1;
- (void)titleViewPressed:(id)arg1;
- (unsigned int)absoluteRowOfIndexPath:(id)arg1;
- (void)notifyDelegateOfDroplistItemSelection;
- (void)switchDroplistState:(BOOL)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;

@end

