/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBMessagesInputViewDelegate <NSObject>

@optional
- (void)messagesInputViewDidPressBackspaceButtonOnKeyboard:(id)arg1;
- (void)messagesInputViewDidPressSendButtonOnKeyboard:(id)arg1;
- (void)messagesInputView:(id)arg1 willChangeHeightFrom:(float)arg2 to:(float)arg3;
@end

