/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBUserTableViewCell.h"

@class UIImageView, WBAdModel;

@interface WBMessageAdCell : WBUserTableViewCell
{
    WBAdModel *advertisement;
    UIImageView *badgeView;
}

+ (float)rowHeightOfDataObject:(id)arg1;
@property(retain, nonatomic) WBAdModel *advertisement; // @synthesize advertisement;
- (void)dealloc;
- (void)layoutSubviews;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

