/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBMessagesTableViewController.h"

#import "WBMessagesInputViewDelegate-Protocol.h"

@interface WBMessagesTableViewController (Layout) <WBMessagesInputViewDelegate>
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)messagesInputView:(id)arg1 willChangeHeightFrom:(float)arg2 to:(float)arg3;
- (void)changeInputViewStateTo:(unsigned int)arg1 keyboardHeight:(float)arg2 animationDuration:(double)arg3;
- (void)downInputViewWithAnimationDuration:(double)arg1;
- (void)adjustShadowFrame;
- (void)adjustTableViewFrame;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)hideToolbar;
- (void)showToolbar;
- (void)initializeLayout;
@end

