/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBStatusTableViewController.h"

#import "PRLMTableViewWrapperDelegate-Protocol.h"
#import "WBLBSNearbyEngineDelegate-Protocol.h"

@class WBLBSNearbyEngine;

@interface WBNearWeiboViewController : WBStatusTableViewController <WBLBSNearbyEngineDelegate, PRLMTableViewWrapperDelegate>
{
    WBLBSNearbyEngine *nearbyEngine;
    BOOL isLoading;
}

- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)locationManagerDidFailToLocateNotification:(id)arg1;
- (void)locationManagerDidFinishLocatingNotification:(id)arg1;
- (void)lbsNearbyEngine:(id)arg1 didFailToLoadNearbyPeopleWithError:(id)arg2;
- (void)lbsNearbyEngine:(id)arg1 didLoadNearbyWeibo:(id)arg2 hasMore:(BOOL)arg3;
- (void)viewWillAppear:(BOOL)arg1;
- (void)checkInButtonPress:(id)arg1;
- (void)viewDidLoad;
- (void)configPRLMWrapper;
- (void)didReceiveMemoryWarning;
- (id)init;

@end

