/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SNNetworkClient.h"

@class NSArray;

@interface WBNetworkClient : SNNetworkClient
{
    BOOL useSecureConnection;
    BOOL ignoreReachabilityStatus;
    NSArray *disabledDefaultParameters;
}

+ (id)sharedTestClient;
+ (id)sharedClient;
+ (id)ua;
@property(retain, nonatomic) NSArray *disabledDefaultParameters; // @synthesize disabledDefaultParameters;
@property(nonatomic) BOOL ignoreReachabilityStatus; // @synthesize ignoreReachabilityStatus;
- (id)wrapperWithRequest:(id)arg1 successBlock:(id)arg2 failureBlock:(void)arg3;
- (id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3;
- (id)parametersByAppendDefaultParameters:(id)arg1;
- (void)dealloc;
- (void)ChooseAndResetV4BaseUrl:(id)arg1;
- (id)initWithBaseURL:(id)arg1;
- (void)resetSecureConnection;
- (id)connectionURLScheme;
- (void)didSuccessAfterSwithHTTPS2HTTP;
- (void)reachabilityChanged:(id)arg1;
- (BOOL)isWIFIConnected;
- (void)accountSignedOut;
- (void)accountDBCreated;
- (void)resetAccountAuthParameters;
- (void)appLanguageDidChange:(id)arg1;
- (void)resetLanguageParameter;

@end

