/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SNNetworkErrorHandler-Protocol.h"
#import "WBTextFieldAlertViewDelegate-Protocol.h"

@interface WBNetworkErrorHandler : NSObject <SNNetworkErrorHandler, WBTextFieldAlertViewDelegate>
{
}

+ (void)showErrorMessage:(id)arg1 withBlock:(id)arg2;
+ (void)showErrorMessage:(id)arg1;
+ (void)showError:(id)arg1 withBlock:(id)arg2;
+ (void)showError:(id)arg1;
+ (id)parseErrorFromError:(id)arg1 responseString:(id)arg2;
+ (id)bussinessErrorFromResponseObject:(id)arg1;
+ (id)handleError:(id)arg1 forWrapper:(id)arg2;
+ (id)sharedHandler;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)didPressCancelButtonInTextFieldAlertView:(id)arg1;
- (void)performDidCancelInCaptchaAlertView:(id)arg1;
- (void)didPressOkButtonInTextFieldAlertView:(id)arg1;
- (void)alertCaptchaWithErrorContext:(id)arg1;
- (void)alertErrorUrlWithErrorInfo:(id)arg1;

@end

