/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBStatus.h"

@class NSArray, NSString;

@interface WBNotice : WBStatus
{
    NSString *title;
}

@property(retain, nonatomic) NSString *title; // @synthesize title;
- (void)dealloc;
@property(readonly, nonatomic) NSArray *links;
- (BOOL)updateWithJSONDictionary:(id)arg1;

@end

