/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBUploader.h"

@class NSDate, NSMutableArray, NSString;

@interface WBPartUploader : WBUploader
{
    unsigned int _totalParts;
    unsigned long long _rangePerFile;
    unsigned long long _currentPartFileSize;
    NSDate *_uploadStartTime;
    NSString *_uploadKey;
    NSMutableArray *_partedFileMD5s;
    unsigned int _pointer;
}

- (void)upload;
- (void)prepareUpload;
- (id)partFilesDir;
- (void)_saveUploadingInfo:(id)arg1;
- (void)loadUploadingInfo;
- (void)_loadUploadingInfo:(id)arg1;
- (unsigned long long)getPartFileSize;
- (void)setProgress:(float)arg1;
- (id)oauthRequestWithURLString:(id)arg1;
- (void)dealloc;
- (id)initWithTask:(id)arg1;

@end

