/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBViewController.h"

#import "UIAlertViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WBPhotoDelegate-Protocol.h"

@class NSArray, NSMutableSet, NSTimer, UIBarButtonItem, UIScrollView, UIToolbar;

@interface WBPhotoViewController : WBViewController <UIScrollViewDelegate, WBPhotoDelegate, UIAlertViewDelegate>
{
    id <WBPhotoViewControllerDelegate> delegate;
    NSArray *photos;
    UIScrollView *pagingScrollView;
    NSMutableSet *visiblePages;
    NSMutableSet *recycledPages;
    unsigned int currentPageIndex;
    unsigned int pageIndexBeforeRotation;
    UIToolbar *toolbar;
    NSTimer *controlVisibilityTimer;
    UIBarButtonItem *previousButton;
    UIBarButtonItem *nextButton;
    BOOL performingLayout;
    BOOL rotating;
    int controllerMode;
    BOOL hadCloseButtonPressed;
}

@property(nonatomic) int controllerMode; // @synthesize controllerMode;
@property(nonatomic) id <WBPhotoViewControllerDelegate> delegate; // @synthesize delegate;
- (void)setInitialPageIndex:(unsigned int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)toggleControls;
- (void)hideControls;
- (void)hideControlsAfterDelay;
- (void)cancelControlHiding;
- (void)setControlsHidden:(BOOL)arg1;
- (void)gotoNextPage;
- (void)gotoPreviousPage;
- (void)jumpToPageAtIndex:(unsigned int)arg1;
- (void)updateNavigation;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGRect)frameForToolbarAtOrientation:(int)arg1;
- (struct CGRect)frameForNavigationBarAtOrientation:(int)arg1;
- (struct CGPoint)contentOffsetForPageAtIndex:(unsigned int)arg1;
- (struct CGSize)contentSizeForPagingScrollView;
- (struct CGRect)frameForPageAtIndex:(unsigned int)arg1;
- (struct CGRect)frameForPagingScrollView;
- (void)didStartViewingPageAtIndex:(unsigned int)arg1;
- (id)dequeueRecycledPage;
- (void)configurePage:(id)arg1 forIndex:(unsigned int)arg2;
- (id)pageDisplayedAtIndex:(unsigned int)arg1;
- (BOOL)isDisplayingPageForIndex:(unsigned int)arg1;
- (void)allocateNewPageWhenPhotoLoadedForPageAtIndex:(int)arg1;
- (void)tilePages;
- (void)photo:(id)arg1 didReceiveBytes:(long long)arg2 totalBytes:(long long)arg3 progress:(float)arg4;
- (void)photoDidFailToLoad:(id)arg1;
- (void)photoDidFinishLoading:(id)arg1;
- (id)photoAtIndex:(unsigned int)arg1;
- (void)performLayout;
- (void)selectImageButtonPressed:(id)arg1;
- (void)deleteImageButtonPressed:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveToCameralRollButtonPressed:(id)arg1;
- (void)closeButtonPressed:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (id)initWithPhotos:(id)arg1;

@end

