/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class UIImage;

@interface WBPieProgressView : UIView
{
    UIImage *backgroundImage;
    UIImage *foregroundImage;
    float progress;
}

@property(nonatomic) float progress; // @synthesize progress;
@property(retain, nonatomic) UIImage *foregroundImage; // @synthesize foregroundImage;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

