/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MKMapViewDelegate-Protocol.h"
#import "PRLMTableViewWrapperDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MKMapView, NSMutableArray, UIControl, WBPRLMTableViewWrapper, WBSearchBar, WBSpot, WBSpotEngine, WBTableView;

@interface WBPOIListViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UIScrollViewDelegate, MKMapViewDelegate, PRLMTableViewWrapperDelegate>
{
    WBSpotEngine *spotEngine;
    WBSpot *selectedSpot;
    BOOL hasSetLocation;
    MKMapView *mapView;
    NSMutableArray *annotations;
    WBTableView *spotsTableView;
    WBPRLMTableViewWrapper *spotsTableViewWrapper;
    WBTableView *searchTableView;
    WBPRLMTableViewWrapper *searchTableViewWrapper;
    WBSearchBar *searchBar;
    UIControl *overlayView;
    id <WBPOIListViewControllerDelegate> delegate;
}

@property(retain, nonatomic) WBSpot *selectedSpot; // @synthesize selectedSpot;
@property(retain, nonatomic) WBSpotEngine *spotEngine; // @synthesize spotEngine;
@property(nonatomic) id <WBPOIListViewControllerDelegate> delegate; // @synthesize delegate;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)updateMapViewAnnotationWithNewSpots:(id)arg1;
- (void)updateMapViewLocation;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)annotationForSpot:(id)arg1;
- (void)cancelSearching;
- (void)startSearching;
- (void)hideSearchingOverlay;
- (void)showSearchingOverlay;
- (void)overlayViewTouched:(id)arg1;
- (void)addSpotButtonPressed:(id)arg1;
- (void)dismissModalViewController;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSpotEngine:(id)arg1;

@end

