/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBPrivateMailTask.h"

#import "WBUploadTask-Protocol.h"

@class NSDictionary, NSString;

@interface WBPrivateMailWithFileTask : WBPrivateMailTask <WBUploadTask>
{
    NSString *_fid;
    NSString *_tofid;
    NSString *_dummyFid;
    NSString *_fname;
    NSString *_fdir;
    NSDictionary *_uploadResult;
    int _ftype;
    BOOL _keepFile;
    BOOL _isForward;
    unsigned int _failTimes;
}

+ (unsigned int)taskType;
@property(nonatomic) unsigned int failTimes; // @synthesize failTimes=_failTimes;
@property(nonatomic) BOOL isForward; // @synthesize isForward=_isForward;
@property(nonatomic) BOOL keepFile; // @synthesize keepFile=_keepFile;
@property(nonatomic) int ftype; // @synthesize ftype=_ftype;
@property(retain, nonatomic) NSDictionary *uploadResult; // @synthesize uploadResult=_uploadResult;
@property(retain, nonatomic) NSString *dummyFid; // @synthesize dummyFid=_dummyFid;
@property(retain, nonatomic) NSString *fdir; // @synthesize fdir=_fdir;
@property(retain, nonatomic) NSString *tofid; // @synthesize tofid=_tofid;
@property(retain, nonatomic) NSString *fid; // @synthesize fid=_fid;
@property(retain, nonatomic) NSString *fname; // @synthesize fname=_fname;
- (void)increaseFailTimes:(unsigned int)arg1;
- (void)taskDidRemoveFromQueue;
- (id)fpath;
- (id)partedFilesTempDir;
- (void)loadFromRS:(id)arg1;
- (BOOL)updateDB:(id)arg1;
- (BOOL)insertIntoDB:(id)arg1;
- (void)dealloc;
- (id)content;
- (id)toBeSentFid;
- (id)init;

@end

