/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBProgressSheetDelegate <NSObject>

@optional
- (void)progressSheetDidCancel:(id)arg1;
- (void)progressSheetWillCancel:(id)arg1;
- (BOOL)progressSheetShouldCancel:(id)arg1;
- (void)progressSheetDidDismiss:(id)arg1;
- (void)progressSheetWillDismiss:(id)arg1;
- (void)didPresentProgressSheet:(id)arg1;
- (void)willPresentProgressSheet:(id)arg1;
@end

