/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PRLMTableViewWrapper.h"

#import "WBAppLanguageObserver-Protocol.h"
#import "WBSkinning-Protocol.h"

@interface WBPRLMTableViewWrapper : PRLMTableViewWrapper <WBSkinning, WBAppLanguageObserver>
{
}

- (void)dealloc;
- (void)appLanguageDidChange:(id)arg1;
- (void)playSoundForAction:(int)arg1;
- (id)footerView;
- (id)headerView;
- (void)reloadUIElements;
- (id)init;
- (void)currentSkinDidChangeNotification:(id)arg1;

@end

