/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTimerAPIAccessor.h"

@interface WBPrivateMailAPIAccessor : WBTimerAPIAccessor
{
}

+ (unsigned int)taskType;
- (BOOL)asyncExecuteTask;
- (void)dealResponseInfo:(id)arg1;
- (id)initWithTaskQueue:(id)arg1;

@end

