/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBStatusBusinessEngine.h"

@class SNHTTPRequestOperationWrapper;

@interface WBRepostEngine : WBStatusBusinessEngine
{
    SNHTTPRequestOperationWrapper *deleteRequestOperationWrapper;
}

- (void)cancelDeleteStatus;
- (void)deleteStatus:(id)arg1 completionHandler:(id)arg2;
- (void)fetchDataWithCompletionHandler:(id)arg1;
- (void)dealloc;

@end

