/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTableViewCell.h"

@class UIImageView, UILabel, WBContactAvatarView, WBUserScreenNameLabel;

@interface WBRepostListTableViewCell : WBTableViewCell
{
    WBContactAvatarView *avatarView;
    WBUserScreenNameLabel *screenNameLabel;
    UILabel *timeLabel;
    UILabel *contentLabel;
    UIImageView *separatorImageView;
    id <WBRepostListTableViewCellDelegate> delegate;
}

+ (float)rowHeightOfStatus:(id)arg1;
+ (id)contentOfStatus:(id)arg1;
@property(nonatomic) id <WBRepostListTableViewCellDelegate> delegate; // @synthesize delegate;
- (void)setStatus:(id)arg1;
- (void)layoutSubviews;
- (void)avatarViewPressed:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

