/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIControl.h"

#import "WBSkinning-Protocol.h"

@class NSArray, NSMutableArray, UIImage, UIImageView;

@interface WBSegmentedControl : UIControl <WBSkinning>
{
    UIImageView *backgroundView;
    NSMutableArray *segmentButtons;
    NSMutableArray *segments;
    struct UIEdgeInsets segmentEdgeInsets;
    UIImage *normalImageLeft;
    UIImage *normalImageMiddle;
    UIImage *normalImageRight;
    UIImage *selectedImageLeft;
    UIImage *selectedImageMiddle;
    UIImage *selectedImageRight;
    unsigned int numberOfSegments;
    int selectedSegmentIndex;
    int lastSelectedSegmentIndex;
    BOOL programmaticIndexChange;
    BOOL momentary;
    unsigned int selectionControlEvent;
    id configSegmentButtonBlock;
}

@property(retain, nonatomic) UIImage *selectedImageRight; // @synthesize selectedImageRight;
@property(retain, nonatomic) UIImage *selectedImageMiddle; // @synthesize selectedImageMiddle;
@property(retain, nonatomic) UIImage *selectedImageLeft; // @synthesize selectedImageLeft;
@property(retain, nonatomic) UIImage *normalImageRight; // @synthesize normalImageRight;
@property(retain, nonatomic) UIImage *normalImageMiddle; // @synthesize normalImageMiddle;
@property(retain, nonatomic) UIImage *normalImageLeft; // @synthesize normalImageLeft;
@property(nonatomic) struct UIEdgeInsets segmentEdgeInsets; // @synthesize segmentEdgeInsets;
@property(nonatomic) unsigned int selectionControlEvent; // @synthesize selectionControlEvent;
@property(nonatomic, getter=isMomentary) BOOL momentary; // @synthesize momentary;
@property(readonly, nonatomic) int lastSelectedSegmentIndex; // @synthesize lastSelectedSegmentIndex;
@property(nonatomic) int selectedSegmentIndex; // @synthesize selectedSegmentIndex;
@property(readonly, nonatomic) unsigned int numberOfSegments; // @synthesize numberOfSegments;
@property(readonly, nonatomic) NSArray *segmentButtons; // @synthesize segmentButtons;
@property(copy, nonatomic) NSArray *segments; // @synthesize segments;
@property(readonly, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (id)imageForSegmentAtIndex:(unsigned int)arg1;
- (id)titleForSegmentAtIndex:(unsigned int)arg1;
- (void)setImage:(id)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (void)setTitle:(id)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (void)removeAllSegments;
- (void)removeSegmentAtIndex:(unsigned int)arg1;
- (void)insertSegmentWithImage:(id)arg1 atIndex:(unsigned int)arg2;
- (void)insertSegmentWithTitle:(id)arg1 atIndex:(unsigned int)arg2;
- (void)setObject:(id)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (void)insertSegmentWithObject:(id)arg1 atIndex:(unsigned int)arg2;
- (void)segmentTapped:(id)arg1;
- (void)resetSegments;
- (void)deselectAllSegments;
- (void)updateUI;
- (void)updateButtonBackgroundImages;
- (void)reloadUIElements;
- (id)initWithCoder:(id)arg1;
- (id)initWithItems:(id)arg1 configSegmentButtonBlock:(id)arg2;
- (id)initWithItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setup;

@end

