/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSCache, NSMutableArray, WBSkin;

@interface WBSkinManager : NSObject
{
    NSMutableArray *skins;
    WBSkin *currentSkin;
    NSCache *imageCache;
    NSCache *colorCache;
}

+ (id)currentSkin;
+ (id)sharedManager;
@property(retain, nonatomic) WBSkin *currentSkin; // @synthesize currentSkin;
@property(retain, nonatomic) NSArray *skins; // @synthesize skins;
- (void)notifyBubbleSkinBackgroundChange;
- (id)bubbleSkinBackgroundImage;
- (void)useDefaultBubbleBackgroundImage;
- (id)cachedColorForKey:(id)arg1;
- (void)cacheColor:(id)arg1 forKey:(id)arg2;
- (void)removeCachedImageForKey:(id)arg1;
- (id)cachedImageForKey:(id)arg1;
- (void)cacheImage:(id)arg1 forKey:(id)arg2;
- (void)setupCaches;
- (BOOL)removeSkinFromLocalWithSkin:(id)arg1;
- (id)defaultBubbleSkin;
- (id)defaultSkin;
- (id)skinByID:(id)arg1;
- (BOOL)applySkin:(id)arg1;
- (void)upgradeSkin:(id)arg1;
- (void)downloadSkin:(id)arg1;
- (void)updateSkins;
- (void)loadSkinsFromLocal;
- (void)scanSkinStates;
- (void)dealloc;
- (id)init;

@end

