/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CLLocation, SNHTTPRequestOperationWrapper, WBResultSet;

@interface WBSpotEngine : NSObject
{
    CLLocation *location;
    BOOL locationOffset;
    WBResultSet *spotsResultSet;
    WBResultSet *searchedSpotsResultSet;
    WBResultSet *showingSpotsResultSet;
    SNHTTPRequestOperationWrapper *fetchSpotsRequestWrapper;
    SNHTTPRequestOperationWrapper *searchSpotsRequestWrapper;
    BOOL cancelled;
}

+ (id)spotEngineWithLocation:(id)arg1;
@property(retain, nonatomic) WBResultSet *showingSpotsResultSet; // @synthesize showingSpotsResultSet;
@property(retain, nonatomic) WBResultSet *searchedSpotsResultSet; // @synthesize searchedSpotsResultSet;
@property(retain, nonatomic) WBResultSet *spotsResultSet; // @synthesize spotsResultSet;
@property(nonatomic) BOOL locationOffset; // @synthesize locationOffset;
@property(retain, nonatomic) CLLocation *location; // @synthesize location;
- (void)cancelLoading;
- (void)searchMoreSpotsWithCompletionHandler:(id)arg1;
- (void)searchSpotsWithKeyword:(id)arg1 completionHandler:(id)arg2;
- (void)searchSpotsWithCompletionHandler:(id)arg1;
- (void)updateMoreSpotsWithCompletionHandler:(id)arg1;
- (void)updateSpotsWithCompletionHandler:(id)arg1;
- (void)fetchSpotsWithCompletionHandler:(id)arg1;
- (void)dealloc;
- (id)initWithLocation:(id)arg1;
- (id)init;

@end

