/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTimelineTableViewCellDrawingContext.h"

@interface WBStatusTableViewCellDrawingContext : WBTimelineTableViewCellDrawingContext
{
}

- (id)availableThumbnailImageURL;
- (id)availableMiddleImageURL;
- (BOOL)hasLocation;
- (BOOL)showsSource;
- (BOOL)quotedItemHasPhoto;
- (BOOL)itemHasPhoto;
- (id)status;
- (void)generateBriefQuotedItemText;
- (void)generateBriefItemText;
- (void)resetWithContentWidth:(float)arg1;
- (id)flagImageUrl;

@end

