/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBTimelineTableViewCell.h"

@class UIImageView, UILabel;

@interface WBStatusTableViewCell : WBTimelineTableViewCell
{
    BOOL shouldMaskImages;
    UIImageView *keepTopImageView;
    UILabel *keepTopLabel;
}

+ (id)createDrawingContextForTimelineItem:(id)arg1;
+ (struct _TimelineCellContentMeasures)contentMeasuresOfDrawingContext:(id)arg1;
+ (void)initialize;
- (void)didPressPhotoImageView:(id)arg1;
- (void)renderExtraUIElementsWithContentMeasures:(struct _TimelineCellContentMeasures)arg1;

@end

