/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBTapImageViewDelegate <NSObject>

@optional
- (void)imageView:(id)arg1 tripleTapDetected:(id)arg2;
- (void)imageView:(id)arg1 doubleTapDetected:(id)arg2;
- (void)imageView:(id)arg1 singleTapDetected:(id)arg2;
@end

