/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITabBar.h"

#import "WBTabBarOverlayDelegate-Protocol.h"

@class WBTabBarOverlay;

@interface WBTabBar : UITabBar <WBTabBarOverlayDelegate>
{
    WBTabBarOverlay *tabBarOverlay;
}

@property(readonly, nonatomic) WBTabBarOverlay *tabBarOverlay; // @synthesize tabBarOverlay;
- (void)dealloc;
- (void)tabBarOverlay:(id)arg1 didSelectTabAtIndex:(unsigned int)arg2;
- (void)setItems:(id)arg1 animated:(BOOL)arg2;
- (void)setSelectedItem:(id)arg1;
- (void)setupTabBarOverlay;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

