/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSMutableSet, WBWorker;

@interface WBTask : NSObject
{
    WBWorker *_owner;
    unsigned long long _id;
    unsigned int _type;
    int _state;
    NSDate *_time;
    float _progress;
    NSMutableSet *_delegates;
}

+ (unsigned int)taskType;
@property(readonly, nonatomic) NSMutableSet *delegates; // @synthesize delegates=_delegates;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(retain, nonatomic) NSDate *time; // @synthesize time=_time;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) unsigned long long taskId; // @synthesize taskId=_id;
@property(nonatomic) WBWorker *owner; // @synthesize owner=_owner;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)taskDidRemoveFromQueue;
- (void)notifyDelegate:(SEL)arg1;
- (void)notifyTaskStateDidChange;
- (void)notifyTaskProgressDidChange;
- (void)notifyTaskDidRemove;
- (void)dealloc;
- (id)init;

@end

