/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol WBTaskInSqlite
- (void)loadFromRS:(id)arg1;
- (BOOL)deleteFromDB:(id)arg1;
- (BOOL)updateDB:(id)arg1;
- (BOOL)insertIntoDB:(id)arg1;
@end

