/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@interface WBTapView : UIView
{
    id <WBTapViewDelegate> tapDelegate;
}

@property(nonatomic) id <WBTapViewDelegate> tapDelegate; // @synthesize tapDelegate;
- (void)handleTripleTap:(id)arg1;
- (void)handleDoubleTap:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

