/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, WBFeedGroup, WBHTTPRequestOperationWrapper, WBResultSet;

@interface WBTimelineManager : NSObject
{
    WBResultSet *resultSet;
    WBFeedGroup *currentGroup;
    NSDate *lastUpdateTime;
    unsigned int newStatusCount;
    id loadNearbyStatusesCompletionHandler;
    BOOL loading;
    WBHTTPRequestOperationWrapper *wrapper;
}

@property(readonly, nonatomic) BOOL loading; // @synthesize loading;
@property(readonly, nonatomic) unsigned int newStatusCount; // @synthesize newStatusCount;
@property(readonly, nonatomic) WBResultSet *resultSet; // @synthesize resultSet;
@property(readonly, nonatomic) WBFeedGroup *currentGroup; // @synthesize currentGroup;
- (void)loadMoreStatuses:(id)arg1 completionHandler:(id)arg2;
- (void)loadStatuses:(id)arg1 withLoadTimelineParams:(id)arg2 completionHandler:(id)arg3;
- (void)cancelLoading;
- (void)loadMoreFeedStatuses:(id)arg1;
- (void)loadFeedStatuses:(id)arg1 withLoadTimelineParams:(id)arg2 completionHandler:(id)arg3;
- (void)_loadFeedStatuses:(id)arg1 newerThenID:(id)arg2 olderThenID:(id)arg3 withLoadTimelineParams:(id)arg4 completion:(id)arg5;
- (void)locationManagerDidFailToLocateNotification:(id)arg1;
- (void)locationManagerDidFinishLocatingNotification:(id)arg1;
- (void)loadMoreNearbyStatuses:(id)arg1;
- (void)loadNearbyStatuses:(id)arg1;
- (void)_loadNearbyStatusesAtPage:(unsigned int)arg1 count:(unsigned int)arg2 location:(id)arg3 completion:(id)arg4;
- (void)loadMoreMyStatuses:(id)arg1;
- (void)loadMyStatuses:(id)arg1;
- (void)_loadMyStatusesAtPage:(unsigned int)arg1 count:(unsigned int)arg2 completion:(id)arg3;
- (void)loadMoreAllStatuses:(id)arg1;
- (void)loadAllStatuses:(id)arg1 completionHandler:(id)arg2;
- (void)loadAllStatusesFromLocal:(id)arg1;
- (void)_loadAllStatusesOlderThan:(id)arg1 andNewerThan:(id)arg2 count:(int)arg3 withLoadTimelineParams:(id)arg4 completion:(id)arg5;
- (void)saveContacts:(id)arg1 orContactsFomStatuses:(id)arg2 toGroup:(id)arg3;
- (void)resetGroupIfNeeded:(id)arg1;
- (void)resetWithNewAccount;
- (void)resetSpecialStatusesAsNormalWithType:(id)arg1;
- (void)checkAndAssureStatusesSizeWithType:(id)arg1;
- (void)saveDictStatuses:(id)arg1 withType:(id)arg2 shouldRemoveHistory:(BOOL)arg3;
- (void)deleteAllStatusesWithType:(id)arg1;
- (id)getMaxStatusIDForType:(id)arg1;
- (id)getStatusesAtPage:(int)arg1 lastUpdateTime:(id)arg2 type:(id)arg3;
- (id)getTotalCountAndMinStatusedIDBetweenMin:(id)arg1 max:(id)arg2 type:(id)arg3;
- (id)db;
- (void)dealloc;
- (id)init;

@end

