/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBWebViewController.h"

@class UIBarButtonItem;

@interface WBTopNavigationWebViewController : WBWebViewController
{
    UIBarButtonItem *navigationBarSpinnerButtonItem;
    UIBarButtonItem *navigationBarRefreshButtonItem;
}

- (void)handlePanGesture:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (void)layout:(BOOL)arg1;
- (void)updateControls;
- (void)leftBarButtonPressed:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

