/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBContact.h"

@class NSArray, NSString;

@interface WBUser : WBContact
{
    unsigned int gender;
    NSString *desc;
    NSString *domain;
    unsigned int followersCount;
    unsigned int followingCount;
    unsigned int friendsCount;
    unsigned int favoritesCount;
    unsigned int statusesCount;
    unsigned int topicsCount;
    NSString *province;
    NSString *city;
    NSString *verifiedReason;
    NSString *lastStatusContent;
    unsigned int possiblyKnownType;
    NSString *possiblyKnownReason;
    int membershipType;
    NSString *eventIconURL;
    int enterpriseAppCount;
    NSString *enterpriseAppsURL;
    NSString *weihao;
    NSArray *medals;
}

+ (id)userWithUserID:(id)arg1;
+ (id)objectWithCommentJSONDictionary:(id)arg1;
+ (id)blockedUsersWithJSONArray:(id)arg1;
+ (int)membershipTypeOfValue:(id)arg1;
@property(retain, nonatomic) NSArray *medals; // @synthesize medals;
@property(retain, nonatomic) NSString *weihao; // @synthesize weihao;
@property(retain, nonatomic) NSString *enterpriseAppsURL; // @synthesize enterpriseAppsURL;
@property(nonatomic) int enterpriseAppCount; // @synthesize enterpriseAppCount;
@property(retain, nonatomic) NSString *eventIconURL; // @synthesize eventIconURL;
@property(nonatomic) int membershipType; // @synthesize membershipType;
@property(retain, nonatomic) NSString *possiblyKnownReason; // @synthesize possiblyKnownReason;
@property(nonatomic) unsigned int possiblyKnownType; // @synthesize possiblyKnownType;
@property(retain, nonatomic) NSString *lastStatusContent; // @synthesize lastStatusContent;
@property(retain, nonatomic) NSString *verifiedReason; // @synthesize verifiedReason;
@property(retain, nonatomic) NSString *city; // @synthesize city;
@property(retain, nonatomic) NSString *province; // @synthesize province;
@property(nonatomic) unsigned int topicsCount; // @synthesize topicsCount;
@property(nonatomic) unsigned int statusesCount; // @synthesize statusesCount;
@property(nonatomic) unsigned int favoritesCount; // @synthesize favoritesCount;
@property(nonatomic) unsigned int friendsCount; // @synthesize friendsCount;
@property(nonatomic) unsigned int followingCount; // @synthesize followingCount;
@property(nonatomic) unsigned int followersCount; // @synthesize followersCount;
@property(retain, nonatomic) NSString *domain; // @synthesize domain;
@property(retain, nonatomic) NSString *desc; // @synthesize desc;
@property(nonatomic) unsigned int gender; // @synthesize gender;
- (void)dealloc;
- (BOOL)updateWithDictionary:(id)arg1;
- (BOOL)updateWithJSONDictionary:(id)arg1;
@property(readonly, nonatomic) NSString *availableEnterpriseAppsURL;

@end

