/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "WBSkinning-Protocol.h"

@class WBBadgeView, WBUserProfileUserDataButton;

@interface WBUserProfileUserDataCellView : UIView <WBSkinning>
{
    WBUserProfileUserDataButton *followingsButton;
    WBUserProfileUserDataButton *statusesButton;
    WBUserProfileUserDataButton *followersButton;
    WBUserProfileUserDataButton *trendsButton;
    WBBadgeView *followersBadgeView;
}

@property(readonly, nonatomic) WBBadgeView *followersBadgeView; // @synthesize followersBadgeView;
@property(readonly, nonatomic) WBUserProfileUserDataButton *trendsButton; // @synthesize trendsButton;
@property(readonly, nonatomic) WBUserProfileUserDataButton *followersButton; // @synthesize followersButton;
@property(readonly, nonatomic) WBUserProfileUserDataButton *statusesButton; // @synthesize statusesButton;
@property(readonly, nonatomic) WBUserProfileUserDataButton *followingsButton; // @synthesize followingsButton;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)reloadUIElements;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

