/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBModelObject.h"

@interface WBUserSettingsModel : WBModelObject
{
    unsigned int displayNameType;
    unsigned int browseMode;
    unsigned int timelineDisplayMode;
    unsigned int textFontSize;
    BOOL showBriefStatus;
    unsigned int uploadImageQuality;
    BOOL enablesSmartUploadImageQuaility;
    unsigned int _version;
}

+ (id)modelWithModel:(id)arg1;
@property(nonatomic) BOOL enablesSmartUploadImageQuaility; // @synthesize enablesSmartUploadImageQuaility;
@property(nonatomic) unsigned int uploadImageQuality; // @synthesize uploadImageQuality;
@property(nonatomic) BOOL showBriefStatus; // @synthesize showBriefStatus;
@property(nonatomic) unsigned int textFontSize; // @synthesize textFontSize;
@property(nonatomic) unsigned int timelineDisplayMode; // @synthesize timelineDisplayMode;
@property(nonatomic) unsigned int browseMode; // @synthesize browseMode;
@property(nonatomic) unsigned int displayNameType; // @synthesize displayNameType;
- (BOOL)isEqual:(id)arg1;
- (id)stringValue;
- (void)resetVersionWithNewVersion:(unsigned int)arg1;
- (void)resetVersion;
- (unsigned int)version;

@end

