/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIButton.h"

@interface WBUserRelationshipButton : UIButton
{
    unsigned int relationshipState;
    unsigned int indicatorType;
    unsigned int relationship;
    BOOL showsIndicator;
}

@property(nonatomic) BOOL showsIndicator; // @synthesize showsIndicator;
@property(nonatomic) unsigned int relationship; // @synthesize relationship;
@property(readonly, nonatomic) unsigned int relationshipState; // @synthesize relationshipState;
- (id)initWithFrame:(struct CGRect)arg1;

@end

