/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBModelObject.h"

@class NSString;

@interface WBUserMedal : WBModelObject
{
    NSString *medalID;
    NSString *name;
    NSString *iconUrl;
}

@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *medalID; // @synthesize medalID;
- (BOOL)updateWithJSONDictionary:(id)arg1;
- (void)dealloc;

@end

