/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WBAccessoryLabel.h"

@class UIImageView, WBContentImageView, WBUser;

@interface WBUserScreenNameLabel : WBAccessoryLabel
{
    WBUser *user;
    UIImageView *membershipIconImageView;
    WBContentImageView *eventIconImageView;
}

@property(retain, nonatomic) WBUser *user; // @synthesize user;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

