/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

@class UIImageView;

@interface WBViewController : UIViewController
{
    unsigned int viewControllerState;
    UIImageView *backgroundImageView;
}

@property(nonatomic) unsigned int viewControllerState; // @synthesize viewControllerState;
- (void)dealloc;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView;
- (void)cancelAction:(id)arg1;
- (void)viewDidUnload;
- (void)viewWillUnload;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)awakeFromNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)addCustomBackBarButtonItemWithTarget:(id)arg1 action:(SEL)arg2;
- (void)addDefaultBackBarButtonItem;
- (void)skinTimelineTableView:(id)arg1;
- (void)skinMainTableView:(id)arg1;

@end

