/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class FMDatabase;

@interface WeiboDao : NSObject
{
    FMDatabase *db;
}

@property(retain, nonatomic) FMDatabase *db; // @synthesize db;
- (void)updataLastTimeForHotwordTitle:(id)arg1 Time:(int)arg2;
- (void)saveAryToHotword:(id)arg1;
- (id)getLastTimeHotword;
- (id)getHotwordData;
- (void)insertToHotword:(id)arg1;
- (void)checkAndAssureHotwordSize;
- (int)getRepeatTitleHotword:(id)arg1;
- (void)clearTable:(id)arg1;
- (unsigned char)tableHasData:(id)arg1;
- (void)dealloc;
- (id)getExtraInfoValueForKey:(id)arg1;
- (void)setExtraInfoValue:(id)arg1 forKey:(id)arg2;
- (id)getCommentsAtPage:(int)arg1 pageCount:(int)arg2 type:(id)arg3;
- (id)getStatusesAtPage:(int)arg1 pageCount:(int)arg2 lastUpdateTime:(id)arg3 type:(id)arg4;
- (void)deleteComment:(id)arg1 type:(id)arg2;
- (void)deleteStatus:(id)arg1 type:(id)arg2;
- (id)initWithDbFullPath:(id)arg1;

@end

