/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "AdViewDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSMutableArray, NSTimer;

@interface AdManager : NSObject <AdViewDelegate>
{
    MGTwitterEngine_WeiboV4 *_engine;
    NSMutableArray *_adsArray;
    BOOL _busy;
    NSTimer *_loadServerAdsTimer;
    NSTimer *_presentAdsTimer;
    NSTimer *_presentAdTimer;
    id <AdManagerDelegate> _delegate;
}

+ (void)clearCachedClosedAds;
+ (void)clearCachedAds;
+ (void)clearAllCachedAds;
+ (id)sharedInstance;
@property(readonly, nonatomic) BOOL isBusy; // @synthesize isBusy=_busy;
@property(nonatomic) id <AdManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)adViewClosed:(id)arg1;
- (void)adViewTouched:(id)arg1;
- (void)presentNextAd;
- (void)stopPresenting;
- (void)startNewPresenting;
- (void)startPresenting;
- (void)GetAdvertisementReceived:(id)arg1;
- (void)loadServerAds;
- (void)terminateAdsPresent;
- (void)scheduleAdsPresent;
- (void)filterAds:(id)arg1;
- (void)dealloc;
- (id)init;

@end

