/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSTimer, UIActivityIndicatorView, UIImageView, UILabel;

@interface AlterErrorShowView : UIView
{
    UILabel *lblLogin;
    UIImageView *imgSign;
    UIActivityIndicatorView *_indicator;
    NSTimer *loaderQueueTimer;
}

+ (id)sharedManager:(BOOL)arg1;
@property(retain, nonatomic) NSTimer *loaderQueueTimer; // @synthesize loaderQueueTimer;
- (void)dealloc;
- (void)setAlterLoad:(id)arg1;
- (void)setAlterContent:(id)arg1 imageName:(id)arg2;
- (void)selfRemoveFromSuperviewEnd;
- (void)selfRemoveFromSuperview;
- (void)setCalculagraphBegin;
- (void)loginReceived;
- (id)initWithFrame:(struct CGRect)arg1;

@end

