/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "UIScrollViewDelegate-Protocol.h"

@class MGTwitterEngine_Weibo, MGTwitterEngine_WeiboV4, NSDictionary, NSMutableArray, UIPageControl, UIScrollView;

@interface ChannelView : UIView <UIScrollViewDelegate>
{
    UIScrollView *scrollView;
    MGTwitterEngine_Weibo *_engineWeibo;
    MGTwitterEngine_WeiboV4 *_engineV4;
    id delegate;
    NSMutableArray *channelsMArray;
    UIPageControl *pageControl;
    NSMutableArray *backImageArray;
    NSMutableArray *titleLbArray;
    NSDictionary *selectedChannelInfoDict;
}

@property(retain, nonatomic) NSDictionary *selectedChannelInfoDict; // @synthesize selectedChannelInfoDict;
@property(nonatomic) id delegate; // @synthesize delegate;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)searchGridReceived:(id)arg1 forRequest:(id)arg2;
- (void)channelListReceived:(id)arg1;
- (void)dealloc;
- (void)channelTouched:(id)arg1 close:(BOOL)arg2;
- (void)makeScrollView:(id)arg1;
- (void)loadScrollView;
- (void)loadChannels;
- (id)initWithFrame:(struct CGRect)arg1;

@end

