/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class BadgeView, CommentsToMeViewController, CommentsViewController, NewHomelineViewController, UIButton, UIImageView, UILabel;

@interface CommentsContainerViewController : UIViewController <TimeLineTab, UIActionSheetDelegate>
{
    CommentsViewController *commentsByMeVC;
    CommentsToMeViewController *commentsToMeVC;
    id <TimeLineTab> currentTab;
    UIButton *bymeBtn;
    UIButton *tomeBtn;
    UIButton *filterBtn;
    UIImageView *bgImageView;
    UIImageView *tabImage;
    UIImageView *bymeBtnImage;
    UIImageView *tomeBtnImage;
    UIImageView *filterBtnImage;
    UIImageView *arrowImage;
    UILabel *filterLabel;
    NewHomelineViewController *myDetailView;
    BadgeView *cmtBadgeView;
}

@property(nonatomic) NewHomelineViewController *myDetailView; // @synthesize myDetailView;
@property(nonatomic) id <TimeLineTab> currentTab; // @synthesize currentTab;
@property(nonatomic) CommentsToMeViewController *commentsToMeVC; // @synthesize commentsToMeVC;
@property(nonatomic) CommentsViewController *commentsByMeVC; // @synthesize commentsByMeVC;
- (void)languageChanged:(id)arg1;
- (void)skinChanged:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)setBadgeCount;
- (void)filterBtnClicked;
- (void)tomeClicked;
- (void)bymeClicked;
- (void)refresh;
- (void)onLogout;
- (void)onRotated;
- (void)onBringToFront;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)refreshSkin;
- (void)viewDidLoad;

@end

