/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "DisplayExpressionDelegate-Protocol.h"
#import "InsertTopicDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"
#import "UserFinderDelegate-Protocol.h"

@class AtPersonToMesViewController, ExpressionViewContrller, MGTwitterEngine_WeiboV4, NSDictionary, SSTextView, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIImageView, UILabel, UIPopoverController, UIToolbar, UIView;

@interface CommentWeiboViewController : UIViewController <UITextViewDelegate, UIActionSheetDelegate, UIPopoverControllerDelegate, UserFinderDelegate, DisplayExpressionDelegate, InsertTopicDelegate>
{
    MGTwitterEngine_WeiboV4 *_engine;
    SSTextView *_textContent;
    NSDictionary *weiboInfo;
    UILabel *wordCountLabel;
    UIBarButtonItem *barItemSend;
    UIBarButtonItem *barItemLoad;
    UIActivityIndicatorView *sendActivity;
    UIToolbar *toolbar;
    BOOL titleStatus;
    BOOL isReplyComment;
    BOOL isRepost;
    UIButton *sendWeiboBtn;
    UIButton *isCommentBtn;
    UILabel *replyLabel;
    UILabel *titleLb;
    UIPopoverController *atpopoverController;
    UIPopoverController *topicPopoverController;
    struct _NSRange selectedRange;
    ExpressionViewContrller *expressionView;
    UIView *baseView;
    struct _NSRange topicRange;
    struct _NSRange topicEndRange;
    struct _NSRange atRange;
    struct _NSRange atEndRange;
    BOOL isTopicPopOn;
    BOOL sending;
    AtPersonToMesViewController *mAtPersonToMesViewController;
    UIImageView *comWeiboBg;
    UIView *clearTextView;
    UIView *controlView;
    BOOL showFace;
    UIImageView *clearImageView;
    UIButton *clearButton;
    UIButton *faceButton;
    BOOL isKeyboardUp;
}

@property(nonatomic) BOOL isReplyComment; // @synthesize isReplyComment;
@property(nonatomic) BOOL titleStatus; // @synthesize titleStatus;
@property(retain, nonatomic) NSDictionary *weiboInfo; // @synthesize weiboInfo;
- (void)backspaceTouched;
- (void)onInsertTopic:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)DisplayWord:(id)arg1;
- (void)onUsersFoundNick:(id)arg1 Uid:(id)arg2;
- (void)callTopicList:(id)arg1;
- (void)callAtList:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)onSaveTouched:(id)arg1;
- (void)onCancelTouched:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)saveTextToFile:(BOOL)arg1;
- (void)readTextFromFile;
- (void)textLengthCount;
- (void)closeMenu:(id)arg1;
- (void)popMenu:(id)arg1;
- (void)isCommentBtnTouched:(id)arg1;
- (void)showAtView:(id)arg1;
- (void)showFaceView;
- (void)insertTopic:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)rotateViewController:(int)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)keyboardFrameChanged:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;
- (void)initContentAndFooter;
- (void)initToolbar;

@end

