/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WeiBoCoreTextViewDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimer, NewHomelineViewController, TableRefreshHeaderView, UIActivityIndicatorView, UITableView;

@interface CommentsToMeViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TimeLineTab, WeiBoCoreTextViewDelegate>
{
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engineV4;
    NSMutableArray *_items;
    unsigned char orientionChanged;
    unsigned char verifiedStatus;
    unsigned char loadOlder;
    unsigned char loadingData;
    unsigned char selectStatus;
    UIActivityIndicatorView *moreActivity;
    NewHomelineViewController *myDetailView;
    TableRefreshHeaderView *refreshHeaderView;
    NSMutableDictionary *comNumberDictionary;
    NSDictionary *selectedWeibo;
    BOOL noOlderWeibo;
    BOOL showMessage;
    int loadingTime;
    NSString *selectedLink;
    NSTimer *loadTimer;
    BOOL filterByAuthor;
    int m_commentPage;
    long long maxId;
}

@property(nonatomic) BOOL filterByAuthor; // @synthesize filterByAuthor;
@property(retain, nonatomic) NSString *selectedLink; // @synthesize selectedLink;
@property(nonatomic) unsigned char selectStatus; // @synthesize selectStatus;
@property(retain, nonatomic) TableRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(retain, nonatomic) NSDictionary *selectedWeibo; // @synthesize selectedWeibo;
@property(retain, nonatomic) NewHomelineViewController *myDetailView; // @synthesize myDetailView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
- (void)weiBoCoreTextViewTouchedAttributedInfo:(id)arg1 index:(int)arg2 tag:(int)arg3;
- (void)thirdViewControllerClosed;
- (void)languageChanged:(id)arg1;
- (void)ChangeUser;
- (void)changeSelectCellBackColor:(int)arg1 cellDic:(id)arg2 isButton:(BOOL)arg3;
- (void)skinChanged:(id)arg1;
- (void)fontSizeChanged:(id)arg1;
- (void)weiboDeleteDidFinished:(id)arg1;
- (void)CommentDeleted:(id)arg1;
- (void)onWeiboCommentTouched:(id)arg1;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)finishLoadingNewData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showLoadingHeader;
- (void)createHeaderView;
- (void)onLogout;
- (void)onBringToFront;
- (void)onRotated;
- (void)refresh;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)rtCommentNumbersReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)recountCoreTextViewHeight;
- (void)clearItems;
- (void)updateRtCommentNumberOfWeibos:(id)arg1;
- (void)loadNewWeibo;
- (void)loadMoreWeibo;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)loadTimeOut;
- (void)releaseTimer;
- (void)refreshSkin;
- (void)viewDidLoad;

@end

