/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface DraftBox : NSObject
{
    NSMutableArray *_draftArray;
    int _draftCount;
}

+ (id)defaultBox;
@property(nonatomic) int draftCount; // @synthesize draftCount=_draftCount;
@property(retain, nonatomic) NSMutableArray *draftArray; // @synthesize draftArray=_draftArray;
- (id)removeEditorForDictionary:(id)arg1;
- (void)clearDraftBox;
- (void)deleteDraft:(id)arg1;
- (void)updateDraft:(id)arg1 withNewDraft:(id)arg2;
- (void)addDraft:(id)arg1;
- (void)dealloc;
- (id)init;

@end

