/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ExpressionDelegate <NSObject>
- (void)moveFace:(id)arg1;
- (void)hiddenDentialView:(id)arg1;
- (void)DentailView:(id)arg1;
@end

