/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DetailContainerViewController, MGTwitterEngine, NSMutableArray, NSMutableDictionary, TableRefreshHeaderView, UIActivityIndicatorView, UITableView;

@interface FavTimelineViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TimeLineTab, UIActionSheetDelegate>
{
    UITableView *mainTableView;
    MGTwitterEngine *_engine;
    NSMutableArray *_items;
    NSMutableArray *reportArray;
    int pageNo;
    unsigned char orientionChanged;
    unsigned char verifiedStatus;
    unsigned char reportStatus;
    unsigned char favStatus;
    unsigned char loadingData;
    UIActivityIndicatorView *moreActivity;
    DetailContainerViewController *myDetailView;
    TableRefreshHeaderView *refreshHeaderView;
    NSMutableDictionary *comNumberDictionary;
}

@property(retain, nonatomic) TableRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(retain, nonatomic) DetailContainerViewController *myDetailView; // @synthesize myDetailView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)onWeiboMoreActionTouched:(id)arg1;
- (void)onWeiboForwardTouched:(id)arg1;
- (void)onWeiboCommentTouched:(id)arg1;
- (void)finishLoadingNewData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showLoadingHeader;
- (void)createHeaderView;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)onLogout;
- (void)onBringToFront;
- (void)onRotated;
- (void)refresh;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)rtCommentNumbersReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)updateRtCommentNumberOfWeibos:(id)arg1;
- (BOOL)checkReportState:(id)arg1;
- (void)loadMoreWeibo;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;
- (void)loadFavTimeline;
- (id)init;

@end

