/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "AdContainerDelegate-Protocol.h"
#import "CLLocationManagerDelegate-Protocol.h"
#import "TimeLineTab-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WeiBoCoreTextViewDelegate-Protocol.h"

@class AdContainerViewController, CLLocationManager, ImageLoader, MGTwitterEngine_WeiboV4, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimer, NewHomelineViewController, PicStatusesViewController, TableRefreshHeaderView, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIPopoverController, UITableView, UITableViewCell, UIView, UserLsitsSelectViewController;

@interface HomeViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate, UIPopoverControllerDelegate, UIActionSheetDelegate, UIGestureRecognizerDelegate, CLLocationManagerDelegate, WeiBoCoreTextViewDelegate, TimeLineTab, AdContainerDelegate>
{
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engineWeibo;
    NSMutableArray *_items;
    NSMutableArray *ipad_Exist_Array;
    UIActivityIndicatorView *moreActivity;
    NSMutableDictionary *comNumberDictionary;
    NSMutableDictionary *remarkNameDictionary;
    NSMutableDictionary *ipad_Exists_Dic;
    unsigned char orientionChanged;
    unsigned char verifiedStatus;
    unsigned char loadingData;
    unsigned char loadOlder;
    unsigned char selectStatus;
    TableRefreshHeaderView *refreshHeaderView;
    UIPopoverController *userPopover;
    NewHomelineViewController *myDetailView;
    UserLsitsSelectViewController *userListViewController;
    NSDictionary *selectedWeibo;
    NSString *selectedImage;
    NSString *selectedLink;
    UITableViewCell *selectedCell;
    BOOL noOlderWeibo;
    BOOL showMessage;
    BOOL showFollowIpad;
    NSMutableArray *userListsArray;
    int statusesFeature;
    int selectListNum;
    int headerHeight;
    int loadingTime;
    PicStatusesViewController *mPicStatusesViewController;
    BOOL isShowPicStatuses;
    BOOL showHeaderStatus;
    BOOL showUserList;
    UIButton *userListsBtn;
    UIButton *allStatusesBtn;
    UIButton *picStatusesBtn;
    UIButton *originalStatusesBtn;
    UIButton *videoStatusesBtn;
    UIButton *musicStatusesBtn;
    UILabel *userListsLabel;
    UILabel *allStatuseLabel;
    UILabel *picStatuseLabel;
    UILabel *originalStatuseLabel;
    UILabel *videoStatuseLabel;
    UILabel *musicStatuseLabel;
    UIImageView *userListsImageView;
    UIImageView *allImageView;
    UIImageView *picImageView;
    UIImageView *originalImageView;
    UIImageView *videoImageView;
    UIImageView *musicImageView;
    UIImageView *arrowImageView;
    UIImageView *headerView;
    UIImageView *sepImageView;
    int currentViewNumber;
    UITableViewCell *touchedCell;
    int mediaCellSelectedIndex;
    UITableViewCell *musicCell;
    struct CGPoint selectMusicPoint;
    NSTimer *loadTimer;
    UIView *newWeiboHintView;
    UIImageView *newWeiboPopImageView;
    UILabel *newWeiboCountLb;
    UILabel *newWeiboCountCommentLb;
    CLLocationManager *locationManager;
    NSString *timelineStatus;
    int pageNo;
    float latitude;
    float longitude;
    ImageLoader *mImageLoader;
    AdContainerViewController *_adContainerVC;
}

@property(retain, nonatomic) NSString *selectedLink; // @synthesize selectedLink;
@property(retain, nonatomic) NSString *selectedImage; // @synthesize selectedImage;
@property(nonatomic) unsigned char selectStatus; // @synthesize selectStatus;
@property(retain, nonatomic) NSDictionary *selectedWeibo; // @synthesize selectedWeibo;
@property(retain, nonatomic) NSMutableArray *userListsArray; // @synthesize userListsArray;
@property(retain, nonatomic) NewHomelineViewController *myDetailView; // @synthesize myDetailView;
@property(retain, nonatomic) TableRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
@property(nonatomic) BOOL isShowPicStatuses; // @synthesize isShowPicStatuses;
- (void)narrowContainer;
- (void)expandContainer;
- (void)weiBoCoreTextViewTouchedAttributedInfo:(id)arg1 index:(int)arg2 tag:(int)arg3;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)updateLocation;
- (void)hideHintView;
- (void)hintViewShowed;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)thirdViewControllerClosed;
- (void)commentBtnTouched:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)musicStatusesBtnClicked:(id)arg1;
- (void)videoStatusesBtnClicked:(id)arg1;
- (void)orginalStatusesBtnClicked:(id)arg1;
- (void)allStatusesBtnClicked:(id)arg1;
- (void)picStatusesBtnClicked:(id)arg1;
- (void)userListsBtnClicked:(id)arg1;
- (void)fontSizeChanged:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)skinChanged:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)weiboDeleteDidFinished:(id)arg1;
- (void)changeSelectCellBackColor:(int)arg1 cellDic:(id)arg2 isButton:(BOOL)arg3;
- (void)changeSelectImageViewBackColor:(id)arg1 selectedStatus:(BOOL)arg2;
- (void)onWeiboMusicTouched:(id)arg1;
- (void)onWeiboMovieTouched:(id)arg1;
- (void)onWeiboRTTouched:(id)arg1;
- (void)onWeiboMapTouched:(id)arg1;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)finishLoadingNewData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)showLoadingHeader;
- (void)createHeaderView;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)remarkNameReceived:(id)arg1 forRequest:(id)arg2;
- (void)rtCommentNumbersReceived:(id)arg1 forRequest:(id)arg2;
- (void)userListsReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)friendShipReceived:(id)arg1 forRequest:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)onRotated;
- (void)onLogout;
- (void)onBringToFront;
- (void)refreshCommentNumber;
- (void)refresh;
- (void)getUsersRemarkName:(id)arg1;
- (void)updateRtCommentNumberOfWeibos:(id)arg1;
- (void)addIpadVipToFriendShips;
- (void)requestFriendShipsExists;
- (void)loadMoreMyWeibo;
- (void)loadNewMyWeibo;
- (void)loadMoreNearbyWeibo;
- (void)loadNewNearbyWeibo;
- (void)loadNewWeibo;
- (void)loadMoreWeibo;
- (void)loadNewWeiboForUserList:(int)arg1 listName:(id)arg2;
- (void)loadNearbyWeibo;
- (void)loadMyWeibo;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)showFollowIpadAlert;
- (void)loadTimeOut;
- (void)handleLongPress2:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (void)createHomeHeaderView;
- (void)refreshSkin;
- (void)releaseTimer;
- (void)viewDidLoad;

@end

