/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NewHomelineViewController, TableRefreshHeaderView, UIActivityIndicatorView, UITableView, UITableViewCell;

@interface HotTrendsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TimeLineTab>
{
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engine;
    NSMutableArray *_items;
    int pageNo;
    unsigned char orientionChanged;
    unsigned char verifiedStatus;
    unsigned char loadOlder;
    unsigned char favStatus;
    unsigned char reportStatus;
    unsigned char loadingData;
    unsigned char selectStatus;
    UIActivityIndicatorView *moreActivity;
    NewHomelineViewController *myDetailView;
    TableRefreshHeaderView *refreshHeaderView;
    NSMutableDictionary *comNumberDictionary;
    NSDictionary *selectedWeibo;
    NSString *selectedImage;
    UITableViewCell *selectedCell;
    BOOL noOlderWeibo;
}

@property(retain, nonatomic) NSDictionary *selectedWeibo; // @synthesize selectedWeibo;
@property(nonatomic) unsigned char selectStatus; // @synthesize selectStatus;
@property(retain, nonatomic) TableRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(nonatomic) NewHomelineViewController *myDetailView; // @synthesize myDetailView;
@property(nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
- (void)languageChanged:(id)arg1;
- (void)ChangeUser;
- (void)skinChanged:(id)arg1;
- (void)weiboDeleteDidFinished:(id)arg1;
- (void)changeSelectCellBackColor:(int)arg1 cellDic:(id)arg2 isButton:(BOOL)arg3;
- (void)changeSelectImageViewBackColor:(id)arg1 selectedStatus:(BOOL)arg2;
- (void)onWeiboMapTouched:(id)arg1;
- (void)onWeiboRTTouched:(id)arg1;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)finishLoadingNewData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showLoadingHeader;
- (void)createHeaderView;
- (void)onLogout;
- (void)onBringToFront;
- (void)onRotated;
- (void)refresh;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)rtCommentNumbersReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)userTrendsReceived:(id)arg1 forRequest:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)updateRtCommentNumberOfWeibos:(id)arg1;
- (void)loadNewWeibo;
- (void)loadMoreWeibo;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)refreshSkin;
- (void)viewDidLoad;

@end

