/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol HPGrowingTextViewDelegate

@optional
- (void)deleteImageBtnPressed;
- (void)imageViewDidClicked;
- (BOOL)growingTextViewShouldReturn:(id)arg1;
- (void)growingTextViewDidChangeSelection:(id)arg1;
- (void)growingTextView:(id)arg1 didChangeHeight:(float)arg2;
- (void)growingTextView:(id)arg1 willChangeHeight:(float)arg2;
- (void)growingTextViewDidChange:(id)arg1;
- (BOOL)growingTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)growingTextViewDidEndEditing:(id)arg1;
- (void)growingTextViewDidBeginEditing:(id)arg1;
- (BOOL)growingTextViewShouldEndEditing:(id)arg1;
- (BOOL)growingTextViewShouldBeginEditing:(id)arg1;
@end

