/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSXMLParserDelegate-Protocol.h"

@class NSMutableData, NSMutableString, NSString, NSURLConnection;

@interface ImageDownoader : NSObject <NSXMLParserDelegate>
{
    NSMutableData *result;
    int imageType;
    id <ImageDownoaderDelegate> delegate;
    NSString *origURL;
    NSURLConnection *connection;
    BOOL waitXMLInfo;
    NSMutableString *contentXMLProperty;
    NSString *fullYFrogImageURL;
    BOOL canceled;
}

@property(retain, nonatomic) NSMutableData *result; // @synthesize result;
@property(retain, nonatomic) NSString *origURL; // @synthesize origURL;
@property(retain, nonatomic) NSString *fullYFrogImageURL; // @synthesize fullYFrogImageURL;
@property(retain, nonatomic) NSMutableString *contentXMLProperty; // @synthesize contentXMLProperty;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection;
- (id)getThumbnailImage:(id)arg1;
- (int)imageType;
- (BOOL)canceled;
- (void)cancel;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)getImageFromURL:(id)arg1 imageType:(int)arg2 delegate:(id)arg3;
- (void)postRequestForImage:(id)arg1;
- (void)dealloc;
- (id)init;

@end

