/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ImageDownoaderDelegate <NSObject>
- (void)receivedLoadingImageSize:(long long)arg1;
- (void)receivedImageSize:(long long)arg1;
- (void)receivedImage:(id)arg1 sender:(id)arg2;
@end

