/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "ImageDownoaderDelegate-Protocol.h"

@class NSMutableDictionary, WBGIFDecodeOperation;

@interface ImageLoader : NSObject <ImageDownoaderDelegate>
{
    NSMutableDictionary *_cache;
    NSMutableDictionary *_activeDownloads;
    id <ImageLoaderDelegate> delegate;
    int cellImageTag;
    struct CGPoint imageCenter;
    struct CGRect viewRect;
    NSMutableDictionary *_dictLastUrlForView;
    WBGIFDecodeOperation *myWBGIFDecode;
    BOOL isScrolling;
    BOOL thumbNailImage;
}

+ (id)sharedLoader;
@property(nonatomic) BOOL thumbNailImage; // @synthesize thumbNailImage;
@property(nonatomic) BOOL isScrolling; // @synthesize isScrolling;
@property(nonatomic) NSMutableDictionary *_cache; // @synthesize _cache;
@property(nonatomic) struct CGRect viewRect; // @synthesize viewRect;
@property(nonatomic) struct CGPoint imageCenter; // @synthesize imageCenter;
@property(nonatomic) int cellImageTag; // @synthesize cellImageTag;
@property(nonatomic) id <ImageLoaderDelegate> delegate; // @synthesize delegate;
- (id)getThumbnailImage:(id)arg1;
- (void)dealloc;
- (void)changeImage:(id)arg1 photoImageViewFrame:(id)arg2;
- (void)changeFrameImage:(id)arg1 photoImageView:(id)arg2;
- (void)receivedImage:(id)arg1 sender:(id)arg2;
- (void)receivedLoadingImageSize:(long long)arg1;
- (void)receivedImageSize:(long long)arg1;
- (void)setImageWithURL:(id)arg1 toView:(id)arg2 delegate:(id)arg3;
- (void)initDownLoader:(id)arg1;
- (void)setImageWithURL:(id)arg1 toView:(id)arg2;
- (id)imageWithURL:(id)arg1;
- (void)clearCacheImage;
- (id)init;

@end

