/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIScrollView.h"

#import "ImageLoaderDelegate-Protocol.h"

@class ImageLoader, NSString, PhotoViewerViewController, UIImageView, UIProgressView;

@interface ImageScrollView : UIScrollView <ImageLoaderDelegate>
{
    UIImageView *photoImageView;
    UIImageView *loadingImageView;
    UIProgressView *loadingProgressView;
    ImageLoader *myImageLoader;
    ImageLoader *thumbnailImageLoader;
    NSString *photoUrl;
    _Bool touchedImageView;
    _Bool isZoom;
    _Bool zoomClose;
    PhotoViewerViewController *myPhotoViewer;
    long loadImageSize;
}

@property(nonatomic) _Bool zoomClose; // @synthesize zoomClose;
@property(nonatomic) _Bool isZoom; // @synthesize isZoom;
@property(nonatomic) UIProgressView *loadingProgressView; // @synthesize loadingProgressView;
@property(nonatomic) PhotoViewerViewController *myPhotoViewer; // @synthesize myPhotoViewer;
@property(retain, nonatomic) NSString *photoUrl; // @synthesize photoUrl;
@property(nonatomic) UIImageView *loadingImageView; // @synthesize loadingImageView;
@property(retain, nonatomic) UIImageView *photoImageView; // @synthesize photoImageView;
- (void)gifLoadFailed:(id)arg1;
- (void)didReceiveImageSize:(long long)arg1 withImageLoader:(id)arg2;
- (void)loadImageSize:(long long)arg1 withImageLoader:(id)arg2;
- (void)onImageLoadComplete:(id)arg1;
- (void)changeThumbnailImageViewFrame;
- (void)changeImageViewFrame;
- (void)changeProgressViewCenter;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (void)setPhotoImageViewImage:(id)arg1;
- (void)loadCacheImageWithURL:(id)arg1;
- (void)loadImage;
- (id)initWithFrame:(struct CGRect)arg1;

@end

