/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ImageLoaderDelegate <NSObject>
- (void)gifLoadFailed:(id)arg1;
- (void)didReceiveImageSize:(long long)arg1 withImageLoader:(id)arg2;
- (void)loadImageSize:(long long)arg1 withImageLoader:(id)arg2;
- (void)onImageLoadComplete:(id)arg1;
@end

