/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSDate;

@interface LocationManager : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *locationManager;
    BOOL locationDefined;
    float latitude;
    float longitude;
    BOOL locationDenied;
    double lastUpdateTime;
    NSDate *locationManagerStartDate;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)locationManager;
@property(retain, nonatomic) NSDate *locationManagerStartDate; // @synthesize locationManagerStartDate;
- (float)longitude;
- (float)latitude;
- (BOOL)locationDefined;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (BOOL)locationServicesEnabled;
- (BOOL)locationDenied;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (BOOL)isValidLocation:(id)arg1 withOldLocation:(id)arg2;
- (id)mapURL;
- (id)longURL;
- (id)longURLWithLatitude:(float)arg1 longitude:(float)arg2;
- (id)urlFormat;
- (void)startUpdates;
- (void)stopUpdates;
- (void)dealloc;
- (id)init;
- (void)reset;
- (id)autorelease;
- (void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

