/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSXMLParserDelegate-Protocol.h"

@class NSData, NSMutableArray, NSMutableDictionary, NSObject<MGTwitterParserDelegate>, NSString, NSXMLParser;

@interface MGTwitterJSONParser : NSObject <NSXMLParserDelegate>
{
    NSObject<MGTwitterParserDelegate> *delegate;
    NSString *identifier;
    int requestType;
    int responseType;
    NSData *json;
    NSMutableArray *parsedObjects;
    NSXMLParser *parser;
    NSMutableDictionary *currentNode;
    NSString *lastOpenedElement;
}

+ (id)parserWithJSON:(id)arg1 delegate:(id)arg2 connectionIdentifier:(id)arg3 requestType:(int)arg4 responseType:(int)arg5;
- (void)dealloc;
- (id)initWithJSON:(id)arg1 delegate:(id)arg2 connectionIdentifier:(id)arg3 requestType:(int)arg4 responseType:(int)arg5;

@end

