/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "MGTwitterEngine.h"

@interface MGTwitterEngine (BasicAuth)
- (void)httpConnectDownloadDataTimeOut:(id)arg1 withFutherInfo:(void *)arg2;
- (void)httpConnectDownloadDataFailed:(id)arg1 withFutherInfo:(void *)arg2;
- (void)httpConnect:(id)arg1 successDownloadData:(id)arg2 withFutherInfo:(void *)arg3;
- (id)infoFromReturnString:(id)arg1;
- (id)stringFromDictionaryForHeadField:(id)arg1;
- (id)stringFromDictionary:(id)arg1;
- (id)getSignatureBaseStringWithHttpMethod:(id)arg1 withURL:(id)arg2 withHeadInfo:(id)arg3;
- (void)getAccessTokenWithUserName:(id)arg1 userPassword:(id)arg2;
- (id)getWidgetInfo:(id)arg1;
- (id)getBatchInfo:(id)arg1;
- (id)getCommentsDailyCount:(int)arg1;
- (id)getRepostDailyCount:(int)arg1;
- (id)getLatestVersion;
- (id)queryMidById:(unsigned long long)arg1 type:(int)arg2;
- (id)existBlockUserById:(unsigned long long)arg1;
- (id)unblockUserById:(unsigned long long)arg1;
- (id)blockUserById:(unsigned long long)arg1;
- (id)deleteUserListsWithListID:(unsigned long long)arg1;
- (id)updateUserListsWithListID:(unsigned long long)arg1 name:(id)arg2 description:(id)arg3;
- (id)createUserListsWithName:(id)arg1 mode:(id)arg2 description:(id)arg3;
- (id)getChannelStatusesWithUrl:(id)arg1 sinceID:(unsigned long long)arg2 withMaximumID:(unsigned long long)arg3 per_page:(int)arg4 page:(int)arg5 base_app:(int)arg6 feature:(int)arg7;
- (id)getListStatusesWithListId:(unsigned long long)arg1 sinceID:(unsigned long long)arg2 withMaximumID:(unsigned long long)arg3 per_page:(int)arg4 page:(int)arg5 base_app:(int)arg6 feature:(int)arg7;
- (id)getUserListsWithCursor:(int)arg1 listType:(int)arg2;
- (id)getStatuesByKeyword:(id)arg1 filter_ori:(int)arg2 filter_pic:(int)arg3 fuid:(unsigned long long)arg4 province:(int)arg5 city:(int)arg6 starttime:(int)arg7 endtime:(id)arg8 page:(int)arg9 count:(int)arg10;
- (id)getUsersByKeyword:(id)arg1 snick:(int)arg2 sdomain:(int)arg3 sintro:(int)arg4 province:(int)arg5 city:(int)arg6 gender:(int)arg7 comorsch:(id)arg8 sort:(int)arg9 page:(int)arg10 count:(int)arg11;
- (id)updateUserProfileWithName:(id)arg1 gender:(id)arg2 province:(int)arg3 city:(int)arg4 description:(id)arg5;
- (void)setUsername:(id)arg1 password:(id)arg2;
- (id)password;
- (id)username;
@end

