/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MGTwitterParserDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSObject<MGTwitterEngineDelegate>, NSString, NSTimer;

@interface MGTwitterEngine_Weibo : NSObject <MGTwitterParserDelegate>
{
    NSObject<MGTwitterEngineDelegate> *_delegate;
    NSMutableDictionary *_connections;
    NSString *_clientName;
    NSString *_clientVersion;
    NSString *_clientURL;
    NSString *_clientSourceToken;
    NSString *_APIDomain;
    BOOL _secureConnection;
    BOOL _clearsCookies;
    int currentPageNo;
    int currentAtPageNo;
    NSMutableArray *newWeibos;
    NSString *_statusStr;
    NSString *unReadAtMsgCount;
    NSString *unReadFansCount;
    NSString *unReadMBlogCount;
    NSString *unReadCommentCount;
    NSString *unReadPrivateMailCount;
    int newWeiboAmmount;
    NSString *newWeibosMinId;
    int localWeiboAmountInPage;
    NSTimer *_timer;
    int timerCount;
    int profileUid;
    BOOL isSingMblog;
    BOOL isNoticeSetting;
}

+ (id)clientVersion;
+ (id)clientName;
+ (id)userAgent;
+ (void)remindNick:(id)arg1;
+ (void)forgetPaw;
+ (id)paw;
+ (void)forgetNick;
+ (id)nick;
+ (void)remindPaw:(id)arg1;
+ (void)remindUid:(id)arg1;
+ (void)forgetUid;
+ (id)uid;
+ (void)remindSid:(id)arg1;
+ (void)forgetSid;
+ (void)resetUid;
+ (void)resetSid;
+ (void)resetGsid;
+ (id)sid;
+ (void)remindGsid:(id)arg1;
+ (void)forgetGsid;
+ (id)gsid;
+ (void)remindPassword;
+ (void)forgetPassword;
+ (id)get_statusArray;
+ (void)remindStatusArray:(id)arg1;
+ (id)getNextAction;
+ (void)setNextAction:(id)arg1;
+ (void)setUsername:(id)arg1 password:(id)arg2 remember:(BOOL)arg3;
+ (id)password;
+ (id)username;
+ (id)version;
+ (id)twitterEngineWithDelegate:(id)arg1;
@property(nonatomic) NSObject<MGTwitterEngineDelegate> *_delegate; // @synthesize _delegate;
@property(copy, nonatomic) NSString *newWeibosMinId; // @synthesize newWeibosMinId;
@property(nonatomic) int profileUid; // @synthesize profileUid;
@property(nonatomic) int localWeiboAmountInPage; // @synthesize localWeiboAmountInPage;
@property(nonatomic) int currentPageNo; // @synthesize currentPageNo;
@property(nonatomic) int newWeiboAmmount; // @synthesize newWeiboAmmount;
- (id)getAltWithTgt:(id)arg1;
- (id)getTgtWithUserName:(id)arg1 password:(id)arg2;
- (id)searchAroundPOIbyLat:(float)arg1 Lon:(float)arg2 Start:(int)arg3 Num:(int)arg4 Query:(id)arg5;
- (id)addmblog2012;
- (id)getPrivateMailPostData:(id)arg1;
- (id)getReleaseCommentPostData:(id)arg1;
- (id)getUserInformationFor:(id)arg1 nick:(id)arg2 pageNum:(int)arg3 pageSize:(int)arg4;
- (id)getListOrBackgroundVisitCount:(id)arg1 param:(int)arg2;
- (id)getAdvertisement;
- (id)deleteAllPrivateMailWithSomeone:(id)arg1;
- (id)deleteOnePrivateMail:(id)arg1 msgid:(id)arg2;
- (id)getSearchGrid;
- (id)getFeaturedPeopleList:(int)arg1 pageNo:(int)arg2 pageSize:(int)arg3;
- (id)getChannelList:(id)arg1 pageNo:(int)arg2 pageSize:(int)arg3;
- (id)setUserGroupWithUserId:(id)arg1 withGroupIds:(id)arg2;
- (id)getUserGroupInfoWithUserId:(id)arg1;
- (id)getHotWords:(int)arg1;
- (id)searchFriendsOfUser:(id)arg1 withKeyword:(id)arg2 atPage:(int)arg3;
- (id)searchAllFriendsOfUser:(id)arg1 withKeyword:(id)arg2 atPage:(int)arg3;
- (id)sendPrivateMail:(id)arg1 usernick:(id)arg2 content:(id)arg3 fid:(id)arg4;
- (id)getPrivateMailList:(id)arg1 pageNum:(int)arg2 count:(int)arg3;
- (id)getMessageForUserId:(id)arg1 maxMessageId:(id)arg2 sinceMessageId:(id)arg3 count:(unsigned int)arg4;
- (id)getPrivateMailList:(id)arg1 withSinceId:(id)arg2 withMaxId:(id)arg3 pageNum:(int)arg4 count:(int)arg5;
- (BOOL)loginFor:(id)arg1 password:(id)arg2;
- (id)getLoginU:(id)arg1 P:(id)arg2;
- (id)getDowntimeSchedule;
- (id)testService;
- (id)unblock:(id)arg1;
- (id)block:(id)arg1;
- (id)setNotificationsDeliveryMethod:(id)arg1;
- (id)setLocation:(id)arg1;
- (id)settingNotice:(id)arg1;
- (id)getRateLimitStatus;
- (id)disableNotificationsFor:(id)arg1;
- (id)enableNotificationsFor:(id)arg1;
- (id)isUser:(id)arg1 receivingUpdatesFor:(id)arg2;
- (id)disableUpdatesFor:(id)arg1;
- (id)enableUpdatesFor:(id)arg1;
- (id)endUserSession;
- (id)checkUserCredentials;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)parsingFailedForRequest:(id)arg1 ofResponseType:(int)arg2 withError:(id)arg3;
- (void)parsingSucceededForRequest:(id)arg1 ofResponseType:(int)arg2 withParsedObjects:(id)arg3;
- (void)parsingSucceededBasicInfo:(id)arg1 ofResponseType:(int)arg2 withObject:(id)arg3;
- (BOOL)_isValidDelegateForSelector:(SEL)arg1;
- (void)removeDelegate;
- (void)_parseDataForConnection:(id)arg1;
- (id)_sendRequestWithMethod:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 bodyData:(id)arg4 requestType:(int)arg5 responseType:(int)arg6;
- (id)_sendRequestWithMethod:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 body:(id)arg4 requestType:(int)arg5 responseType:(int)arg6;
- (id)createMd5Key;
- (id)md5HexDigest:(id)arg1;
- (id)getImageAtURL:(id)arg1;
- (id)_encodeString:(id)arg1;
- (id)_dateToHTTP:(id)arg1;
- (id)_HTTPToDate:(id)arg1;
- (id)_queryStringWithBase:(id)arg1 parameters:(id)arg2 prefixed:(BOOL)arg3;
- (id)getAttgroupWeibo:(id)arg1 maxId:(id)arg2;
- (id)getAttgroupList;
- (id)_HTTPDateFormatter;
- (void)closeAllConnections;
- (void)closeConnection:(id)arg1;
- (id)connectionIdentifiers;
- (int)numberOfConnections;
- (void)setClearsCookies:(BOOL)arg1;
- (BOOL)clearsCookies;
- (void)setUsesSecureConnection:(BOOL)arg1;
- (BOOL)usesSecureConnection;
- (void)setAPIDomain:(id)arg1;
- (id)APIDomain;
- (void)setClientName:(id)arg1 version:(id)arg2 URL:(id)arg3 token:(id)arg4;
- (id)clientSourceToken;
- (id)clientURL;
- (id)clientVersion;
- (id)clientName;
- (void)stopTimer;
- (void)initTimer;
- (void)restarTimer;
- (void)resetTimer;
- (void)refreshUserUnreadMsgTimer:(id)arg1;
- (void)parserUserUnread:(id)arg1;
- (id)getReturnPlat:(id)arg1;
- (id)platform;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

