/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MGTwitterEngineDelegate-Protocol.h"
#import "MGTwitterParserDelegate-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSObject<MGTwitterEngineDelegate>, NSString, SNHttpConnect;

@interface MGTwitterEngine : NSObject <MGTwitterEngineDelegate, MGTwitterParserDelegate>
{
    SNHttpConnect *httpConnect;
    NSObject<MGTwitterEngineDelegate> *_delegate;
    NSMutableDictionary *_connections;
    NSString *_clientName;
    NSString *_clientVersion;
    NSString *_clientURL;
    NSString *_clientSourceToken;
    NSString *_APIDomain;
    BOOL _secureConnection;
    BOOL _clearsCookies;
    NSString *_username;
    NSString *_password;
    NSDictionary *_xauthToken;
}

+ (id)version;
+ (id)twitterEngineWithDelegate:(id)arg1;
@property(retain, nonatomic) SNHttpConnect *httpConnect; // @synthesize httpConnect;
@property(nonatomic) NSObject<MGTwitterEngineDelegate> *_delegate; // @synthesize _delegate;
@property(retain, nonatomic) NSDictionary *_xauthToken; // @synthesize _xauthToken;
@property(retain, nonatomic) NSString *_username; // @synthesize _username;
@property(retain, nonatomic) NSString *_password; // @synthesize _password;
- (id)getForwardsOf:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getCommentsOf:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getCommentsSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getCommentsSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)deleteWeiboCommentByID:(unsigned long long)arg1;
- (id)deleteWeiboByID:(unsigned long long)arg1;
- (id)getStatusFromUserID:(id)arg1 WeiboID:(unsigned long long)arg2;
- (id)getCommentsByMeSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getCommentsByMeSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getCommentsToMeSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getCommentsToMeSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getFollowerIDsFor:(id)arg1 startingFromCursor:(long long)arg2;
- (id)getFriendIDsFor:(id)arg1 startingFromCursor:(long long)arg2;
- (id)getDowntimeSchedule;
- (id)testService;
- (id)checkUserExistsBlocks:(id)arg1;
- (id)unblock:(id)arg1;
- (id)block:(id)arg1;
- (id)weiboReportWithUserId:(id)arg1 url:(id)arg2 content:(id)arg3;
- (id)disableNotificationsFor:(id)arg1;
- (id)enableNotificationsFor:(id)arg1;
- (id)resetUnread:(int)arg1;
- (id)getUnread;
- (id)unRegAllPushRequest;
- (id)pushSetRequest:(int)arg1 beginHour:(int)arg2 endHour:(int)arg3 isChange:(BOOL)arg4;
- (id)sendInstallRequest;
- (id)sendReport_SpamRequest;
- (id)markUpdate:(unsigned long long)arg1 asFavorite:(BOOL)arg2;
- (id)getFavoriteUpdatesFor:(id)arg1 startingAtPage:(int)arg2;
- (id)getRateLimitStatus;
- (id)setNotificationsDeliveryMethod:(id)arg1;
- (id)setLocation:(id)arg1;
- (id)setProfileBackgroundImageWithImageAtPath:(id)arg1 andTitle:(id)arg2;
- (id)setProfileImageWithImage:(id)arg1;
- (id)endUserSession;
- (id)checkUserCredentials;
- (id)cancelUserFellowShip:(id)arg1;
- (id)cancelUserFromFriend:(id)arg1;
- (id)addUserToFriend:(id)arg1;
- (id)isUser:(id)arg1 receivingUpdatesFor:(id)arg2;
- (id)showFriendshipFor:(long long)arg1;
- (id)disableUpdatesFor:(id)arg1;
- (id)enableUpdatesFor:(id)arg1;
- (id)getHotTrends:(BOOL)arg1;
- (id)getUserTrends:(id)arg1 pages:(int)arg2 trendCount:(int)arg3;
- (id)deleteBatchDirectMessage:(id)arg1;
- (id)deleteDirectMessage:(unsigned long long)arg1;
- (id)sendDirectMessage:(id)arg1 to:(id)arg2;
- (id)getSentDirectMessagesSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getSentDirectMessagesSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2;
- (id)getDirectMessagesUserListWithCursor:(int)arg1 count:(int)arg2;
- (id)getDirectMessagesWithID:(unsigned long long)arg1 sinceID:(unsigned long long)arg2 withMaximumID:(unsigned long long)arg3 startingAtPage:(int)arg4 count:(int)arg5;
- (id)getDirectMessagesSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getDirectMessagesSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2;
- (id)getMessagePrivacy;
- (id)updateUserRemarkByUserId:(id)arg1 remark:(id)arg2;
- (id)getUserInformationForEmail:(id)arg1;
- (id)getBulkUserInformationFor:(id)arg1;
- (id)getUserInformationForId:(id)arg1;
- (id)getUserInformationForUserName:(id)arg1;
- (id)getUserInformationFor:(id)arg1;
- (id)getFollowersIncludingCurrentStatus:(BOOL)arg1;
- (id)getAtUserByKeyWord:(id)arg1 startingAtPage:(int)arg2 type:(int)arg3 count:(int)arg4;
- (id)getRecentlyUpdatedFollowersFor:(id)arg1 startingAtPage:(int)arg2;
- (id)getRecentlyUpdatedFriendsFor:(id)arg1 startingAtPage:(int)arg2;
- (id)getFeaturedUsers;
- (id)deleteUpdate:(unsigned long long)arg1;
- (id)getMentionsSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getMentionsSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getRepliesSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getRepliesSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getRepliesStartingAtPage:(int)arg1;
- (id)sendComment:(unsigned long long)arg1 withComment:(id)arg2 toComment:(unsigned long long)arg3 is_repost:(int)arg4;
- (id)sendRetweet:(unsigned long long)arg1 withRtReason:(id)arg2 is_comment:(int)arg3;
- (id)sendUpdate:(id)arg1 withImage:(id)arg2 withLatitude:(double)arg3 longitude:(double)arg4;
- (id)sendUpdate:(id)arg1 withImage:(id)arg2;
- (id)sendUpdate:(id)arg1 inReplyTo:(unsigned long long)arg2 withLatitude:(double)arg3 longitude:(double)arg4;
- (id)sendUpdate:(id)arg1 inReplyTo:(unsigned long long)arg2;
- (id)sendUpdate:(id)arg1 withLatitude:(double)arg2 longitude:(double)arg3;
- (id)getStreetInfoWithLatitude:(double)arg1 longitude:(double)arg2;
- (id)sendUpdate:(id)arg1;
- (id)getRtNumberAndCommentNumber:(id)arg1;
- (id)getUserRemarkName:(id)arg1;
- (id)getUpdate:(unsigned long long)arg1;
- (id)getUserTimelineFor:(id)arg1 sinceID:(unsigned long long)arg2 withMaximumID:(unsigned long long)arg3 startingAtPage:(int)arg4 count:(int)arg5;
- (id)getUserTimelineFor:(id)arg1 sinceID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getFollowedTimelineSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getFollowedTimelineSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getHomeTimelineSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4 feature:(int)arg5;
- (id)getHomeTimelineSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3 feature:(int)arg4;
- (id)getPublicTimelineSinceID:(unsigned long long)arg1 withMaximumID:(unsigned long long)arg2 startingAtPage:(int)arg3 count:(int)arg4;
- (id)getPublicTimelineSinceID:(unsigned long long)arg1 startingAtPage:(int)arg2 count:(int)arg3;
- (id)getPublicTimeline;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)parsingFailedForRequest:(id)arg1 ofResponseType:(int)arg2 withError:(id)arg3;
- (void)parsingJSONSucceededForRequest:(id)arg1 ofResponseType:(int)arg2 withParsedArray:(id)arg3;
- (void)parsingJSONSucceededForRequest:(id)arg1 ofResponseType:(int)arg2 withParsedObjects:(id)arg3;
- (void)parsingSucceededForRequest:(id)arg1 ofResponseType:(int)arg2 withParsedObjects:(id)arg3;
- (BOOL)_isValidDelegateForSelector:(SEL)arg1;
- (void)_parseDataForConnection:(id)arg1;
- (id)_baseRequestWithMethod:(id)arg1 path:(id)arg2 requestType:(int)arg3 queryParameters:(id)arg4;
- (id)_sendDataRequestWithMethod:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 filePath:(id)arg4 body:(id)arg5 requestType:(int)arg6 responseType:(int)arg7;
- (id)_sendImageAndGPSDataRequestWithMethod:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 image:(id)arg4 body:(id)arg5 requestType:(int)arg6 responseType:(int)arg7;
- (id)_sendUserProfileImageDataRequestWithMethod:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 image:(id)arg4 body:(id)arg5 requestType:(int)arg6 responseType:(int)arg7;
- (id)_sendImageDataRequestWithMethod:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 image:(id)arg4 body:(id)arg5 requestType:(int)arg6 responseType:(int)arg7;
- (id)getPostBlogTextBody:(id)arg1 img:(id)arg2 msg:(id)arg3;
- (id)_sendRequestWithMethod:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 body:(id)arg4 requestType:(int)arg5 responseType:(int)arg6;
- (id)_sendRequest:(id)arg1 withRequestType:(int)arg2 responseType:(int)arg3;
- (id)getImageAtURL:(id)arg1;
- (id)_encodeString:(id)arg1;
- (id)_dateToHTTP:(id)arg1;
- (id)_HTTPToDate:(id)arg1;
- (id)_queryStringWithBase:(id)arg1 parameters:(id)arg2 prefixed:(BOOL)arg3;
- (id)_HTTPDateFormatter;
- (void)closeAllConnections;
- (void)closeConnection:(id)arg1;
- (id)connectionIdentifiers;
- (unsigned int)numberOfConnections;
- (void)setClearsCookies:(BOOL)arg1;
- (BOOL)clearsCookies;
- (void)setUsesSecureConnection:(BOOL)arg1;
- (BOOL)usesSecureConnection;
- (void)setAPIDomain:(id)arg1;
- (id)APIDomain;
- (void)setClientName:(id)arg1 version:(id)arg2 URL:(id)arg3 token:(id)arg4;
- (id)clientSourceToken;
- (id)clientURL;
- (id)clientVersion;
- (id)clientName;
- (id)getReturnPlat:(id)arg1;
- (id)platform;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

