/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, NSMutableArray, NSObject<MGTwitterParserDelegate>, NSString, NSURL;

@interface MGTwitterLibXMLParser : NSObject
{
    NSObject<MGTwitterParserDelegate> *delegate;
    NSString *identifier;
    int requestType;
    int responseType;
    NSURL *URL;
    NSData *xml;
    NSMutableArray *parsedObjects;
}

+ (id)parserWithXML:(id)arg1 delegate:(id)arg2 connectionIdentifier:(id)arg3 requestType:(int)arg4 responseType:(int)arg5 URL:(id)arg6;
- (void)_parsingErrorOccurred:(id)arg1;
- (void)_parsingDidEnd;
- (id)_geoForNode:(id)arg1;
- (id)_sourceForNode:(id)arg1;
- (id)_userDictionaryForNode:(id)arg1;
- (id)_statusDictionaryForNode:(id)arg1;
- (id)_normalDictionaryForNodeWithName:(id)arg1;
- (void)parse;
- (void)dealloc;
- (id)initWithXML:(id)arg1 delegate:(id)arg2 connectionIdentifier:(id)arg3 requestType:(int)arg4 responseType:(int)arg5 URL:(id)arg6;

@end

