/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol MGTwitterEngineDelegate
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;

@optional
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)connectionFinished:(id)arg1;
- (void)connectionStarted:(id)arg1;
- (void)imageReceived:(id)arg1 forRequest:(id)arg2;
- (void)socialGraphInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)getCaptchaReceived:(id)arg1;
- (void)jsonDictionaryReceived:(id)arg1 forRequest:(id)arg2;
- (void)batchInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)blockListReceived:(id)arg1 forRequest:(id)arg2;
- (void)channelWeiboReceived:(id)arg1 forRequest:(id)arg2;
- (void)deletePrivateMailReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)sendPmReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)editUserGroupReceived:(id)arg1 forRequest:(id)arg2;
- (void)destroyUserGroupReceived:(id)arg1 forRequest:(id)arg2;
- (void)settingUserGroupReceived:(id)arg1 forRequest:(id)arg2;
- (void)weiboUserGroupReceived:(id)arg1 forRequest:(id)arg2;
- (void)weiboUserInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)channelListReceived:(id)arg1;
- (void)peopleReceived:(id)arg1;
- (void)loginReceived:(id)arg1 forRequest:(id)arg2;
- (void)installReceived:(id)arg1 forRequest:(id)arg2;
- (void)userGroupReceived:(id)arg1 forRequest:(id)arg2;
- (void)blocksExistsReceived:(id)arg1 forRequest:(id)arg2;
- (void)privacyInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)pushInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)updateRemarkReceived:(id)arg1 forRequest:(id)arg2;
- (void)remarkNameReceived:(id)arg1 forRequest:(id)arg2;
- (void)streetInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)userTrendsReceived:(id)arg1 forRequest:(id)arg2;
- (void)rtReportReceived:(id)arg1 forRequest:(id)arg2;
- (void)rtCommentNumbersReceived:(id)arg1 forRequest:(id)arg2;
- (void)miscInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)usersInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)userInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)directMessagesReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
@end

