/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSDictionary, NSString, UIImageView, UITableView, UITextView;

@interface MyUserFullInfoViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *mainTableView;
    NSDictionary *userDic;
    _Bool followerStatus;
    _Bool blogStatus;
    UIImageView *sepImageView;
    UIImageView *vipBackImageView;
    UITextView *infoText;
    NSString *blockListCount;
    MGTwitterEngine_WeiboV4 *_engine;
    _Bool blockListStatus;
}

@property(nonatomic) _Bool followerStatus; // @synthesize followerStatus;
@property(retain, nonatomic) NSDictionary *userDic; // @synthesize userDic;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
- (void)languageChanged:(id)arg1;
- (void)messageBoxChanged:(id)arg1;
- (void)skinChanged:(id)arg1;
- (void)blockListReceived:(id)arg1 forRequest:(id)arg2;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)onRotated:(int)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)openUrl:(id)arg1;
- (void)addTableViewHeaderView;
- (void)clearTableViewHeaderView;
- (void)createTableView;
- (void)requestBlockList;
- (void)viewDidLoad;

@end

