/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "CLLocationManagerDelegate-Protocol.h"
#import "DisplayExpressionDelegate-Protocol.h"
#import "InsertTopicDelegate-Protocol.h"
#import "MessageBoxDelegate-Protocol.h"
#import "POIInfoDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"
#import "UserFinderDelegate-Protocol.h"

@class AtPersonToMesViewController, CLLocationManager, ExpressionViewContrller, MGTwitterEngine_WeiboV4, MessageBoxViewController, NSArray, NSDate, NSDictionary, NSMutableArray, NSString, SSTextView, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIImageView, UILabel, UIPopoverController, UIToolbar, UIView;

@interface NewWeiboViewController : UIViewController <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIPopoverControllerDelegate, UITextViewDelegate, UIActionSheetDelegate, CLLocationManagerDelegate, UserFinderDelegate, DisplayExpressionDelegate, POIInfoDelegate, InsertTopicDelegate, MessageBoxDelegate>
{
    MGTwitterEngine_WeiboV4 *_engineWeiboV4;
    SSTextView *_textContent;
    UILabel *wordCountLabel;
    UIPopoverController *atpopoverController;
    UIPopoverController *topicPopoverController;
    UIPopoverController *gpsPOIListPopoverController;
    UIButton *clearImageButton;
    UIButton *newPicture;
    UIButton *gpsButton;
    UIButton *leftImageRotate;
    UIButton *rightImageRotate;
    UIButton *doneBtn;
    UIImageView *imageView;
    UIImageView *imageBorder;
    UIImageView *dataImage;
    BOOL imageFlag;
    BOOL showStreetInfo;
    BOOL cameraFlag;
    NSString *_textString;
    UIBarButtonItem *barItemSend;
    UIBarButtonItem *barItemLoad;
    UIActivityIndicatorView *sendActivity;
    UIToolbar *toolbar;
    UIView *imageContainer;
    UIButton *sendWeiboBtn;
    UIButton *editImageBtn;
    UIButton *cameraPictureBtn;
    UIButton *latitudeButton;
    struct CGRect imageViewRect;
    BOOL isKeyboardUp;
    BOOL needRotate;
    UILabel *replyLabel;
    UILabel *latitudeLb;
    UILabel *longtitudeLb;
    UILabel *titleLb;
    BOOL withGPS;
    BOOL getLocationSuccessed;
    CDStruct_2c43369c location;
    CLLocationManager *locationManager;
    UIImageView *buttonsImageView;
    UIActivityIndicatorView *loadingActicity;
    struct _NSRange selectedRange;
    NSArray *faceTextArray;
    ExpressionViewContrller *expressionView;
    UIView *baseView;
    struct _NSRange topicRange;
    struct _NSRange topicEndRange;
    struct _NSRange atRange;
    struct _NSRange atEndRange;
    BOOL isTopicPopOn;
    BOOL sending;
    AtPersonToMesViewController *mAtPersonToMesViewController;
    MessageBoxViewController *mMessageBoxViewController;
    UIButton *messageBoxBtn;
    UIView *controlView;
    BOOL showFace;
    UIView *clearTextView;
    UIImageView *GPSImageView;
    NSDictionary *savedMessage;
    UIImageView *clearImageView;
    UIButton *clearButton;
    UIButton *faceButton;
    UIButton *atButton;
    UIButton *newTopic;
    UIPopoverController *messageboxPopover;
    UIPopoverController *imagePopover;
    UILabel *messagebox_lb;
    NSString *poiIDstr;
    NSString *areaName;
    NSMutableArray *poiListAry;
    NSString *xid;
    NSString *savePOIName;
    NSString *poiName;
    struct _NSRange rangeSel;
    NSString *style;
    NSDictionary *weiboInfo;
    BOOL isRepost;
    BOOL isReplyComment;
    BOOL isDraft;
    NSDate *draftDate;
    UIImageView *comWeiboBg;
    UIButton *isCommentBtn;
    BOOL titleStatus;
    UILabel *commentLb;
    BOOL flag;
    BOOL fromMessageBox;
}

@property(nonatomic) BOOL fromMessageBox; // @synthesize fromMessageBox;
@property(nonatomic) BOOL isReplyComment; // @synthesize isReplyComment;
@property(nonatomic) BOOL titleStatus; // @synthesize titleStatus;
@property(retain, nonatomic) NSDictionary *weiboInfo; // @synthesize weiboInfo;
@property(retain, nonatomic) UILabel *replyLabel; // @synthesize replyLabel;
@property(retain, nonatomic) NSString *_textString; // @synthesize _textString;
@property(retain, nonatomic) UIPopoverController *atpopoverController; // @synthesize atpopoverController;
- (void)changeToFitWidth:(id)arg1;
- (struct _NSRange)getRangeSel:(struct _NSRange)arg1;
- (void)dismissPOIPopover;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)getXID:(id)arg1;
- (void)AroundPOIReceived:(id)arg1;
- (void)getPOIID:(id)arg1;
- (void)getPOIName:(id)arg1;
- (void)GetPOIList;
- (void)onLocationUpdated:(id)arg1;
- (void)backspaceTouched;
- (void)clearCrashCheck;
- (void)changeMessageBoxBtnTitle;
- (void)messageBoxSelected:(id)arg1;
- (void)onInsertTopic:(id)arg1;
- (void)DisplayWord:(id)arg1;
- (void)onUsersFoundNick:(id)arg1 Uid:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)animationStoped2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)animationStoped;
- (void)editImageBtnTouched;
- (void)selectImage;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)streetInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingImage:(id)arg2 editingInfo:(id)arg3;
- (id)getThumbnailImage:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)onChooseImageTouched:(id)arg1;
- (void)onCameraImageTouched:(id)arg1;
- (void)showMessageBox:(id)arg1;
- (void)showAtView:(id)arg1;
- (void)showFaceView;
- (void)faceTextButton:(id)arg1;
- (void)onSaveTouched:(id)arg1;
- (void)onCancelTouched:(id)arg1;
- (void)callTopicList:(id)arg1;
- (void)callAtList:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)closeNewWeiboView;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)gotoMessageBox;
- (void)saveTextToFile:(BOOL)arg1;
- (void)readTextFromFile;
- (void)clearCoreTextEditor;
- (void)changeSelectedRange:(struct _NSRange)arg1;
- (void)insertGPS:(id)arg1;
- (void)insertFeedBack:(id)arg1;
- (void)insertTopic:(id)arg1;
- (void)closeMenu:(id)arg1;
- (void)popMenu:(id)arg1;
- (void)rotateToRight;
- (void)rotateToLeft;
- (void)rightRotateImage:(id)arg1;
- (void)leftRotateImage:(id)arg1;
- (void)clearImage:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)textLengthCount;
- (void)rotateViewController:(int)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardFrameChanged:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)setReplyLabelText:(id)arg1;
- (void)createFaceTextView;
- (void)isCommentBtnTouched:(id)arg1;
- (void)viewDidLoad;
- (void)initContentAndFooter;
- (void)initToolbar;
- (id)initWithStyle:(id)arg1;

@end

