/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSArray.h"

@class NSString;

@interface NSArray (StringExtensions)
@property(readonly) NSString *stringValue;
@property(readonly, getter=arrayBySortingStrings) NSArray *sortedStrings;
@end

