/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (JSONKitSerializing)
- (id)JSONStringWithOptions:(unsigned int)arg1 serializeUnsupportedClassesUsingDelegate:(id)arg2 selector:(SEL)arg3 error:(id *)arg4;
- (id)JSONStringWithOptions:(unsigned int)arg1 error:(id *)arg2;
- (id)JSONString;
- (id)JSONDataWithOptions:(unsigned int)arg1 serializeUnsupportedClassesUsingDelegate:(id)arg2 selector:(SEL)arg3 error:(id *)arg4;
- (id)JSONDataWithOptions:(unsigned int)arg1 error:(id *)arg2;
- (id)JSONData;
@end

