/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSBundle.h"

@interface NSBundle (YAJL_GHUtils)
- (id)yajl_gh_URLForResource:(id)arg1;
- (id)yajl_gh_loadStringDataFromResource:(id)arg1;
- (id)yajl_gh_loadDataFromResource:(id)arg1;
@end

