/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSDate.h"

@interface NSDate (DateString)
+ (id)dataFromString:(id)arg1 withFormat:(id)arg2;
- (id)stringFromDateWithFormat:(id)arg1;
@end

