/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSMutableAttributedString.h"

@interface NSMutableAttributedString (WeiBo)
- (void)setAttributedStringWithFont:(id)arg1 textColor:(id)arg2 range:(struct _NSRange)arg3 infoDic:(id)arg4;
- (void)setAttributedStringParagraphStyleWithRange:(struct _NSRange)arg1 textFont:(id)arg2;
- (void)setAttributedStringParagraphStyleLineBreakModeWithRange:(struct _NSRange)arg1 breakModeStyle:(int)arg2;
@end

