/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (PerformWithMorePara)
- (void)performSelectorOnMainThread:(SEL)arg1 withObjects:(id)arg2;
- (void)performSelectorOnMainThread:(SEL)arg1 withArgumentNum:(int)arg2 withArguments:(void *)arg3;
- (id)performSelector:(SEL)arg1 withObjects:(id)arg2;
- (id)performSelector:(SEL)arg1 withArgumentNum:(int)arg2 withArguments:(void *)arg3;
@end

