/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (SNEncode)
- (id)URLDecodedStringWithCFStringEncoding:(unsigned long)arg1;
- (id)URLEncodedStringWithCFStringEncoding:(unsigned long)arg1;
- (id)URLDecodedString;
- (id)URLEncodedString;
- (id)base64EncodedString;
- (id)HMACSHA1EncodedDataWithKey:(id)arg1;
- (id)MD5EncodedString;
@end

