/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class MGTwitterEngine_Weibo, NSArray, NSMutableArray, NSString, UIScrollView;

@interface OnlineWallPaperView : UIView
{
    id delegate;
    UIScrollView *mScrollView;
    NSArray *smallBackArray;
    NSMutableArray *userWallPapersArray;
    NSString *wallPapersDirectory;
    int deleteWallPaperTag;
    MGTwitterEngine_Weibo *_engine_weibo;
}

@property(retain, nonatomic) UIScrollView *mScrollView; // @synthesize mScrollView;
@property(nonatomic) id delegate; // @synthesize delegate;
- (void)dealloc;
- (void)GetAdvertisementReceived:(id)arg1;
- (void)refreshScrollView;
- (void)addWallPaperFromArray;
- (void)loadWallpaper;
- (id)initWithFrame:(struct CGRect)arg1;

@end

