/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UserFinderPMDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSDictionary, NSMutableArray, NSString, NSTimer, NewHomelineViewController, TableRefreshHeaderView, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIPopoverController, UITableView, UITableViewCell;

@interface PmsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, TimeLineTab, UIPopoverControllerDelegate, UserFinderPMDelegate>
{
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engine;
    NSMutableArray *_items;
    NSMutableArray *newPmsArray;
    unsigned char orientionChanged;
    unsigned char verifiedStatus;
    unsigned char loadOlder;
    unsigned char loadingData;
    unsigned char selectStatus;
    UIActivityIndicatorView *moreActivity;
    NewHomelineViewController *myDetailView;
    TableRefreshHeaderView *refreshHeaderView;
    int cursor;
    int loadingTime;
    int pageNum;
    UITableViewCell *selectedCell;
    NSDictionary *selectedWeibo;
    NSString *cell_Id;
    BOOL noOlderWeibo;
    NSMutableArray *tempNewPmsArray;
    NSTimer *loadTimer;
    UILabel *deleteBtnLabel;
    BOOL editStatus;
    unsigned int deleteRow;
    UIPopoverController *contactpopoverController;
    UIImageView *bgImageView;
    UIImageView *lineImageView;
    UIImageView *loadMoreBackImage;
    UIButton *deleteBtn;
    UIButton *newPmBtn;
    UILabel *newPmBtnLabel;
    BOOL showMessage;
}

@property(retain, nonatomic) NSDictionary *selectedWeibo; // @synthesize selectedWeibo;
@property(nonatomic) unsigned char selectStatus; // @synthesize selectStatus;
@property(retain, nonatomic) TableRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(retain, nonatomic) NewHomelineViewController *myDetailView; // @synthesize myDetailView;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
- (void)PmSendSuccessed;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)onUsersPM:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)thirdViewControllerClosed;
- (void)weiboDeleteDidFinished:(id)arg1;
- (void)ChangeUser;
- (void)skinChanged:(id)arg1;
- (void)fontSizeChanged:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)onWeiboCommentTouched:(id)arg1;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)touchedDeleteButton:(id)arg1;
- (void)deleteBtnClicked:(id)arg1;
- (void)setTableViewEditStatus;
- (void)newPmBtnClicked:(id)arg1;
- (void)finishLoadingNewData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showLoadingHeader;
- (void)createHeaderView;
- (void)onLogout;
- (void)onBringToFront;
- (void)onRotated;
- (void)refresh;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2 dataFromLocal:(BOOL)arg3;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)loadNewWeibo;
- (void)loadNewPms;
- (void)loadMoreWeibo;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)loadTimeOut;
- (void)releaseTimer;
- (void)refreshSkin;
- (void)viewDidLoad;

@end

