/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class ASIOAuthRequest, NSMutableDictionary;

@interface PmTask : NSObject
{
    NSMutableDictionary *pmDict;
    ASIOAuthRequest *request;
    id delegate;
    id progressDelegate;
}

@property(retain, nonatomic) NSMutableDictionary *pmDict; // @synthesize pmDict;
@property(nonatomic) id progressDelegate; // @synthesize progressDelegate;
@property(nonatomic) id delegate; // @synthesize delegate;
@property(nonatomic) ASIOAuthRequest *request; // @synthesize request;
- (void)dealloc;
- (void)cancelRequest;
- (id)init;

@end

