/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "POIInfoDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class HomeViewTableHeaderView, MGTwitterEngine_WeiboV4, NSMutableArray, NSString, UIActivityIndicatorView, UITableView, WBSearchBar;

@interface POIListTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, POIInfoDelegate>
{
    WBSearchBar *m_search;
    UITableView *tableview;
    float latitude;
    float longitude;
    MGTwitterEngine_WeiboV4 *_engineWeiboV4;
    NSMutableArray *poilistAry;
    NSMutableArray *poiAreaAry;
    NSMutableArray *searchAry;
    NSMutableArray *searchDisplayAry;
    BOOL isNoMessage;
    id <POIInfoDelegate> poiDelegate;
    HomeViewTableHeaderView *refreshHeaderView;
    int pagenum;
    int searchlistPagenum;
    BOOL ishaveMore;
    BOOL isLoading;
    BOOL isSeaching;
    UIActivityIndicatorView *load;
    NSString *searchtext;
    NSString *xid;
    NSString *poiid;
    NSString *areaName;
    int count;
}

@property(retain, nonatomic) HomeViewTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(nonatomic) id <POIInfoDelegate> poiDelegate; // @synthesize poiDelegate;
- (void)getXID:(id)arg1;
- (void)getPOIID:(id)arg1;
- (void)getPOIName:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)basicInfoReceived:(id)arg1 forRequest:(id)arg2 responseType:(int)arg3;
- (void)finishLoadingNewData;
- (void)POIReloadData;
- (void)showLoadingHeader;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)AroundPOIReceived:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (BOOL)noMessages;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)returnView;
- (void)viewDidLoad;
- (void)setLat:(float)arg1 Lon:(float)arg2 poiID:(id)arg3 areaName:(id)arg4 Ary:(id)arg5;
- (id)initWithLat:(float)arg1 Lon:(float)arg2 poiID:(id)arg3 areaName:(id)arg4 Ary:(id)arg5;

@end

