/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface POIListCell : UITableViewCell
{
    UIImageView *locationIconImageView;
    UILabel *nameLabel;
    UILabel *addressLabel;
    UIImageView *peopleIconImageView;
    UILabel *userCountLabel;
    UIImageView *selectedImageView;
}

- (void)dealloc;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)updateCellContent:(id)arg1 index:(int)arg2 poiid:(id)arg3 areaName:(id)arg4;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

