/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface RSA : NSObject
{
}

- (id)decrypt:(id)arg1;
- (id)encrypt:(id)arg1;
- (id)encrypt:(id)arg1 usingKey:(struct __SecKey *)arg2 error:(id *)arg3;
- (id)decrypt:(id)arg1 usingKey:(struct __SecKey *)arg2 error:(id *)arg3;
- (struct __SecKey *)getPublicKey;
- (struct __SecKey *)getPrivateKey;

@end

