/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSArray, NSMutableArray, NSString, UIActionSheet, UIActivityIndicatorView, UITableView;

@interface SearchFollowerViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate, UIActionSheetDelegate>
{
    MGTwitterEngine_WeiboV4 *_engine;
    int _isSearchUser;
    NSMutableArray *_messages;
    int _pagenum;
    BOOL _lastMessage;
    UIActivityIndicatorView *_indicator;
    int _indicatorCount;
    BOOL _loading;
    NSString *_errorDesc;
    NSString *viewTag;
    UIActivityIndicatorView *activityView;
    NSString *keyword;
    NSArray *filteredArray;
    UITableView *tableView;
    UIActionSheet *progressSheet;
    id <UserFinderDelegateInSearch> delegate;
}

@property(nonatomic) id <UserFinderDelegateInSearch> delegate; // @synthesize delegate;
@property(retain, nonatomic) UIActionSheet *progressSheet; // @synthesize progressSheet;
@property(retain) NSArray *filteredArray; // @synthesize filteredArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView;
@property(retain, nonatomic) NSString *keyword; // @synthesize keyword;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView;
- (void)dealloc;
- (void)releaseActivityIndicator;
- (void)retainActivityIndicator;
- (void)searchKeyword:(id)arg1;
- (void)loadMessagesStaringAtPage:(int)arg1 count:(int)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (id)loadingMessagesString;
- (id)noMessagesString;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (BOOL)isItemInModel:(id)arg1;
- (void)fansReceived:(id)arg1 forRequest:(id)arg2;
- (void)atUsersReceived:(id)arg1 forRequest:(id)arg2;
- (void)closeHintAfterDelay;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(BOOL)arg1;
- (BOOL)noMessages;
- (void)action:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)initTableView;
- (id)initWithSearchType:(int)arg1;

@end

