/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UserInfoDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSMutableArray, NSString, NewHomelineViewController, UIActivityIndicatorView, UITableView;

@interface SearchUsersViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TimeLineTab, UIScrollViewDelegate, UserInfoDelegate, UIActionSheetDelegate>
{
    NSMutableArray *friendsArray;
    NSMutableArray *userUidArray;
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engineWeiboV4;
    UIActivityIndicatorView *moreActivity;
    int pageNum;
    int headerHeight;
    int rowNum;
    NSString *searchUserString;
    unsigned char loadOlder;
    unsigned char loadingData;
    unsigned char showStatus;
    unsigned char noNewUser;
    NewHomelineViewController *myDetailView;
    id delegate;
    BOOL noOlderWeibo;
    BOOL loadClient;
}

@property(nonatomic) NewHomelineViewController *myDetailView; // @synthesize myDetailView;
@property(nonatomic) int pageNum; // @synthesize pageNum;
@property(nonatomic) int headerHeight; // @synthesize headerHeight;
@property(nonatomic) id delegate; // @synthesize delegate;
@property(nonatomic) unsigned char showStatus; // @synthesize showStatus;
@property(retain, nonatomic) NSString *searchUserString; // @synthesize searchUserString;
@property(nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
@property(retain, nonatomic) NSMutableArray *friendsArray; // @synthesize friendsArray;
- (void)languageChanged:(id)arg1;
- (void)ChangeUser;
- (void)skinChanged:(id)arg1;
- (void)friendsButtonTouchedOn:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)usersInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)userInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)userInfoButtonTouced:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)onBringToFront;
- (void)onRotated;
- (void)refresh;
- (void)onLogout;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)changeTableViewContentInset;
- (void)loadMoreFriendsInfo;
- (void)loadFriendsInfo:(id)arg1;
- (void)loadIpadClientUserInfo;
- (void)refreshSkin;
- (void)viewDidLoad;

@end

