/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSOperation.h"

#import "SNHttpConnectDelegate-Protocol.h"

@class NSString;

@interface SNHttpConnectOperation : NSOperation <SNHttpConnectDelegate>
{
    BOOL done;
    NSString *urlString;
    void *exterInfo;
    id delegate;
    int encodeType;
}

@property(nonatomic) int encodeType; // @synthesize encodeType;
@property(nonatomic) id delegate; // @synthesize delegate;
@property(nonatomic) void *exterInfo; // @synthesize exterInfo;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString;
- (void)httpConnectDownloadDataTimeOut:(id)arg1 withFutherInfo:(void *)arg2;
- (void)httpConnectDownloadDataFailed:(id)arg1 withFutherInfo:(void *)arg2;
- (void)httpConnect:(id)arg1 successDownloadData:(id)arg2 withFutherInfo:(void *)arg3;
- (void)main;
- (void)dealloc;

@end

