/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SNHttpConnect.h"

@interface SNHttpConnect (SNXAuthManager)
- (void)preCreateConnectXOuthRequestWithURL:(id)arg1 withAccessToken:(id)arg2 withAccessSecret:(id)arg3 withHttpMethod:(id)arg4;
@end

