/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface SNSystemUtil : NSObject
{
}

+ (id)pathForMainBundleResource:(id)arg1;
+ (void)deleteFile:(id)arg1;
+ (BOOL)fileExist:(id)arg1;
+ (id)getFileModifiedTime:(id)arg1;
+ (id)getDirectoryInDocumentWithName:(id)arg1;
+ (id)getDocumentDirectory;
+ (id)GetGUID;
+ (void)showAlertViewWithAlertTitle:(id)arg1 alertString:(id)arg2;
+ (void)showAlertViewWithAlertString:(id)arg1;

@end

