/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SNHttpConnectDelegate-Protocol.h"

@class NSObject<SNXAuthDelegate>, SNHttpConnect;

@interface SNXAuth : NSObject <SNHttpConnectDelegate>
{
    SNHttpConnect *httpConnect;
    NSObject<SNXAuthDelegate> *delegate;
}

@property(retain, nonatomic) NSObject<SNXAuthDelegate> *delegate; // @synthesize delegate;
- (void)httpConnectDownloadDataTimeOut:(id)arg1 withFutherInfo:(void *)arg2;
- (void)httpConnectDownloadDataFailed:(id)arg1 withFutherInfo:(void *)arg2;
- (void)httpConnect:(id)arg1 successDownloadData:(id)arg2 withFutherInfo:(void *)arg3;
- (void)getAccessTokenWithUserName:(id)arg1 userPassword:(id)arg2;
- (void)dealloc;
- (id)init;

@end

