/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CellButton, ImageLoader, MGTwitterEngine_WeiboV4, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NewHomelineViewController, TableRefreshHeaderView, UIActionSheet, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UITableView;

@interface TopicStatusesThirdViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate, UIGestureRecognizerDelegate, TimeLineTab>
{
    NSString *keyWords;
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engineWeiboV4;
    NSMutableArray *_items;
    UIActivityIndicatorView *moreActivity;
    NSMutableDictionary *comNumberDictionary;
    unsigned char orientionChanged;
    unsigned char verifiedStatus;
    unsigned char loadingData;
    unsigned char loadOlder;
    unsigned char selectStatus;
    ImageLoader *cellImageLoader;
    TableRefreshHeaderView *refreshHeaderView;
    NewHomelineViewController *myDetailView;
    NSDictionary *selectedWeibo;
    int m_commentPage;
    int headerHeight;
    BOOL noOlderWeibo;
    UIImageView *rightBackImage;
    UIImageView *headerImageView;
    UIImageView *sendImageView;
    CellButton *followTopicButton;
    UIImageView *followImageView;
    UIButton *sendTopicButton;
    UIButton *closeBtn;
    UILabel *selectTopicLabel;
    UILabel *followLabel;
    UILabel *closeLabel;
    UILabel *backLabel;
    UILabel *sendLabel;
    BOOL backHidden;
    UIButton *backBtn;
    UIActionSheet *fellowactionSheet;
    UIImageView *topMaskImgView;
}

@property(nonatomic) BOOL backHidden; // @synthesize backHidden;
@property(nonatomic) int headerHeight; // @synthesize headerHeight;
@property(retain, nonatomic) NSDictionary *selectedWeibo; // @synthesize selectedWeibo;
@property(nonatomic) unsigned char selectStatus; // @synthesize selectStatus;
@property(retain, nonatomic) NewHomelineViewController *myDetailView; // @synthesize myDetailView;
@property(retain, nonatomic) TableRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
@property(retain, nonatomic) NSString *keyWords; // @synthesize keyWords;
- (void)backBtnClicked:(id)arg1;
- (void)closeBtnClicked:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)followTopicButtonTouched:(id)arg1;
- (void)sendTopicButtonTouched;
- (void)ChangeUser;
- (void)skinChanged:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)fontSizeChanged:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)rtCommentNumbersReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)changeSelectCellBackColor:(int)arg1 cellDic:(id)arg2 isButton:(BOOL)arg3;
- (void)changeSelectImageViewBackColor:(id)arg1 selectedStatus:(BOOL)arg2;
- (void)onWeiboRTTouched:(id)arg1;
- (void)onWeiboMapTouched:(id)arg1;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)finishLoadingNewData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showLoadingHeader;
- (void)createHeaderView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)rotateViewController:(int)arg1;
- (void)onRotated;
- (void)onLogout;
- (void)onBringToFront;
- (void)refreshCommentNumber;
- (void)refresh;
- (void)refreshTableView;
- (void)updateRtCommentNumberOfWeibos:(id)arg1;
- (void)loadNewWeibo;
- (void)loadMoreWeibo;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)changeTableViewContentInset;
- (void)handleSwipeFrom:(id)arg1;
- (void)viewDidLoad;

@end

