/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol UISplitViewControllerDelegate

@optional
- (BOOL)splitViewController:(id)arg1 shouldHideViewController:(id)arg2 inOrientation:(int)arg3;
- (void)splitViewController:(id)arg1 popoverController:(id)arg2 willPresentViewController:(id)arg3;
- (void)splitViewController:(id)arg1 willShowViewController:(id)arg2 invalidatingBarButtonItem:(id)arg3;
- (void)splitViewController:(id)arg1 willHideViewController:(id)arg2 withBarButtonItem:(id)arg3 forPopoverController:(id)arg4;
@end

