/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@interface UIView (CKRelativeLayout)
- (struct CGRect)rectRelativeToLeftView:(id)arg1 leftPadding:(float)arg2 rightView:(id)arg3 rightPadding:(float)arg4 topView:(id)arg5 topPadding:(float)arg6 bottomView:(id)arg7 bottomPadding:(float)arg8;
@end

