/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UserInfoDelegate-Protocol.h"

@class CellButton, MGTwitterEngine_WeiboV4, NSMutableArray, NSString, NSTimer, UIActivityIndicatorView, UIButton, UITableView;

@interface UserFriendsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TimeLineTab, UIScrollViewDelegate, UserInfoDelegate, UIActionSheetDelegate>
{
    NSMutableArray *friendsArray;
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engineWeiboV4;
    UIActivityIndicatorView *moreActivity;
    int pageNum;
    int rowNum;
    int loadingTime;
    NSString *nowUserId;
    unsigned char loadOlder;
    unsigned char loadingData;
    unsigned char showStatus;
    unsigned char showUserBg;
    id delegate;
    BOOL noOlderWeibo;
    BOOL noNewUser;
    NSTimer *loadOutTimer;
    CellButton *touchedfriendButton;
    UIButton *guideButton;
    BOOL showMessage;
    BOOL isThirdView;
}

@property(nonatomic) BOOL isThirdView; // @synthesize isThirdView;
@property(nonatomic) id delegate; // @synthesize delegate;
@property(nonatomic) unsigned char showUserBg; // @synthesize showUserBg;
@property(nonatomic) unsigned char showStatus; // @synthesize showStatus;
@property(retain, nonatomic) NSString *nowUserId; // @synthesize nowUserId;
@property(nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
@property(retain, nonatomic) NSMutableArray *friendsArray; // @synthesize friendsArray;
- (void)languageChanged:(id)arg1;
- (void)ChangeUser;
- (void)refreshSkin;
- (void)skinChanged:(id)arg1;
- (void)userInfoButtonTouced:(id)arg1;
- (void)cancelButtonTouched;
- (void)followButtonTouched;
- (void)scrollViewDidScroll:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)usersInfoReceived:(id)arg1 forRequest:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)onBringToFront;
- (void)onRotated;
- (void)refresh;
- (void)onLogout;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)loadMoreFriendsInfo;
- (void)loadFriendsInfo:(id)arg1;
- (void)loadTimeOut;
- (void)releaseTimer;
- (void)viewDidLoad;

@end

