/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView;

@interface UserMailInfoView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *mailInfoTableView;
    NSMutableArray *mailInfoArray;
    NSString *nameString;
    BOOL isAddUser;
    id <UserMailInfoViewDelegate> delegate;
}

@property(nonatomic) BOOL isAddUser; // @synthesize isAddUser;
@property(nonatomic) NSMutableArray *mailInfoArray; // @synthesize mailInfoArray;
@property(nonatomic) id <UserMailInfoViewDelegate> delegate; // @synthesize delegate;
@property(nonatomic) UITableView *mailInfoTableView; // @synthesize mailInfoTableView;
@property(retain, nonatomic) NSString *nameString; // @synthesize nameString;
- (void)dealloc;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

