/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TopicButtonDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSMutableArray, UIActivityIndicatorView, UIImage, UIScrollView;

@interface UserGuideHotTopicViewController : UIViewController <TopicButtonDelegate>
{
    MGTwitterEngine_WeiboV4 *_engine;
    NSMutableArray *hotTopicArray;
    UIImage *topicImage;
    UIImage *topicSelectImage;
    UIScrollView *topicScrollView;
    UIActivityIndicatorView *loadingActivity;
    int topic_x;
    int topic_y;
}

@property(retain, nonatomic) UIImage *topicSelectImage; // @synthesize topicSelectImage;
@property(retain, nonatomic) UIImage *topicImage; // @synthesize topicImage;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)userTrendsReceived:(id)arg1 forRequest:(id)arg2;
- (void)topicButtonTouced:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)onSaveTouched;
- (void)addTopicButtonView;
- (void)createTopicButton:(id)arg1 keyName:(id)arg2;
- (void)loadHotTopic;

@end

