/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class HomeViewController, MGTwitterEngine_WeiboV4, NSMutableArray, NSString, UITableView, UITableViewCell;

@interface UserLsitsSelectViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *mainTableView;
    UITableViewCell *selectListCell;
    HomeViewController *myHomeVC;
    MGTwitterEngine_WeiboV4 *_engine;
    NSMutableArray *myListsArray;
    BOOL selectStatus;
    NSString *listName;
}

@property(nonatomic) BOOL selectStatus; // @synthesize selectStatus;
@property(retain, nonatomic) NSMutableArray *myListsArray; // @synthesize myListsArray;
@property(nonatomic) HomeViewController *myHomeVC; // @synthesize myHomeVC;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)userListsReceived:(id)arg1 forRequest:(id)arg2;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)languageChanged:(id)arg1;
- (void)skinChanged:(id)arg1;
- (void)listNameSetAll;
- (void)clearListName;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (void)loadUserLists;

@end

