/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSDictionary, UIImageView, UILabel;

@interface UserInfoForCellView : UIView
{
    UIImageView *userBgImageView;
    UIImageView *imgvAvatar;
    UIImageView *verifiedImage;
    UILabel *nameLabel;
    UILabel *locationLabel;
    UILabel *followersLabel;
    NSDictionary *userInfoDic;
    int tagNum;
    _Bool userBgStatus;
    id <UserInfoDelegate> delegate;
}

@property(nonatomic) id <UserInfoDelegate> delegate; // @synthesize delegate;
@property(nonatomic) _Bool userBgStatus; // @synthesize userBgStatus;
@property(nonatomic) int tagNum; // @synthesize tagNum;
@property(retain, nonatomic) NSDictionary *userInfoDic; // @synthesize userInfoDic;
- (void)dealloc;
- (void)refreshSkin;
- (void)selectUserButtonTouched;
- (void)drawRect:(struct CGRect)arg1;
- (id)init;

@end

