/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TimeLineTab-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WeiBoCoreTextViewDelegate-Protocol.h"

@class MGTwitterEngine_WeiboV4, NSMutableArray, NSMutableDictionary, NSString, NSTimer, TableRefreshHeaderView, UIActivityIndicatorView, UITableView;

@interface UserStatusesViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TimeLineTab, WeiBoCoreTextViewDelegate>
{
    UITableView *mainTableView;
    MGTwitterEngine_WeiboV4 *_engineWeiboV4;
    NSMutableArray *_items;
    NSMutableArray *reportArray;
    int pageNo;
    int loadingTime;
    unsigned char orientionChanged;
    unsigned char verifiedStatus;
    unsigned char loadOlder;
    unsigned char favStatus;
    unsigned char reportStatus;
    unsigned char loadingData;
    unsigned char showStatus;
    UIActivityIndicatorView *moreActivity;
    TableRefreshHeaderView *refreshHeaderView;
    NSMutableDictionary *comNumberDictionary;
    NSTimer *loadOutTimer;
    NSString *nowUserId;
    unsigned char showUserBg;
    id delegate;
    BOOL loadingOLder;
    BOOL noOlderWeibo;
}

@property(nonatomic) unsigned char showUserBg; // @synthesize showUserBg;
@property(nonatomic) id delegate; // @synthesize delegate;
@property(nonatomic) unsigned char showStatus; // @synthesize showStatus;
@property(retain, nonatomic) TableRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView;
@property(retain, nonatomic) NSString *nowUserId; // @synthesize nowUserId;
@property(retain, nonatomic) NSMutableArray *_items; // @synthesize _items;
@property(nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
- (void)weiBoCoreTextViewTouchedAttributedInfo:(id)arg1 index:(int)arg2 tag:(int)arg3;
- (void)skinChanged:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)refreshSkin;
- (void)fontSizeChanged:(id)arg1;
- (void)onWeiboRTTouched:(id)arg1;
- (void)onWeiboMapTouched:(id)arg1;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)finishLoadingNewData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showLoadingHeader;
- (void)createHeaderView;
- (void)onLogout;
- (void)onBringToFront;
- (void)onRotated;
- (void)refresh;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)rtCommentNumbersReceived:(id)arg1 forRequest:(id)arg2;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (void)updateRtCommentNumberOfWeibos:(id)arg1;
- (void)loadMoreWeibo;
- (void)loadUserStatuses:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)loadTimeOut;
- (void)releaseTimer;
- (void)viewDidLoad;

@end

