/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSOperation.h"

@class NSString;

@interface WBAudioDecodeOperation : NSOperation
{
    id <WBAudioDecodeOperationDelegate> delegate;
    NSString *inputFile;
    NSString *outputFile;
    BOOL success;
}

@property(retain, nonatomic) NSString *outputFile; // @synthesize outputFile;
@property(retain, nonatomic) NSString *inputFile; // @synthesize inputFile;
@property id <WBAudioDecodeOperationDelegate> delegate; // @synthesize delegate;
- (void)cancel;
- (void)finishedDecoding;
- (void)main;
- (void)dealloc;
- (id)initWithAMRFile:(id)arg1 waveFile:(id)arg2 delegate:(id)arg3;

@end

