/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WBAudioRecorderDelegate <NSObject>
- (void)recordingDidCancel;
- (void)recordingDidFailWithErrorType:(int)arg1;
- (void)recordingDidFinishWithFile:(id)arg1 fileType:(int)arg2;
- (void)recordingDidStartEncoding;

@optional
- (void)afterConfirmButtonPressed:(id)arg1;
- (void)updateMetersWithAveragePower:(float)arg1;
@end

