/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "WBAudioPlayerDelegate-Protocol.h"
#import "WBAudioRecorderDelegate-Protocol.h"

@class NSString, NSTimer, UIButton, UIImageView, UILabel, WBAudioRecorder;

@interface WBAudioRecorderViewController : UIViewController <WBAudioRecorderDelegate, WBAudioPlayerDelegate>
{
    id <WBAudioRecorderViewControllerDelegate> delegate;
    WBAudioRecorder *audioRecorder;
    UIImageView *recordButtonBgView;
    UIImageView *recordButtonView;
    UIButton *recordButton;
    UIButton *cancelButton;
    UIButton *sendVoiceButton;
    NSString *recordingFile;
    NSString *errorMessage;
    NSTimer *currentDurationTimer;
    int duration;
    BOOL recordingFlag;
    float angle;
    NSTimer *recordAnimationTimer;
    int flag;
    UILabel *currentDurationLabel;
    UILabel *timeLabel;
    UIImageView *recordBgView;
}

@property BOOL recordingFlag; // @synthesize recordingFlag;
@property(retain, nonatomic) NSString *recordingFile; // @synthesize recordingFile;
@property(nonatomic) id <WBAudioRecorderViewControllerDelegate> delegate; // @synthesize delegate;
- (void)refreshSkin;
- (void)skinChanged:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)audioDidStopPlaying;
- (void)audioDidFailToPlayWithErrorType:(int)arg1;
- (void)audioDidEndDecodingWithAudioFile:(id)arg1;
- (void)audioDidStartDecodingWithAudioFile:(id)arg1;
- (void)recordingDidFailWithErrorType:(int)arg1;
- (void)recordingDidFinishWithFile:(id)arg1 fileType:(int)arg2;
- (void)recordingDidStartEncoding;
- (void)afterConfirmButtonPressed:(id)arg1;
- (void)confirmButtonPressed:(id)arg1;
- (void)updateElapsedTime:(id)arg1;
- (void)stopRecordingButtonPressed:(id)arg1;
- (void)recordButtonPressed:(id)arg1;
- (void)currentTimer;
- (void)startRecord;
- (void)rotateTwo;
- (void)rotateOne;
- (void)rotate;
- (void)recordImageAnimation;
- (void)removeRecordedFile;
- (void)cancelButtonPressed:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

