/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData;

@interface WBGIFFrame : NSObject
{
    NSData *data;
    NSData *header;
    double delay;
    int disposalMethod;
    struct CGRect area;
}

@property(copy, nonatomic) NSData *header; // @synthesize header;
@property(nonatomic) struct CGRect area; // @synthesize area;
@property(nonatomic) int disposalMethod; // @synthesize disposalMethod;
@property(nonatomic) double delay; // @synthesize delay;
@property(copy, nonatomic) NSData *data; // @synthesize data;
- (void)dealloc;

@end

