/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ImageLoader, MGTwitterEngine_WeiboV4, NSDictionary, NSMutableArray, NSString, NewWeiBoDetailThirdViewController, UIActionSheet, UIActivityIndicatorView, UITableView;

@interface WeiboDetailCommentsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate>
{
    NSMutableArray *_items;
    UITableView *mainTableView;
    ImageLoader *cellImageLoader;
    NSDictionary *weiboInfo;
    unsigned long long commentID;
    MGTwitterEngine_WeiboV4 *_engine_v4;
    BOOL noOlderWeibo;
    BOOL loadOlder;
    BOOL loadingData;
    UIActivityIndicatorView *moreActivity;
    int m_commentPage;
    NSMutableArray *mutableUrlArray;
    NSDictionary *deleteComment;
    UIActionSheet *urlactionSheet;
    UIActionSheet *copyactionSheet;
    NewWeiBoDetailThirdViewController *mNewWeiBoDetailThirdViewController;
    int *selectedCommentCell;
    NSString *deleteRequest;
    unsigned long long nextCursor;
    long long maxId;
}

@property(nonatomic) NewWeiBoDetailThirdViewController *mNewWeiBoDetailThirdViewController; // @synthesize mNewWeiBoDetailThirdViewController;
@property(retain, nonatomic) NSDictionary *weiboInfo; // @synthesize weiboInfo;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView;
- (void)fontSizeChanged:(id)arg1;
- (void)recountCoreTextViewHeight;
- (void)skinChanged:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)onUserPhotoTouched:(id)arg1;
- (void)onWeiboThumbTouched:(id)arg1;
- (void)onWeiboRecommentDeleteTouched:(id)arg1;
- (void)onWeiboRecommentUrlTouched:(id)arg1;
- (void)onWeiboRecommentTouched:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (id)tableviewCellWithReuseIdentifier:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)refresh;
- (void)loadMoreWeibo;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)refreshSkin;
- (void)viewDidLoad;

@end

