/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIScrollView.h"

@class MGTwitterEngine_WeiboV4, NSMutableArray, UIView;

@interface WeiBoImageScrollView : UIScrollView
{
    NSMutableArray *allImageViewArray;
    NSMutableArray *allLabelArray;
    NSMutableArray *allViewArray;
    MGTwitterEngine_WeiboV4 *_engine;
    NSMutableArray *_items;
    _Bool loadOlder;
    _Bool loadingData;
    _Bool openImageStatus;
    _Bool pageStusts;
    int pageNum;
    int imageNum;
    struct CGPoint touchBeginPoint;
    UIView *imageBackView;
    _Bool touchStatus;
}

@property(nonatomic) UIView *imageBackView; // @synthesize imageBackView;
@property(nonatomic) _Bool touchStatus; // @synthesize touchStatus;
@property(nonatomic) _Bool openImageStatus; // @synthesize openImageStatus;
- (void)requestFailed:(id)arg1 withError:(id)arg2;
- (void)requestSucceeded:(id)arg1;
- (void)statusesReceived:(id)arg1 forRequest:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (void)loadNewWeibo;
- (void)loadMoreWeibo;
- (void)viewRotationToInterfaceOrientationUp;
- (void)viewRotationToInterfaceOrientationLeft;
- (void)exitAllImageView;
- (void)changeOpenImageStatus;
- (void)loadImage;
- (id)initWithFrame:(struct CGRect)arg1;

@end

