/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSDictionary, NSMutableArray, NSMutableAttributedString, NSString, UIColor, UIFont, WeiBoAttributedStringEditor;

@interface WeiBoCoreTextView : UIView
{
    NSDictionary *weiBoDic;
    NSDictionary *touchedDic;
    NSMutableArray *highLightInfoArray;
    NSMutableArray *faceTextInfoArray;
    NSMutableAttributedString *weiBoText;
    UIFont *defaultFont;
    UIFont *highLightedFont;
    UIColor *defaultColor;
    UIColor *highLightedColor;
    UIColor *selectedColor;
    int paragraphSep;
    WeiBoAttributedStringEditor *weiBoStringEditor;
    struct CGRect drawingRect;
    struct _NSRange touchedRange;
    struct __CTFrame *textFrame;
    BOOL inSelected;
    id <WeiBoCoreTextViewDelegate> delegate;
    int _index;
    BOOL isComment;
    NSString *userName;
}

@property(retain, nonatomic) WeiBoAttributedStringEditor *weiBoStringEditor; // @synthesize weiBoStringEditor;
@property(nonatomic) int index; // @synthesize index=_index;
@property(nonatomic) NSString *userName; // @synthesize userName;
@property(nonatomic) BOOL isComment; // @synthesize isComment;
@property(nonatomic) id <WeiBoCoreTextViewDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSDictionary *touchedDic; // @synthesize touchedDic;
@property(retain, nonatomic) NSDictionary *weiBoDic; // @synthesize weiBoDic;
- (void)dealloc;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)isTouchedHighLightTextWith:(struct _NSRange)arg1;
- (long)getStringIndexInFrameWith:(struct CGPoint)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawFaceImageWithFrame:(struct __CTFrame *)arg1 WeiboContext:(struct CGContext *)arg2 FaceArray:(id)arg3;
- (void)resetAttributedStringParagraphStyleLineBreakMode;
- (void)setAttribution:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)createWeiBoAttributedStringWith:(id)arg1;

@end

