/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MKAnnotation-Protocol.h"

@class NSString;

@interface WeiboAnnotation : NSObject <MKAnnotation>
{
    CDStruct_2c43369c coordinate;
    NSString *title;
    NSString *subtitle;
}

@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(nonatomic) CDStruct_2c43369c coordinate; // @synthesize coordinate;
- (id)initWithCoordinate:(CDStruct_2c43369c)arg1;
- (id)init;

@end

