/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UISearchBar.h"

@interface WeiboSearchBar : UISearchBar
{
}

- (void)dealloc;
- (void)setShowsCancelButton:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setTitle:(id)arg1 forState:(unsigned int)arg2 forView:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)setCloseButtonTitle:(id)arg1 forState:(unsigned int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

