/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSDictionary, NSString, UIButton, UIImageView;

@interface WidgetView : UIView
{
    NSDictionary *widgetDic;
    struct CGRect home;
    NSString *titleString;
    UIButton *deleteButton;
    UIImageView *widgetImageView;
    UIImageView *recommendImageView;
    UIView *allView;
    BOOL editStatus;
    id <WidgetViewDelegate> delegate;
}

@property(nonatomic) BOOL editStatus; // @synthesize editStatus;
@property(nonatomic) UIButton *deleteButton; // @synthesize deleteButton;
@property(nonatomic) struct CGRect home; // @synthesize home;
@property(retain, nonatomic) NSDictionary *widgetDic; // @synthesize widgetDic;
@property(retain, nonatomic) NSString *titleString; // @synthesize titleString;
@property(nonatomic) id <WidgetViewDelegate> delegate; // @synthesize delegate;
- (void)languageChanged:(id)arg1;
- (void)dealloc;
- (void)widgetViewBackHomeAnimation;
- (void)widgetButtonTouched;
- (void)widgetDeleteButtonTouched;
- (void)loadWidgetImageView:(id)arg1;
- (void)addSelectedWidgetToCache;
- (void)widgetInvertAnimation;
- (void)widgetRightAnimation;
- (void)widgetLeftAnimation;
- (void)widgetEndAnimation;
- (void)widgetBeginAnimation;
- (id)initWithWidgetDic:(id)arg1;
- (id)initWithImage:(id)arg1 widgetName:(id)arg2;
- (BOOL)existWidgetFromeArray:(id)arg1 withDictionary:(id)arg2;

@end

