/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "YAJL_GTMBase64.h"

@interface YAJL_GTMBase64 (PrivateMethods)
+ (unsigned int)baseDecode:(const char *)arg1 srcLen:(unsigned int)arg2 destBytes:(char *)arg3 destLen:(unsigned int)arg4 charset:(const char *)arg5 requirePadding:(BOOL)arg6;
+ (unsigned int)baseEncode:(const char *)arg1 srcLen:(unsigned int)arg2 destBytes:(char *)arg3 destLen:(unsigned int)arg4 charset:(const char *)arg5 padded:(BOOL)arg6;
+ (id)baseDecode:(const void *)arg1 length:(unsigned int)arg2 charset:(const char *)arg3 requirePadding:(BOOL)arg4;
+ (id)baseEncode:(const void *)arg1 length:(unsigned int)arg2 charset:(const char *)arg3 padded:(BOOL)arg4;
@end

