/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSError;

@interface YAJLParser : NSObject
{
    struct yajl_handle_t *handle_;
    id <YAJLParserDelegate> delegate_;
    unsigned int parserOptions_;
    NSError *parserError_;
}

@property(readonly, nonatomic) unsigned int parserOptions; // @synthesize parserOptions=parserOptions_;
@property(nonatomic) id <YAJLParserDelegate> delegate; // @synthesize delegate=delegate_;
@property(retain, nonatomic) NSError *parserError; // @synthesize parserError=parserError_;
- (unsigned int)startParse:(id)arg1;
- (unsigned int)readyStartParse;
- (unsigned int)parse:(id)arg1;
- (void)_endArray;
- (void)_startArray;
- (void)_endDictionary;
- (void)_startDictionary;
- (void)_mapKey:(id)arg1;
- (void)_add:(id)arg1;
- (void)_cancelWithErrorForStatus:(int)arg1 message:(id)arg2 value:(id)arg3;
- (id)_errorForStatus:(int)arg1 message:(id)arg2 value:(id)arg3;
- (void)dealloc;
- (id)initWithParserOptions:(unsigned int)arg1;
- (id)init;

@end

