/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "YAJLParserDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, YAJLParser;

@interface YAJLDocument : NSObject <YAJLParserDelegate>
{
    id root_;
    YAJLParser *parser_;
    id <YAJLDocumentDelegate> delegate_;
    NSMutableDictionary *dict_;
    NSMutableArray *array_;
    NSString *key_;
    NSMutableArray *stack_;
    NSMutableArray *keyStack_;
    int currentType_;
    unsigned int parserStatus_;
}

@property(nonatomic) id <YAJLDocumentDelegate> delegate; // @synthesize delegate=delegate_;
@property(readonly, nonatomic) unsigned int parserStatus; // @synthesize parserStatus=parserStatus_;
@property(readonly, nonatomic) id root; // @synthesize root=root_;
- (void)_pop;
- (void)parserDidEndArray:(id)arg1;
- (void)parserDidStartArray:(id)arg1;
- (void)parserDidEndDictionary:(id)arg1;
- (void)parserDidStartDictionary:(id)arg1;
- (void)_popKey;
- (void)parser:(id)arg1 didMapKey:(id)arg2;
- (void)parser:(id)arg1 didAdd:(id)arg2;
- (unsigned int)startParse:(id)arg1 error:(id *)arg2;
- (unsigned int)readyParse:(id *)arg1;
- (unsigned int)parse:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)initWithData:(id)arg1 parserOptions:(unsigned int)arg2 capacity:(int)arg3 error:(id *)arg4;
- (id)initWithData:(id)arg1 parserOptions:(unsigned int)arg2 error:(id *)arg3;
- (id)initWithParserOptions:(unsigned int)arg1 capacity:(int)arg2;
- (id)initWithParserOptions:(unsigned int)arg1;
- (id)init;

@end

